### ISSUE TITLE
Multi Backend e.g. .Net

### ISSUE THREAD

**Issue by sirinath** [typelead/eta#116]
Great project!

Wondering if the scope can be extended to including other backends like .net rather than just JVM backend. I.e., one code base to rule them all!

**Comment by rahulmutt** [comment]
This is a FAQ, I'll add it to the docs at some point. Given that .NET has similar bytecode to Java, this would be a great thing to try out in the future. This is something I can see us trying out in 2-3 years, but not anytime soon. We need to get it right on the JVM first.
