### ISSUE TITLE
Reusing Existing Code Bases

### ISSUE THREAD

**Issue by sirinath** [typelead/eta#117]
ETA is fairly a new language and as of now still is not different from Haskell syntax thought it might diverse in the future. So in moving into ETA there should be a migration path for the existing code. This can be Java Source Code or Bytecode. In the current path it has a great story for Haskell and Java.

What I propose is initially you have a Java to ETA transpiler (perhaps through couple of layers if ETA IRs/ILs) which can work on Java source code and also reverse engineer Java Bytecode into ETA. For any external observer the effect of running the original code and ETA should be the same through the order strictness and other aspects may differ.

This can be further leveraged to transpile other code into ETA and also convert other IR/IL/ByteCode/Machine Code back to ETA. The resulting code base can be used to target particular backend. The implication of this is through ETA your might be able to mix and match code written in say Java, C#, F#, OCaml, ML, etc. without FFI overheads and global optimisation across language boundaries. As ETA will support .net in the future any other approach will not support cross translation of Java ByteCode and .net IL which will not give a synergistic effect in supporting .net as only ETA and perhaps Haskell code might be cross targeted without ability to reused ecross ecosystem. I feel it is doable if this is through through upfront.

This infrastructure can be used to support many multiple version of Haskell and also incorporate changes quickly either in Haskell or any other supported language or binary format.

Also being able to work with either source code or binary formats will invalidate the need of FFI.

Also the front end infrastructure supporting transpiling can be used even define DSLs as in itself is a metaprogramming system.

**Comment by rahulmutt** [comment]
These are some pretty cool ideas. Check out GraalVM/Truffle upcoming in JDK 9 that allow the sort of global optimisation across languages that you're talking about. They used it with JRuby/C allowing for huge boosts in speed.

Being able to interoperate between .NET and Java is pretty cool but it's a lot more difficult than it sounds. The main problem is the lack of congruence in commonly used standard APIs and key distinctions in VM semantics/implementations. It's not a problem I want to spent time on right now, and probably something I'll have more time for later on once I have access to more resources (time especially). I am also quite inexperienced with the .NET ecosystem, which is the primary reason for differing this.

I like idea of a Java to Eta transpiler, it would illustrate to new Java developers how to translate side-effecting Java code into monadic code via the `Java` monad. But that mapping is a bit tricky due to laziness as you said, but overall it can be done. Not sure if it's worth pursuing immediately but I can see that being worked on 3-4 months down the line. Kotlin actually does this via its plugin on IntelliJ and it has a certain "wow" factor being able to right click on a Java file and automatically have it convert to Kotlin style.

Thanks for the input!

**Comment by sirinath** [comment]
Make the JVM backend so the incremental effort to move something like .net, LLVM or directly to native trivial when it is in pace, i.e., translate into an abstract IL/IR before spitting out exact bytecode. You might be wondering Haskell already has this but if you can do this in a mixed language project where some code is in JVM languages, sone in .net, some in LLVM IR and some native without FFI overhead and optimisation across language boundaries. 

Scala/Dotty is standedising the AST: https://docs.google.com/document/d/1h3KUMxsSSjyze05VecJGQ5H2yh7fNADtIf3chD3_wr0/edit, https://docs.google.com/document/d/1Wp86JKpRxyWTqUU39H40ZdXOlacTNs20aTj7anZLQDw/edit, also the Graal/Truffle framework.

One thing is you can use a documented AST format. Also at a lower level you can perhaps have a IR/IL like Web Assembly which used a binary format similar to lisp.

Also in Graal/Truffle [Sulong](https://github.com/graalvm/sulong) is usde to optimise across language boundries.

**Comment by rahulmutt** [comment]
Translating into an abstract IR is something I have planned for a while and I'll work on things like that once this becomes stable and I want to start optimising.

Thanks for the references to the Dotty AST, it's very interesting.

**Comment by sirinath** [comment]
Also Swift and Rust uses IR layer before LLVM.

**Comment by puffnfresh** [comment]
Doesn't GHC already have a few different intermediate representations already?

**Comment by sirinath** [comment]
I feel ETA should perhaps be different perhaps borrowing from other formats. This should be such that ETA can evolve separately and also support Haskell (different versions), Java and other code formats.

**Comment by rahulmutt** [comment]
@puffnfresh Yeah it has three: Core, STG, and Cmm. Of those Core and STG are mature and well-designed. Cmm is designed to be a portable untyped assembly language which works for compiling to native, but a lot of the IR makes no sense in the context of compiling to the JVM. Hence the need for a good intermediate language that's suitable for optimising typed bytecodes. 

In formulating a good IR between STG and the bytecode, it's probably better taking inspiration from [Soot](https://sable.github.io/soot/) which is a JVM bytecode analysis framework that does some really cool optimisations. If used properly, we can just add that on as an optimisation pass and focus efforts on making the runtime better and maybe making new Core2Core or Stg2Stg transformations that are suitable for the mapping we have laid out now.

@sirinath Sounds like a good idea.

**Comment by sirinath** [comment]
Since ETA might evolve independently or Haskell keep the IR independent or any back end format. Also look at Web Assembly not to directly use it but might give inspiration for design. With regard to IR keep it typed, effectfull and proof carrying so not that you will use all this at the start but you can use it when the need arises without revising this too often. Also optimisation and transformations targeted at each stage can evolve separately.

**Comment by sirinath** [comment]
Also be inspired by Soot and even LLVM and WebKit [B3](https://webkit.org/blog/5852/introducing-the-b3-jit-compiler/) but don't depent on Soot since this is JVM specific and Licensing.

Some projects will not be able to use ETA if you have a *GPL dependency.

**Comment by rahulmutt** [comment]
So the choice of IR at the end of the day depends on the need and the resources at hand. If I end up deferring the design of the IR for many months, I'll be able to come up with an IR that addresses all the issues mentioned which I hope to be the case.

Thanks for the advice, links, and references. Lots to explore and think about. Good point about licensing, I need to be more wary about that.

You mentioned "typed, effectual, and proof-carrying" - do you happen to have any IR examples that meet this criteria?

**Comment by sirinath** [comment]
Typed IR:
 
- WebAssembly
- http://www.cs.cornell.edu/talc/
- https://github.com/sweirich/tal

Also see: Rust MIR and Swift IR.

Layered / intermediate languages:

- System Red: http://static.red-lang.org/red-system-specs-light.html (intermidiate language for red)
- http://groupoid.space/exe.htm
- https://github.com/FStarLang/kremlin

Proof Carrying Code:

 - http://groupoid.space/om.htm 
 - see research by George C. Necula and Peter Lee

Effectful Layered Language:

- https://github.com/FStarLang/kremlin

Other than for Kremlin which is slightly restricted language traspiles to C I am not sure whether effectful languages use IR which retains this information but this is worth exploring as this information can be retained by type tagging or type annotations at the IR level. Languages like Nim directly translates to C++. Dotty's TASTY may get this once Dotty supports effects but this is just speculation. See https://www.fstar-lang.org/, http://www.eff-lang.org/, Dotty, http://nim-lang.org/, http://rise4fun.com/Dafny, http://www.cs.utexas.edu/users/moore/acl2/, http://www.ats-lang.org/, good starting point.

**Comment by rahulmutt** [comment]
Great stuff. I'll put all this into one place somewhere so it doesn't get lost and close the issue once it's been transferred.

**Comment by sirinath** [comment]
OK. Some of the references are a bit loose there still no IR which deals with all aspects, at least to extend I have in mind.

**Comment by rahulmutt** [comment]
Closing as this is a large infrastructure change, this should follow the Eta Proposal Process:

https://github.com/typelead/eta-proposals
