### ISSUE TITLE
Drop Haskell Compatibility for .eta but retain it only for .hs

### ISSUE THREAD

**Issue by sirinath** [typelead/eta#118]
Since one goal is:

> accessibility for beginners from imperative languages, especially Java

It might be more flexible to drop the compatibility for ETA language (.eta files) but retain it for .hs files and even detect and support many Haskell version. The implication of this is at the start ETA infrastructure can understand the ETA language itself, Java ByteCode and GHC 7.10.3's Haskell, but can later extended. (Currently ETA infrastructure can understand the Java ByteCode and GHC 7.10.3's Haskell as there is no ETA language.)

Dropping the compatibility for eta files means this can evolve independently to pursue the above goal better than also dragging the technical debt of compatibility. This can be addressed separately through https://github.com/typelead/eta/issues/117 in a more broader context which can include "compatibility with Haskell, OCaml, Java, C#, F#, C/C++, R, Python, Scala, etc."

**Comment by rahulmutt** [comment]
I intended that .hs files will always be recognised and only support the features of GHC Haskell 7.10.3 and before. Any .eta files will have full support of the Eta language. Is this what you meant?

**Comment by sirinath** [comment]
To start with. Depending on ETA it might be easy to map even 8.0.1 to ETA hence support different version. But having said that I feel it is better to design ETA independently and from scratch than base it on Haskell and have Haskell also translate into ETA starting with GHC Haskell 7.10.3 and later other versions.

**Comment by rahulmutt** [comment]
Basing it on GHC 7.10.3 was to have a starting point so that it's easy to get something production-ready sooner. Another reason was to get access to Hackage so I can solve the libraries problem early on. It's a lot of baggage to carry and I'll probably feel the weight once the language evolves in drastic ways. Making it in an independent language altogether I can only see happening if I happen to acquire sufficient resources and there's a dire need for it. I'm not aiming for a perfect solution from day one. Just one that works and keeps getting better over time.

**Comment by sirinath** [comment]
Initially keep GHC 7.10.3 and ETA experimental for a while and some point when ETA is somewhat mature transpile GHC 7.10.3 to ETA but from the onset designing ETA will be able to address some of the more pressing needs in typed programming not envisaged during the design or Haskell. Also haskell is hard for anybody from an imperative background. 

Perhaps I can open another issue from what is best expected from a language designed today without any previous technical debt.

My feeling is this is the best way to go. You get your MVP out using Haskell and then to ETA with Haskell -> ETA so any investment in Haskell does not break.

**Comment by rahulmutt** [comment]
> ...some of the more pressing needs in typed programming not envisaged during the design or Haskell.

Can you expand on this? I don't want to venture too far off since I'm trying to attract people who have already been sold on Haskell/Typed FP and want something that is geared towards industry since the alternatives are quite limited in their abilities to apply purely function techniques.

> Perhaps I can open another issue from what is best expected from a language designed today without any previous technical debt.

That would be great!

**Comment by sirinath** [comment]
I will put this together and open another issue.

There is Haskell, OCaml, F#, ML, Scala, etc. the best way to package ETA would be best and cream or FP than just geared to one language to attract users from all languages. There are things you can borrow from OCaml but in which case you cannot have change ETA.

**Comment by rahulmutt** [comment]
I'm open to taking ideas from other languages, but for the most part I'm sticking with Haskell as it is fixing the warts as much as possible. I don't want to make Eta complex with too many features either. If the features from the other language can't be implemented in Eta, or is very useful and should have special compiler/runtime support I can think about it.

**Comment by sirinath** [comment]
What I am going to propose is: making the language simple but like lego brings which can com together to build something bigger. Also make it accessible from people from C, Java, C# background. Also easier for the programmer. Also support Haskell by translating it into ETA and not by makes ETA Haskell++--. Wait until I start another issue with more information.

**Comment by rahulmutt** [comment]
Closing as this is a major language change, this should follow the Eta Proposal Process:

https://github.com/typelead/eta-proposals
