### ISSUE TITLE
ETA Design Proposal

### ISSUE THREAD

**Issue by sirinath** [typelead/eta#119]
ETA is really appealing since
1. Typed programming to the enterprise
2. Promises easy to learn for people from imperative languages
3. Provides Haskell compatibility
4. Provides JVM compatibility with the option to extend in the future

But having said that if ETA is Haskell++/-- this will not achieve some of the goals especially bringing people from imperative languages on to it. Other issues might be that there will be divergence from Haskell itself reducing the appeal from the Haskell community adopters.

So what I propose if make ETA independent language to which Haskell and Java can translate into. This translator need not be a monolithics translator but a series of transformation which can introduce introduce feature by feature and which makes it easier to use. Also if anybody needs a particular feature this should be easy and modular to introduce. (E.g. https://github.com/cwi-swat/recaf, JetBrains MPS, Xtext)

Also in supporting a large language like Haskell and Java may introduce subtle incompatibilities and bugs. The system should be easy enough to debug and maintain. The time spent of any experimental feature should be minimal with easy prototyping capabilities.

Also time to market is important. For this the best is 1st get MVP which can translate Haskell in .hs files into ByteCode and then look at translating Haskell into ETA.

1st starting point perhaps would be a low level intermediate language based on S and M expressions. This can be even have a SSA layer. Good starting point to get inspiration Web Assembly and WebKit B3.

The next level perhaps should be a mid level intermediate  language which is a typed assembly perhaps inspired by: [Om](http://groupoid.space/om.htm), TAL (http://www.cs.cornell.edu/talc/, https://github.com/sweirich/tal). In addition it should tract inferred effects for better optimisation. Any effect which is not IO need not have a runtime representation and should be optimised away. Also memory operation should be factored as effects and should be optimised least memory usage and fasted speed. Also see research at: https://secure-compilation.github.io/ assebly taging.

On top of the TAL a more higher level intermediate  language like [EXE](http://groupoid.space/exe.htm), Shen, Racket, Redex Racket, Typed Clojure, http://www.shenlanguage.org/, which is homoiconic and represent the syantax of another language in. Perhaps at this level you should be able to parse text into PHOAS/HOAS but needs further investigation. But some form of reusable, modular, parameterised AST will be needed. Also there should exist a very generic parser which can very efficiently and incrementally parse text and binary and also recreate original input without losing fidelity. This should be usable for transformations also when both formats are defined. Also another area perhaps to address is term rewriting  for optimisation. Perhaps you can get inspiration from: https://github.com/dotty-linker/dotty, http://purelang.bitbucket.org/, https://bitbucket.org/inkytonik/kiama, http://www.rascal-mpl.org/, http://nim-lang.org/. You can have many more intermediate language representation, but unlike other languages the intermediate languages even the lowest levels targeted at the machine should be user accessible and programmable. Also perhaps staging support: https://scala-lms.github.io/. Also the language and library at this point should be geared towards parsing, code generation, code transformation, code analysis, etc. See: http://flix.github.io/, Red, Nitra,  #Nemerle.

Based on the above define ETA. Using this implement the Haskell and Java syntax. At this stage you would need Quasi Quotes also which can translate different language syntax into the AST representation in the layer above. (http://blog.tweag.io/posts/2016-10-17-inline-java.html implements QQ through FFI but ideally quatation should undestant the embeded language for proper optimisation.)

Since each layer is simpler and functionality is added in layers maintaining correctness and will be easy and would be maintainable. Also the design should be such that you will not encounter any complexity related very hard to fix bugs. Any new language feature should be easy to add. This would mean you can have different version of Haskell or even other languages with minimal effort. Regarding correctness see: https://secure-compilation.github.io/

Coming to the point this will be used in the enterprise, there are some companies still using languages like COBOL since they have a large code base. This would help migrate such code based to ETA and even interop between languages without FFIs and also optimise beyond language boundaries.

Also more of the world's programmers are in fact is imperative with FP seaming alien. Haskell is difficult hence I feel ETA should be much simpler with some powerful features. All of Haskell should not be put into this and there should be features which might not be in Haskell needs to be in it.

Regarding the type system I feel you should have simpler type system by default but with is composable and extensible to the extent that it can represent any type system. https://redex.racket-lang.org/, https://github.com/lexi-lambda/rascal. Also please go through this presentation in detail: http://www.cs.utah.edu/~rafkind/tmp/slides.pdf, http://www.cs.utah.edu/~rafkind/papers/fool09.pdf, http://www.ccs.neu.edu/home/stchang/pubs/ckg-popl2017.pdf

Type checking should be also extensible. See Type checking as a function. Truly à la carte in http://typedclojure.org/, JetBrains MPS, http://mbeddr.com/, etc.

A salable and extensible language the user can also add to the language like writing libraries with scoped extensions than language forks, hacks and plugins. So if someone wants any version syntax of a particular language this this should be doable.

There are some pressing issues in concurrent and distributed programming which needs solving. Currently mainstream languages do not directly support process calculi and algebras. So if a language is designed today I believe even a general purpose language should be able to support this. There are DSLs like http://www.scribble.org/ but it is best thought through at the language level.

Currently there is a lot of interest on stream and reactive programming. So such constructs should be easily supported and language should be supported.

Also simple to use generators and data structures should be present. 

Since there are many people coming from OO background best is to have OO scheme also. Perhaps the OO features can through Heterogeneous data structures. Also records which can be supported the same way.

Typing should be a mixed mode with structural and normative. Good application of structural typing is the OCaml module system. You can easily switch in and mock modules as long as they provide the same interface. Structural typing also gives the feel of a dynamic language like.

There are many users of dynamic languages. So type inference should be tip top to attack a following from this crowd. One language that sells well in this space is: http://nim-lang.org/

The language should support ML and Big Data most of which algorithms are in LA. So LA types and constructs should have out of the box and support array programming. Also you should be able to slice and manipulate data. Maybe you can borrow some ideas from http://julialang.org/, http://www.sac-home.org/, http://x10-lang.org/, http://chapel.cray.com/, https://projectfortress.java.net/. Also please watch: https://www.youtube.com/watch?v=EZD3Scuv02g

Also a well desined operator system like found in Fortress (https://www.youtube.com/watch?v=EZD3Scuv02g) would be of immense value.

Code contacts and verifiability is also important. See: Fortress, http://why3.lri.fr/, http://www.spark-2014.org/, https://github.com/Microsoft/dafny, http://www.cs.utexas.edu/users/moore/acl2/, http://www.ats-lang.org/

Also constraint typing found in X10 would be of immense value to deal with dimensional data types. E.g. matrix should have these dimension. Also dependent typing system which also supports constraint typing would be a welcome addition while insulating beginners from complexity.

Another possible areas to explore is capabilities: ponylang.org, type state: http://www.cs.cmu.edu/~./aldrich/plaid/. Some of these perhaps can be achieved with phantom types. Also Dotty is trying to add Phantom types. Also another area is effects. This is also another area Dotty is trying to add to Scala. This is very much worthwhile to consider. http://www.eff-lang.org/, http://nim-lang.org/, https://www.fstar-lang.org/. Also effects should be used for optimisation; anything that is not a IO dependent should be optimise away and should not have a runtime memory or compounding overhead whatsoever.

Also pattern machining should be formalised and 1st class (see: Pattern Calculus and F# active pattern).

Also we have to deal with quantities and units so the language should be able to support this. (F#, http://www.squants.com/) This help errors due to mismatch in dimetions. You cannot assign a meter to a second. cm and m will auto convert on assignment. Also see: https://frinklang.org/

Also languages like Pascal you could define rages and refinements as types. This also would be a good addition. https://github.com/fthomas/refined. This should be used in very aggressive optimisation.

Also currently in the financial sector and many businesses modeling is done using spreadsheets. So if you can give a way to easily model spreadsheet interaction this will be a great sell but the language should be easy. (See: http://www.red-lang.org/2016/07/native-reactive-spreadsheet-in-17-loc.html but Red is not a easy language). Something perhaps that has the feel of http://orgmode.org/ but the calabilities of http://www.quantrix.com/en/ and http://www.ankhor.com/. Spreadsheet abstraction could be library DSL shipped with the language.

Also LINQ / SQL like queries would be a worthy consideration.  This is more familiar the map, filter, zip like constructs to average programmer due to widespread use of SQL. http://flink.apache.org/, https://slamdata.com/, http://quasar-analytics.org/, etc.

Lessons from recent languages. Though Pure Script and Elm are specialist languages they succeeded though there are Haskell to JS. So best is try to appeal to modern problems while having a great range of skill sets being also to use it. Haskell on the JVM is a great selling point but this is negated by Only Plain Old Haskell on the JVM as there are existing investments in libraries and languages in many organisations. Follow the lead by: https://github.com/graalvm, Eclipse OMR. Selling point of the new language will be:
- address pressing current IT issues
- familiarity
- simplicity
- speed and predictability of runtime for real time system and generally throughput and memory usage for more broader scope
- marketing

To summarise the proposed game plan is to deliver GHC 7.10.3 initially while building ETA as a language such that any version of Haskell and Java can transpired into with ability to work with syntax of other languages ASTs and IR/ILs of other languages while making this language both functional and imperative language friendly. This is to be done through layed language design with a simple core upon which you build but small enough to easily test and debug for maintainers while easy to extend and model other languages by language designers and / or use it for its own merit to address today's main IT application by other. Also should have the feel of C like Nemerle but also with the power of Haskell, Idris, F*, OCaml, PureScript, Elm, Scala, Fortress, X10.

Some collection of references which might be relevant: https://github.com/EECOLOR/programming-language. Also: https://github.com/atnos-org/eff-cats, https://github.com/slamdata/matryoshka, https://github.com/typelevel/algebra, http://quasar-analytics.org/, http://flix.github.io/, http://www.shenlanguage.org/, http://www.cs.utexas.edu/users/moore/acl2/, http://www.ats-lang.org/, https://github.com/lihaoyi/scala.rx, https://secure-compilation.github.io/, http://whiley.org/, https://github.com/lexi-lambda/rascal, http://www.ccs.neu.edu/home/stchang/pubs/ckg-popl2017.pdf, https://lexi-lambda.github.io/, http://impredicative.com/ur/

Also some of the links may disappear. If it interests you perhaps with might be worthwhile to convert them into PDF and save on one research and references repo.

@rahulmutt Your thoughts?

**Comment by sirinath** [comment]
Incorporated some updates.

**Comment by psibi** [comment]
> 1st starting point perhaps would be a low level intermediate language based on S and M expressions. This can be even have a SSA layer. Good starting point to get inspiration Web Assembly and WebKit B3.

Can you probably create a PR for that ? I'm interested to see what comes out of this.

**Comment by sirinath** [comment]
My interest is to be a user of the language and at least something that makes me more productive than the languages available now. At the moment I have my hands full with other work.

**Comment by sirinath** [comment]
Following might be a interesting read: https://lexi-lambda.github.io/blog/2016/10/03/using-types-to-unit-test-in-haskell/. I just updated the above with a few more links and references.

**Comment by cartazio** [comment]
As an industrial haskell user and occasional pl oriented computer scientist I'm  bummed that this will diverge from being a Haskell 2010/ ghc compiler targeting jvm.

**Comment by sirinath** [comment]
I am proposing to have a framework which can actually support even multiple versions of Haskell than 1 version by virtualizing  the syntax with a lower layer but being able to mimic different version of the language and have many more targets than the JVM. In addition any one can use the lower layer as a language on its own and virtualize syntax of other languages without FFI.

**Comment by cartazio** [comment]
That's called ghc core. It already exists.

**Comment by sirinath** [comment]
Can you use Syntax of another language without FFI embedded like in [inline-java ](https://github.com/tweag/inline-java/) and optimisation beyond language bountries. Can you support files from different version of Haskell in the same same project in the presence of breaking changes. Can you support an existing code base written in another language without FFI. Can you reuse parts of the project for other DSLs and [grow the type system](http://www.ccs.neu.edu/home/stchang/pubs/ckg-popl2017.pdf).

**Comment by rahulmutt** [comment]
Closing as this is a language change, this should follow the Eta Proposal Process:

https://github.com/typelead/eta-proposals
