### ISSUE TITLE
ApplicativeDo

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#120]

**Comment by DemiMarie** [comment]
Can this just be cherry-picked from GHC upstream?

**Comment by rahulmutt** [comment]
@DemiMarie Yes of course. I think this extension is fairly isolated. But the goal is no major frontend changes until tests/benchmarks are setup (should be up within the coming weeks).

**Comment by rahulmutt** [comment]
Closing as this is a language change, this should follow the Eta Proposal Process:

https://github.com/typelead/eta-proposals

**Comment by rahulmutt** [comment]
Re-opening to track that we want to backport. @jneira

**Comment by jneira** [comment]
The base ghc commit to backport wold be https://github.com/ghc/ghc/commit/8ecf6d8f7dfee9e5b1844cd196f83f00f3b6b879 ?

**Comment by rahulmutt** [comment]
I would recommend you start with the current `master` because it will include bug fixes/updates.

**Comment by Jyothsnasrinivas** [comment]
Backported ApplicativeDo in f6ebc0ae3058016379131b086c0ee5f0cf01412a
