### ISSUE TITLE
Failed to install time-1.7

### ISSUE THREAD

**Issue by sergey-scherbina** [typelead/eta#127]
<pre>
Preprocessing library time-1.7...
[ 1 of 26] Compiling Data.Time.Clock.CTimespec ( dist/build/Data/Time/Clock/CTimespec.hs, dist/build/Data/Time/Clock/CTimespec.jar )
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.1):
	tcCheckFIType: Unsupported calling convention.
  ccall unsafe "static time.h clock_gettime"

Please report this as a Eta bug: http://github.org/typelead/eta/issues

Failed to install time-1.7

~ $ cat ~/.epm/logs/time-1.7.log
~ $ stat -f%z ~/.epm/logs/time-1.7.log
0
~ $ uname -v
Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu3789.21.3~60/RELEASE_X86_64
~ $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
~ $ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
~ $ stack --version
Version 1.2.0 x86_64 hpack-0.14.0
~ $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
</pre>

**Comment by psibi** [comment]
Eta right now supports time package whose version is `1.6.0.1`. To install that specific version - you can use:

```
epm install time-1.6.0.1
```

To see which specific versions are supported - you can go over to the [eta-hackage](https://github.com/typelead/eta-hackage) repository and find out.

**Comment by psibi** [comment]
time-1.7 has been ported to Eta. You can do `epm update` to get the latest hackage patch set and then install `time-1.7`. I'm closing the issue, please re-open if you feel necessary to.

**Comment by sergey-scherbina** [comment]
thank you
