### ISSUE TITLE
Add OSX travis build for Eta

### ISSUE THREAD

**Issue by psibi** [typelead/eta#128]
I think I have a working version here: https://github.com/psibi/eta/blob/osx-travis/.travis.yml

But I need to test it before I send a PR. The time package is currently causing the build to break (because of the random package). I have sent a relevant PR in eta-hackage repository for that.

**Comment by rahulmutt** [comment]
I merged the PR - check now?

**Comment by psibi** [comment]
Travis for OSX doesn't seem to be as good as the Linux one. It timeouts the 50 minute before the entire thing get's completed even with the caching (Linux take around 30 minutes to do the entire stuff). As of now, I'm just planning to run till the `verify.sh` stage for OS X.

**Comment by rahulmutt** [comment]
For now, I'm closing this since the basic setup is done. We can file more issues for improving the build times.
