### ISSUE TITLE
External Interpreter & Template Haskell support

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#130]
So the sequence of implementation steps for getting an interpreter + TemplateHaskell support (which follows almost directly):

~~1. Port `process` and `directory` packages. This requires mapping low-level OS C APIs to Java APIs. @psibi is currently looking into it, but others are welcome to help him to speed up the process.~~

2. Make `iserv` work. `iserv` is the interpreter process that takes in bytecode as input and interprets it as output. See [here](https://github.com/ghc/ghc/tree/master/iserv). If all the dependencies were implemented in a semantics-preserving fashion, this step should require almost no effort.

3. The bytecode interpreter should be written in the RTS. Essentially, [this](https://github.com/ghc/ghc/blob/e0ca7ff3a9df3f746f0496ae274d669fc14a17dc/rts/Interpreter.c) has to be ported from C to Java.  I've done a minor start [here](https://github.com/typelead/eta/tree/master/rts/src/eta/runtime/interpreter).

4. The [ghci](https://github.com/ghc/ghc/tree/master/libraries/ghci) library from GHC 8 should be ported. 

5. Port the modern Template Haskell implementation in GHC 8 while making sure the type system changes don't leak in. This means a focus on those `*Splice` modules in the GHC 8 codebase and changing the imports to match Eta's module namespacing.

6. Turn on the `GHCI` macro when compiling `eta` by adding the `-DGHCI` option to the `eta.cabal` file. This will automatically enable the Template Haskell implementation.

**Comment by codygman** [comment]
I may be able to help port the directory package, but what is it used for in the template haskell implementation?

**Comment by rahulmutt** [comment]
It's not actually, I misread the dependencies of `iserv`. I edited the description to reflect the mistake. 

As for the directory package, I've already started the port and it's very close to being done. 

The main thing that needs to be done now is the core design of interpretation. GHC uses runtime linking to facilitate interpretation and I think you can map that to Java class loading. 

If you're interesting in helping implement the interpreter bit, we can discuss on Gitter.

**Comment by psibi** [comment]
For anyone planning to contribute/collaborate on interpreter for Eta - this is the PR/branch I'm working on it: https://github.com/typelead/eta/pull/162

**Comment by rahulmutt** [comment]
Successfully completed and working in Eta v0.8.0b1. Docs/release coming soon.
