### ISSUE TITLE
New syntax for Java wrappers

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#140]
Currently, to wrap a Java object (a feature that's used throughout the FFI to keep Eta's polymorphism), the syntax is:

```haskell
data {-# CLASS "java.util.LinkedList" #-} LinkedList a = MkLinkedList (Object# (LinkedList a))
```
There are currently two proposals for the new syntax:

1. This is the Haskell-y solution that's nice on the eyes.

```haskell
data LinkedList a = MkLinkedList (@java.util.LinkedList a)
```

2. We lose the Haskell-iness in exchange for a bit of clarity that the `a` Eta type variable corresponds to the `a` generic type parameter.

```haskell
data LinkedList a = MkLinkedList (@java.util.LinkedList<a>)
```

Comments/feedback? Other syntax proposals are welcome as well.

**Comment by ExcaliburZero** [comment]
Both of those syntax proposals are much better than the current version.

I think the second one is a bit better, as it makes it clearer that it is dealing with the Java class `java.util.LinkedList<a>`.

**Comment by mitchellwrosen** [comment]
I prefer the second as well, because the first looks like `a` is a field in the `LinkedList` constructor.

**Comment by koerriav** [comment]
the second is better

**Comment by mitchellwrosen** [comment]
Both are a bit confusing, however, because they don't give a name for the data constructor. Wouldn't it be something like

```haskell
data LinkedList a = MkLinkedList (@java.util.LinkedList a)
```
or
```
type LinkedList a = @java.util.LinkedList a
```
instead?

**Comment by rahulmutt** [comment]
@mitchellwrosen Thanks for the catch! I'll edit the original post.

**Comment by mitchellwrosen** [comment]
Ah, in that case I much prefer the first!

**Comment by alexander-at-github** [comment]
From `@java.util.LinkedList` we already know that we are dealing with a java object. When we add the type variable `a` to `(@java.util.LinkedList a)` what else could it be than a generic type variable to the java class? I do not think that we gain anything by proposal number two. I.e., I much prefer proposal number one.

**Comment by rahulmutt** [comment]
Fair enough :) The majority wants (1) and it also it slightly easier on the parser side to implement, so we'll go with that! If anyone is interesting in taking a stab at this, I'd be happy to guide them through the required steps.

**Comment by alexander-at-github** [comment]
I could give it a try, if you do not mind that I will only start working on it in about two weeks. (I am very busy in the moment).

**Comment by rahulmutt** [comment]
Yeah no problem! It would be best if you can ping on the typelead/eta channel on Gitter once you're ready.

**Comment by mitchellwrosen** [comment]
If @alexander-at-github drops the ball I'd be happy to pick it up =)

**Comment by codygman** [comment]
I also prefer one as it's more concise without compromising readability/meaning.

**Comment by alexander-at-github** [comment]
@mitchellwrosen: In case I step back, I will let you know.

**Comment by rahulmutt** [comment]
Relevant files to take a look at:

compiler/ETA/Parser/Lexer.x - Define a new token type for java identifiers (@[java-identifier]). Make a rule to recognise this token under special conditions (when parsing the types in a data decl).
compiler/ETA/Parser/Parser.y - Add the token you defined above. Add a special rule for parsing data decls. When you parse it, you should change it around to the transformation above. This made require some major changes to how data decls are parsed (like more values returned by the parser monadic context).

**Comment by alexander-at-github** [comment]
Hey @rahulmutt, I had an accident about two weeks ago and I have been offline cause of that. I will not be able to implement the issue any time soon. Sorry, for that!
@mitchellwrosen: please feel free to adopt the issue.

**Comment by mitchellwrosen** [comment]
Sure, I can take it over. @rahulmutt would you mind assigning me, if no one else is working on this yet?

**Comment by rahulmutt** [comment]
@alexander-at-github No worries, get well soon!

@mitchellwrosen Sure, you can go ahead.

**Comment by rahulmutt** [comment]
@mitchellwrosen Status? I can give more hints as required.

**Comment by mitchellwrosen** [comment]
Status is I'm still working thru an alex/happy tutorial. Sure, if you have any hints in mind please dump them here - I was going to hop into gitter when I get back to it.

**Comment by rahulmutt** [comment]
Ok cool, just wanted to know if you needed anything form my side. Sure, come on Gitter when you start hacking.
