### ISSUE TITLE
eta-lang.org front page example typo

### ISSUE THREAD

**Issue by the9000** [typelead/eta#159]
Under the "Concurrency and parallelism", the example reads:

    transact amount sender receiever = do
      senderBalance <- readTVar sender
      receiverBalance <- readTVar sender

The latter should be `readTVar receiver`, I suppose.

(Sorry for posting it here; I can't find the repo that represents the site itself.)

**Comment by rahulmutt** [comment]
Thanks! I already fixed it. The update should be deployed in a couple minutes. I'll close this as soon as it's deployed.

**Comment by rahulmutt** [comment]
Fixed
