### ISSUE TITLE
[eta-playground]: Bug - integer-0.5.1.0 Package Not Found

### ISSUE THREAD

**Issue by Hartshorn** [typelead/eta#160]
When in the Eta Playground, choosing the integer-0.5.1.0 package from the list on the right side links to -
[https://hackage.haskell.org/package/integer-0.5.1.0](url)
returns a Package Not Found error.

**Comment by rahulmutt** [comment]
Thanks for the report! This is expected since the actual location should be https://hackage.haskell.org/package/integer-gmp-0.5.1.0. The links are currently automatically generated, so I'll need to add an override mechanism for this particular package.

**Comment by rahulmutt** [comment]
Eta Playground no longer exists (just the Tour now) so this is not relevant anymore.
