### ISSUE TITLE
[eta-playground]: Example ordering

### ISSUE THREAD

**Issue by ExcaliburZero** [typelead/eta#161]
Currently in the Eta Playground the examples are listed in the following order:

* Lens Example
* Hello World!
* Java Generics

It would make more sense to have them ordered by difficulty level:

* Hello World!
* Java Generics
* Lens Example

> rahulmutt: The ordering of those examples is non-deterministic (it uses getDirectoryContents). I think adding a number parameter to the examples for ordering purposes would be useful - can you file an issue?

**Comment by rahulmutt** [comment]
Eta Playground no longer exists (just the Tour now) so this is not relevant anymore.
