### ISSUE TITLE
Implement JArray instances for primitive arrays

### ISSUE THREAD

**Issue by noughtmare** [typelead/eta#165]
The [Java Classes & Arrays](http://eta-lang.org/docs/html/getting-started.html#java-classes-arrays) section doesn't mention arrays.

**Comment by rahulmutt** [comment]
My bad, I completely forgot to document them! For now, you can see [this](https://github.com/typelead/eta/blob/master/libraries/base/Java/Array.hs) for the basic API. `JByteArray` to give a direct answer to your question.

**Comment by noughtmare** [comment]
Is there a function like `fromList :: [Word8] -> Java a JByteArray`?

**Comment by rahulmutt** [comment]
Not yet, I'll get around to implementing it, we'll make this the issue to track it. In the meantime, I can present a workaround if you can give me a basic idea of what you're trying to do?

**Comment by noughtmare** [comment]
I was just playing around with java functions that take byte[]'s as input. Specifically `java.util.zip.Adler32.update`.

**Comment by rahulmutt** [comment]
See [this](http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html) for all the supported character escapes.

**Comment by AlexeyRaga** [comment]
I am getting an error for running this example though:
```
example/Main.hs:54:17:
    Couldn't match kind ‘*’ with ‘#’
    When matching types
      r0 :: *
      Object# JByteArray :: #
    In the expression: JByteArray $ getBytesUtf8# js
    In an equation for ‘stringBytes’:
        stringBytes s
          = JByteArray $ getBytesUtf8# js
          where
              !(JS# js) = toJString s
```

**Comment by rahulmutt** [comment]
@AlexeyRaga I updated the example above to fix it. Basically, you can't use `$` for primitive types (of kind '#').

**Comment by rahulmutt** [comment]
Btw I'm working on closing this issue today.
