### ISSUE TITLE
speed up / stabilize the installation process on mac

### ISSUE THREAD

**Issue by Dierk** [typelead/eta#175]
atm the installation process is unstable wrt already installed / not installed GHC versions, cpp compiler versions, and stack. (see discussion in gitter)

**Comment by rahulmutt** [comment]
I think we might end up just uploading the binaries `eta`, `epm`, and `eta-build` to some location and have the tap download them instead and do some post-installation steps to build the base libraries.

**Comment by rahulmutt** [comment]
Closing this as we'll eventually have binary builds and installation will become smoother.
