### ISSUE TITLE
can`t find the --enable-uberjar-mode flag

### ISSUE THREAD

**Issue by misha913loki** [typelead/eta#186]
Sorry to take your time.When I read about Eta Programming Language v0.0.5  Docs » Getting Started with Eta  » Setting Up The Project, I'm stuck in some problem.

when I use Main.hs just like the example says:

	{-# LANGUAGE MagicHash #-}

	import Java

	data {-# CLASS "eta.example.MyExportedClass" #-} MyExportedClass
	  = MyExportedClass (Object# MyExportedClass)

	fib' 0 = 1
	fib' 1 = 1
	fib' n = fib' (n - 1) + fib' (n - 2)

	fib :: Int -> Java MyExportedClass Int
	fib n = return $ fib' n

	foreign export fib :: Java MyExportedClass Int

	main :: IO ()
	main = return ()`
Run the command`$ epm run` then I got the error:
	
	Preprocessing executable 'y' for y-0.1.0.0...
	[1 of 2] Compiling Main             ( src/Main.hs, dist/build/y/y-tmp/Main.jar )

	src/Main.hs:21:16: parse error on input ‘fib’`

I modified the Main.hs code:

	foreign export java fib :: Int -> Java MyExportedClass Int

then I got `y.jar` (oh my .cabal named y.cabal).

so I want to know if the doc has some errors or I made some mistakes.

by the way,I try `epm configure --enable-uberjar-mode`,but got:
	
	epm: unrecognized 'configure' option `--enable-uberjar-mode'`
I called `epm configure --help` but still can't find out the`enable-uberjar-mode` flags.

**Comment by rahulmutt** [comment]
The doc had some error - just fixed it thanks!

`--enable-uberjar-mode` is showing up for me - when did you install? That flag was added just a couple days ago. Did you correctly update using `update.sh`?

**Comment by misha913loki** [comment]
Thank u ! It works! The new uberjar has been successfully run on my java side!
