### ISSUE TITLE
Generate line number information in class files

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#189]
In stack traces, any code generated by Eta has `(Unkown Source)` listed as the line number since Eta doesn't generate any info right now. The information is available at the STG level via `StgTick`. This information should be used to generate the appropriate class file attributes that can be used to make debugging a whole lot easier.

**Comment by rahulmutt** [comment]
I've outlined the steps to get this implemented below. This is what I feel is the most immediate approach to getting this feature in. There may be alternatives that you can choose to pursue based on your style of programming.

1. Add functionality in `codec-jvm` for generating the [LineNumberAttribute](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.12) attribute.
  a. In `Codec.JVM.Attr`, a new constructor for the `Attr` type should be added, probably something along the lines of `ALineNumber [(Offset, LineNumber)]` where `LineNumber` can be a `newtype` or a `type` synonym.
  b. Update `attrName` to handle the new case.
  c. Update `putAttrBody` to handle the new case.

2. Add functionality in `codec-jvm` for generating the [SourceFileAttribute](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.10) attribute.
  a. In `Codec.JVM.Attr`, a new constructor for the `Attr` type should be added, probably something along the lines of `ASourceFile Text`.
  b. Update `attrName` to handle the new case.
  c. Update `putAttrBody` to handle the new case.
  d. Update `unpackAttr` to handle the new case. 
        i. This is required since `SourceFile` references a constant in the constant pool for the name. 

3. In `codec-jvm`, provide APIs to add attributes for methods.
  a. Update `Codec.JVM.ASM.MethodDef` to store attributes.
  b. Update `Codec.JVM.ASM.mkMethodDef` to handle the change in (a).
  c. Add a new function `addAttrsToMethodDef` which will allow you to update an existing `MethodDef` and add new attributes to it.
  d. Update `Codec.JVM.Method.MethodInfo` to store attributes.
  e. Update `Codec.JVM.ASM.mkClassFile` to convert between `MethodDef` and `MethodInfo` properly handling the new attributes-storing fields in each type.

4. In `Codec.JVM.ASM.Code.Instr`, add the facility to record line number info.
  a. Augment `InstrState` with a field for storing line number information.
  b. Add a new function `getBCSL` that is similar to `getBCS` which returns the line number information from (a).
  c. Similarly, add a new function `instrBCSL` that uses the new function in (b).

6. In `Codec.JVM.Attr`, handle custom attributes in the binary serialization functions.
  a. In `toAttrs`, use the new function from 4 (c) and make sure that the `LineNumberAttribute` attribute is placed in the list of attributes to generate *for the method*, not *for the Code attribute*.

7. In `Codec.JVM.ASM.Code`, add combinators for modifying the state of the `Instr` monad.
  a. Define `emitLineInfo :: LineNumber -> Code`.

8. Familiarize yourself with the data types involved in this feature.
  a. The basic abstract syntax tree (AST) for STG code in `ETA.StgSyn.StgSyn` defined via the `GenStgExpr` data type, with special attention to `StgTick`.
  b. The `Tickish` type defined in `ETA.Core.CoreSyn`, with special attention to `SourceNote`.
  c. The `RealSrcSpan` data type in `ETA.BasicTypes.SrcLoc`.
  
9. Update the `CodeGen` monad in `ETA.CodeGen.Monad` to store relevant information needed for generating the attributes above.
  a. The information for the `SourceFile` can be obtained from the `ETA.BasicTypes.Module.Module` datatype which can be retrieved from the `ETA.Main.DynFlags.DynFlags` data type.
  b. Update `withMethod` to modify the `methodDef` before returning by reading the `CgEnv` or `CgState` and generating attribute information from it.
    i. Make sure to add on the `SourceFile` attribute using the function from 3 (c).
   ii. The module remains constant for a single invocation of the code generator so the `SourceFile` information will remain the same across calls to `withMethod`.

10. Deal with the `StgTick` case in `ETA.CodeGen.Expr.cgExpr`.
  a. Get a feel for how `StgTick` is generated by sending the `-g -ddump-stg -ddump-cg-trace -ddump-to-file` flag to the `eta` compiler (which turns on creating `StgTick`s for `SourceNote`s). Can be done with an `etlas` project by adding `eta-options: -g -ddump-stg -ddump-cg-trace -ddump-to-file`.
     i. Inspect the generated `*.dump-stg` and `*.dump-cg-trace` files and look for the `StgTick` debug outputs to see how and when they're generating. Compare with the original source file.
    ii. Determine whether `-g` should be turned on by default.
  b. Process the `Tickish` component and only deal with the `SourceNote` case which provides information.
     i. The `RealSrcSpan` you can extract from a `SourceNote` should give you a line number which you can add to the line number info using `emit $ emitLineInfo ...`.

**Comment by puffnfresh** [comment]
@rahulmutt I think that needs to be LineNumberTable attribute, instead of LineNumber attribute.

**Comment by rahulmutt** [comment]
@puffnfresh Updated, thanks!

**Comment by ywata** [comment]
Hi. I'll try to implement this feature based on the description above.

**Comment by rahulmutt** [comment]
Just wanted to point out that @Abhiroop and I implemented #3 in the outline above just yesterday in the process of implementing #298.

**Comment by rahulmutt** [comment]
@ywata #298 is now merged into master and the required updates have been pushed to codec-jvm. Feel free to update your progress on this issue and let us know about anything that's blocking you.

**Comment by jneira** [comment]
@ywata @rahulmutt hi, i am trying to implement this one. I already have a inittial implementation of 1 and 2

**Comment by rahulmutt** [comment]
@jneira Great start! I think 3 should already be implemented so you can proceed to 4 and beyond.

**Comment by jneira** [comment]
I have pushed what I have been able to do so far: https://github.com/jneira/codec-jvm/commit/0c236aea36814e8e4f80442e647f4a654643f3ad
I will not be able to continue it until after a few weeks

**Comment by rahulmutt** [comment]
Awesome! Feel free to submit a PR to `codec-jvm`.

**Comment by rahulmutt** [comment]
@jneira Will you be tackling the rest of this as well?

**Comment by jneira** [comment]
Hi @rahulmutt, sure i'll try to do it. BTW i have to do steps 5 and 6 fot finishing the codec-jvm part, started with this [pr](https://github.com/rahulmutt/codec-jvm/pull/10)

**Comment by rahulmutt** [comment]
Sure send another PR for that.

**Comment by jneira** [comment]
Hi @rahulmutt, i think the LineNumberAttribute shoud be generated for the Code Attribute. I tested to compile a java class with javac and with javap -v the LineNumberTable seems to be under Code and no under Method definition
Moreover, the [spec ](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.6) states:
> The attributes defined by this specification as appearing in the attributes table of a method_info structure are the Code (§4.7.3), Exceptions (§4.7.5), Synthetic (§4.7.8), Signature (§4.7.9), Deprecated (§4.7.15), RuntimeVisibleAnnotations (§4.7.16), RuntimeInvisibleAnnotations (§4.7.17), RuntimeVisibleParameterAnnotations (§4.7.18), RuntimeInvisibleParameterAnnotations (§4.7.19), and AnnotationDefault (§4.7.20) attributes. 

and

> The only attributes defined by this specification as appearing in the attributes table of a Code attribute are the LineNumberTable (§4.7.12), LocalVariableTable (§4.7.13), LocalVariableTypeTable (§4.7.14), and StackMapTable (§4.7.4) attributes.

So unless you tell me otherwise i'll try to do it in this way

**Comment by rahulmutt** [comment]
@jneira Apologise for that, you're right. Go ahead.

**Comment by jneira** [comment]
nvm, it could not been done (by me) it in a reasonable time without your detailed guide lines
now i'll try to do the really hard part in eta

**Comment by rahulmutt** [comment]
It's not as hard as you think :) You're very close actually.

So as you debug, I strongly encourage you to run the `./tests/verify/verify.sh` script after you do `./cleaninstall.sh` with your changes. It will let you now whether the generated classfile is valid.

I took a look at this last week some time, here are some observations that might help:
Doing `-g -ddump-stg -ddump-cg-trace -ddump-to-file` in `ghc-options:` in the `base.cabal` file can give you some examples to look at. The files will be in `dist/build/*`. I'm taking a look at `GHC/List.dump-cg-trace`, I find this:

```
creating new closure...sat_sNKN
StgTick src<GHC/List.hs:986:38-56>
StgTick src<GHC/List.hs:986:47>
StgTick src<GHC/List.hs:986:52-53>
StgTick src<GHC/List.hs:986:55-56>
StgApp zipWith3 [z_sNK9, as_sNKF, bs_sNKI, cs_sNKL]
```
Notice that before any code is even reached in the STG AST, you encounter 4 consecutive StgTicks, all with different line number information. Those ticks give you information about the original functions *before inlining* which is useful for even better debugging information later, but for now you need to make a decision on *which* of those line numbers to choose. The first entry will be the outer most call and the last entry will be the innermost call. It'll probably help you to open up `GHC.List` source file and really follow the sequence above and you'll find out which line number will be the most relevant to the user upon an exception or space leak. 

As far as I see it, you main work will be:
1) Extending the state in `ETA.CodeGen.Monad` to include some data structure to track consecutive StgTicks.
2) Extending the StgTick case in `cgExpr` to use the state in (1) to collect all consecutive StgTicks and just after the last consecutive tick, emit the line number into the bytecode - checkout the `emit` function in the `CodeGen` monad.

Hope this helps! You're almost there.

**Comment by jneira** [comment]
I complete the changes in codec-jvm with a method to add attributes when making a ClassFile, so we can add the sourceFile attribute in eta Codegen monad
https://github.com/rahulmutt/codec-jvm/pull/13

**Comment by jneira** [comment]
Maybe we could close this one, taking in account #494

**Comment by rahulmutt** [comment]
Yes, we can - thanks for the reminder!
