### ISSUE TITLE
Port tf-random & QuickCheck

### ISSUE THREAD

**Issue by polux** [typelead/eta#190]
QuickCheck depends on tf-random which fails to install because:

~~~
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.5):
	tcCheckFIType: Unsupported calling convention.
  ccall unsafe "static skein.h Threefish_256_Process_Block"
~~~

quite a few libraries depend on QuickCheck which makes them in turn unusable.

**Comment by rahulmutt** [comment]
`tf-random` has a single C FFI import that needs to be shimmed with a Java import. 

Btw, which libraries do you need that are unusable?

**Comment by polux** [comment]
I stumbled upon it by trying to depend on megaparsec.

**Comment by rahulmutt** [comment]
Sure. Will let you know once this issue is resolved.

**Comment by polux** [comment]
Aweome, thanks! I'm really excited about eta.

**Comment by psibi** [comment]
Had a look at both the C code and the relevant java libraries for tf-random. 

The code for java can be likely adapted from here: https://github.com/bmalkow/java-bc-threefish/blob/7e70464d70489869209a73ab9d5a9688d6e7cf3c/src/org/bouncycastle/crypto/engines/ThreefishEngine.java#L232

**Comment by rahulmutt** [comment]
@psibi Finished this. It should now be working.

**Comment by polux** [comment]
Great, thanks a ton!
