### ISSUE TITLE
Some inconsistency in eta-lang docs

### ISSUE THREAD

**Issue by psibi** [typelead/eta#195]
* http://eta-lang.org/docs/html/getting-started.html#deriving-standard-typeclass-instances

There is a sentence there like this: `To find out more about the Class typeclass, see here.`. I think the `see here` word is missing a hyperlink.

* http://eta-lang.org/docs/html/getting-started.html#java-classes-arrays

While the heading is "Java Classes & Arrays", it doesn't seem to explain about arrays.

**Comment by rahulmutt** [comment]
Thanks for the catch! Array support is still a bit incomplete. It supports object arrays but not primitive arrays yet. Once that's done I'll add the docs for arrays as well.
