### ISSUE TITLE
Possible bug in resolving overloaded java constructors

### ISSUE THREAD

**Issue by AlexeyRaga** [typelead/eta#196]
In my FFI bindings I am trying to import an object with multiple constructors:

```
public final class ProducerRecord<K, V> {
   public ProducerRecord(String topic, Integer partition, Long timestamp, K key, V value) { ... }
   public ProducerRecord(String topic, Integer partition, K key, V value) { ... }
   public ProducerRecord(String topic, K key, V value) { ... }
   public ProducerRecord(String topic, V value) { ... }

   ...
}
```

My import statement looks like:

```
data {-# CLASS "org.apache.kafka.clients.producer.ProducerRecord" #-} JProducerRecord k v =
  JProducerRecord (Object# (JProducerRecord k v))
  deriving (Class, Show)

foreign import java unsafe "@new" newJProducerRecord ::
  (Extends k Object, Extends v Object) => JString -> Int -> Int64 -> k -> v -> JProducerRecord k v
```
I am trying to import the constructor with 5 parameters. 
The `ProducerRecord` object is immutable so I don't bother wrapping it with `Java` monad (although doing it doesn't make any difference).

Calling `newJProducerRecord` results in the following exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.kafka.clients.producer.ProducerRecord.<init>(Ljava/lang/String;IJLjava/lang/Object;Ljava/lang/Object;)V
	at main.Main$main7.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
	at base.ghc.io.handle.Text$zdwa8.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
...
```

It looks like the code actually tries to call `ProducerRecord` constructor that has 3 parameters, not 5 (if I understand it correctly)
```
ProducerRecord.<init>(Ljava/lang/String;IJLjava/lang/Object;Ljava/lang/Object;)V
```

**Comment by rahulmutt** [comment]
The tricky part here is that Integer and Long are classes and not primitives. So you must declare JWTs and use those for imports. In the future, we'll put the JWTs in the Java module.

**Comment by AlexeyRaga** [comment]
Ah, I see. Do I also need explicit conversion `Int` -> `JInteger` and `Int64` -> `JLong`?
How to do it correctly?

**Comment by rahulmutt** [comment]
JInteger and JLong both have constructors that accept int and long respectively (see reference for java.lang.Integer and java.lang.Long). You can use those constructors for coversion. You can avoid the Java monad in the return type because the conversion is pure.

**Comment by AlexeyRaga** [comment]
Thanks, your answers helped, as usual.
