### ISSUE TITLE
Support Proxy a in FFI imports

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#201]
In cases where you make heavy use of generics, you need something to determine a type parameter. 

Take for example:

```haskell
foreign import java unsafe "@interface addAll" addAll ::
  (Extends a Object, Extends b (Collection a)) => b -> Java b Bool
```
(from https://gist.github.com/amir/0782874fb5bfe40fddc56a7e37735877#file-mycollections-hs-L40)

Note that when you use `addAll a` for some `a` that only determines the type of `b` but there's nothing to determine the type of `a` causing the `Extends'` type family to get stuck with a compilation error (see the Gist above). The goal is to support something like:
```haskell
foreign import java unsafe "@interface addAll" addAll ::
  (Extends a Object, Extends b (Collection a)) => Proxy a -> b -> Java b Bool
```
So that the user can specify `addAll (Proxy :: Proxy a) a1` to determine the `a` type variable. Note that the `Proxy a` type has no runtime representation and contributes nothing to determine the Java method signature of the imported method.

**Comment by Jyothsnasrinivas** [comment]
Closing this because implementing Type Applications will solve this. Updates on Type Applications are tracked on #799
