### ISSUE TITLE
Lazy initialization of Eta modules

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#202]
As shown in #200, strict class loading can wreak havoc on startup times. We should find a way to lazily initialize the closures in an Eta module. Most likely, the solution will involve reflection since that's the only way we can refer to a class without the JVM loading it.

**Comment by puffnfresh** [comment]
Can we instead do less work (e.g. NOT initialise closures) in class initialisers?

**Comment by rahulmutt** [comment]
We could wrap all the static initialisations in StgIndStatic's, but it would become pretty complicated since we have to manage dependencies as well.

Or, we can wait until we convert all the virtual methods to static methods when we start optimising the codegen. I think that should reduce class loading quite a bit.

**Comment by rahulmutt** [comment]
So one way to reduce this overhead that I thought of today as I was looking at a trace:

```haskell
module Some.Module where

someFun = ...
```

```java
package some;

import eta.runtime.stg.StgClosure;
import eta.runtime.stg.StgFun;

public Module {
   public static StgClosure someFun = new Module.someFun();

   public static class someFun extends StgFun {

      public void enter(StgContext context) {
          ...
      }
   } 
}
```

This can get transformed to:
```java
package some;

import eta.runtime.stg.StgClosure;
import eta.runtime.stg.StgFun;

public Module {
   private static StgClosure someFun;

   public static StgClosure get_someFun() {
      if (someFun == null) {
          // We should synchronise this to make it thread-safe
          // Best to make this lightweight using atomic cas operations.
          someFun = new Module.someFun();
      }
      return someFun;
   }

   public static class someFun extends StgFun {

      public void enter(StgContext context) {
          ...
      }
   } 
}
```

And moreover, in the code generator, when referencing the `someFun` closure, we should call the static method instead of referencing the static field (which should involve changing just a couple lines given the abstraction we have in place). The advantage here is that there will be no class loading overhead, but there will be a slight extra overhead upon usage of a function closure for the first time but the JIT should be able to optimise it pretty well given that it's a one-shot mutation and eventually be able to inline the static method calls to a field reference (the situation we have now).

When are function closures used? Currently, all the time, but it can be optimised so that we put the entry code into a separate static method (which will improve performance by several fold) and only use the closure when passing the function as an argument to a higher-order function. 

While I mentioned only function closures above, the same logic also applies to CAFs (constant applicative forms) which are essentially top-level thunks, and static values like instances like type class instances and constant lists.

Pros:
1. This will eliminate pretty much all the class loading overhead, improving startup times significantly.
2. ProGuard will be able to do dead-code elimination a lot more effectively. In the current state, ProGuard will treat the usage of any class in the static initialiser as a hard dependency for the class and will not optimise, say instances of unused typeclasses! In cases like `aeson` where there are a huge number of instances that you may never use, this is a serious problem.
3. The form of the proposed static wrapper methods is an extremely common pattern in Java code (essentially the singleton pattern), so we can hope that the JIT will optimise this well.
4. This will reduce the amount of garbage that is generated. Lots of unused objects were getting instantiated at class load time.
Cons:
1. This will generate a lot more bytecode increasing the unoptimized jar sizes by at least a couple MB (after compression with Deflate) and maybe 30-40% increase at worst. But this will most likely not matter in the presence of point 2 above.
