### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by mchav** [typelead/eta#205]
I'd like to start giving ETA on Android a crack.  A few questions though:

1) How do I override methods
2) how can I make a module extend/inherit from another class.

**Comment by rahulmutt** [comment]
Here's the documentation on exporting: http://eta-lang.org/docs/html/getting-started.html#exporting-eta-methods

What I didn't mention was how to extend/implement, which is shown below:

```Haskell
data {-# CLASS "eta.example.MyActivity extends android.app.Activity" #-} MyActivity
  = MyActivity (Object# MyActivity)

onCreateFn :: Bundle -> Java MyActivity ()
onCreateFn savedInstanceState = io $ print "Hello World!"

foreign export java "onCreate" onCreateFn :: Bundle -> Java MyActivity ()
```

Overriding has no special syntax - just specify in the export string the name of the method you want to declare. If it happens to be a method from a parent class, it will override.

It's a bit clunky right now, and we'll have better syntax in the future. Also, you'll have to import quite a bit of Android types to get going, something we can make better with an import generator in the future.

**Comment by rahulmutt** [comment]
Closing, as the main question was resolved.
