### ISSUE TITLE
base-4.8.2.0 failed during the building phase

### ISSUE THREAD

**Issue by juanmanuel-calderon** [typelead/eta#208]
Hello,

I'm trying to install eta in ArchLinux, but when running install.sh I'm getting:

 Configuring base-4.8.2.0...
epm (for install)
Resolving dependencies...
Configuring base-4.8.2.0...
Building base-4.8.2.0...
Preprocessing library base-4.8.2.0...
./Data/Bifunctor.hs: hGetContents: invalid argument (invalid byte sequence)
Failed to install base-4.8.2.0
epm: Error: some packages failed to install:
base-4.8.2.0 failed during the building phase. The exception was:
ExitFailure 1
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: epm install --solver=topdown
Current directory: path.to.eta/eta/libraries/base
Exit code: 1
Stderr:
./Data/Bifunctor.hs: hGetContents: invalid argument (invalid byte sequence)
epm: Error: some packages failed to install:
base-4.8.2.0 failed during the building phase. The exception was:
ExitFailure 1
)

For information:
$ java -version 
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)

$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0

Thanks

**Comment by rahulmutt** [comment]
Can you go `libraries/base` and run this command:

`epm install --solver=topdown -v3`

and share the output?

**Comment by juanmanuel-calderon** [comment]
Here it is.
One detail I forgot to mention is that I am behind a proxy. If I run the command without _JAVA_OPTIONS set I have the same output.

[output.txt](https://github.com/typelead/eta/files/734747/output.txt)

**Comment by rahulmutt** [comment]
I'm not able to make out what might be causing this. Can you try running `./cleaninstall.sh` and show me the full log?

**Comment by juanmanuel-calderon** [comment]
Here: 
[output.txt](https://github.com/typelead/eta/files/739596/output.txt)

**Comment by rahulmutt** [comment]
In `libraries/base/base.cabal`, change

```
    ghc-options: -this-package-key base
```

to

```
    ghc-options: -this-package-key base -v3
```

and run `./cleaninstall.sh` and share the output.

**Comment by juanmanuel-calderon** [comment]
Here.

[output.txt](https://github.com/typelead/eta/files/741612/output.txt)

**Comment by juanmanuel-calderon** [comment]
Hello,
The problem was with the env variable LC_ALL=C. Doing an export LC_ALL=en_US.utf-8 made it work. Maybe in the tutorial it should be specified that uft8 is needed.

**Comment by rahulmutt** [comment]
Thanks for the hint! I'll add it to the docs and close this issue once that's done.
