### ISSUE TITLE
Haskell stackage/cabal coverage?

### ISSUE THREAD

**Issue by chadbrewbaker** [typelead/eta#216]
Has anyone made a CI to see what stackage/cabal packages are building under Eta?

I have a need to run SBV on the JVM. Trying to estimate if rewriting it in Java or fixing broken Eta dependencies would be quicker.

**Comment by rahulmutt** [comment]
The best we have is a manually maintained list here: 

https://github.com/typelead/eta-hackage#supported-packages

What is SBV? If you can give me a list of dependencies that you need, I can let you know how long it would take to get them ported if they aren't already.

**Comment by chadbrewbaker** [comment]
Thanks!

https://github.com/LeventErkok/sbv

**Comment by rahulmutt** [comment]
Wow that depends on `ghc`. Probably not something we'll be able to have anytime soon. The rest of the dependencies look OK.

**Comment by chadbrewbaker** [comment]
Very few lines of GHC dependency. Making the package play nice with Stack and setting the path.

**Comment by puffnfresh** [comment]
@chadbrewbaker Eta will automatically apply patches we put into https://github.com/typelead/eta-hackage - if we write a patch for sbv to get rid of the GHC stuff it should work well! :+1:

**Comment by rahulmutt** [comment]
Just pushed a patch for `sbv-6.1` on `eta-hackage` which should work with the new Eta v0.7 release. Feel free to file issues on `eta-hackage` if there any bugs at runtime.

It turns out that `sbv` doesn't really depend on `ghc` since removing the dependency didn't cause any build errors.
