### ISSUE TITLE
Java 8 lambda expressions

### ISSUE THREAD

**Issue by aktowns** [typelead/eta#219]
Hey!, I have a file with the following:

```java
import java.util.function.Function;

public class FFIExample {
  public void blah() {
    Function<Boolean, Boolean> f = (Boolean z) -> { return true; };
  }
}
```

which seems to cause a panic on compile

```
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.5):
	getConst: 18
````

Which appears to be caused by the lambda expression itself, am I hitting a constraint (should I be only using java7 features?)

**Comment by rahulmutt** [comment]
This is interesting. What's your project setup? I'm not sure what exactly you were trying to do.

**Comment by aktowns** [comment]
I've [thrown an example that replicates it on github here](https://github.com/aktowns/eta-ffi-nolambda) where i actually hit it, i'm playing with writing a wai host that runs on netty, part of it i pass my netty handler a eta function that in return takes a function something like 

```haskell
setHandler :: HttpRequest -> (HttpResponse -> Bool) -> Bool
``` 
For java to play nice with it i added FFI declarations for the Function/BiFunction interfaces so it ended up like
```haskell
data {-# CLASS "java.util.function.Function" #-} Function a b
  = Function (Object# (Function a b))
  deriving Class

foreign import java unsafe "@wrapper apply"
  jfunc :: (Extends a Object, Extends b Object)
        => (a -> Java (Function a b) b)
        -> Function a b

data {-# CLASS "java.util.function.BiFunction" #-} BiFunction a b c
  = BiFunction (Object# (BiFunction a b c))
  deriving (Class, Show)

foreign import java unsafe "@wrapper apply"
  jbifunc :: (Extends a Object, Extends b Object, Extends c Object)
          => (a -> b -> Java (BiFunction a b c) c)
          -> BiFunction a b c

data {-# CLASS "eta.netty.NettyHandlerContext" #-} NettyHandlerContext
  = NettyHandlerContext (Object# NettyHandlerContext)
  deriving Class

foreign import java unsafe "@new" setHandler :: BiFunction HttpRequest (Function HttpResponse JBoolean) JBoolean -> Java c NettyHandlerContext

```

Which seemed to work fine, but on the java side I needed a way to pass the function back into eta
So I've written something like

```java
  @Override
  public void channelRead(ChannelHandlerContext ctx, Object msg) {
    if (msg instanceof FullHttpRequest) {
      FullHttpRequest req = (FullHttpRequest) msg;
      Function<NettyResponse, Boolean> f = (NettyResponse r) -> {
          // Unhappy compiler above!
      }
      NettyRequest nreq = new NettyRequest(req, (InetSocketAddress)ctx.channel().remoteAddress());
      this.responder.apply(nreq, f);
    }
  }
```

Ultimately was trying to fit in with Wai's `Application` CPS style of handling requests a bit smoother

**Comment by rahulmutt** [comment]
Ok so the problem is that class file parser in `codec-jvm` only supports Java 7 class files right now and lambdas use `invokedynamic` which is specific to Java 8, hence the parsing is failing. I can make it return some default value instead of crashing and it'll still work. In the meantime, can you use an anonymous class to instantiate `Function<Boolean, Boolean>`?

**Comment by rahulmutt** [comment]
Working on a patch now, will verify and push to master in about ~30 minutes.

Great work btw! Let me know if you face any more issues and let us know in some manner (either Eta-Discuss/Gitter/Slack) when you've finished it.

**Comment by rahulmutt** [comment]
Fixed. Run `./update.sh` to get the updated compiler.

**Comment by aktowns** [comment]
Yep went with an anonymous class, quick response and fix! thank you :)
