### ISSUE TITLE
Change the example on eta-lang.org

### ISSUE THREAD

**Issue by seagreen** [typelead/eta#220]
The slow implementation of QuickSort is exactly what you would put up if you wanted to make a Haskell-style language look bad. Every time it gets discussed one of the top comments is about how the very first code snippet people see isn't actually practical real-world code, for example here: https://news.ycombinator.com/item?id=13374878

There are lots of awesome things Eta can do that can be shown off in a few lines and are also practical, any of them would be better than faux-quicksort.

**Comment by rahulmutt** [comment]
Honestly, that example is there because we couldn't think of anything better at the time. And I do agree that we can come up with better examples. I'll leave this open for anyone who wants to submit a replacement example.

**Comment by Yanpas** [comment]
The main site `http://eta-lang.org/` doesn't mention haskell at all, despite eta's syntax is almost identical to Haskell's one.

**Comment by gneuvill** [comment]
@Yanpas http://eta-lang.org/docs/html/faq.html?highlight=haskell

**Comment by Yanpas** [comment]
@gneuvill I know but I was talking about **main** page :)

**Comment by gneuvill** [comment]
@Yanpas oops, sorry

**Comment by Jyothsnasrinivas** [comment]
Closing this because we no longer have the QuickSort example on the homepage.
