### ISSUE TITLE
Incorrect comment on arrayToList in the docs

### ISSUE THREAD

**Issue by Xandaros** [typelead/eta#224]
In the [documentation](http://eta-lang.org/docs/html/getting-started.html#working-with-arrays), there is an incorrect comment for `arrayToList`:

```
-- Convert a lazy Eta list to a Java array
arrayToList :: JArray e c => Java c [e]
```

**Comment by rahulmutt** [comment]
What correction do you want to make? That the conversion happens in the `Java` monad?

**Comment by Xandaros** [comment]
The comment is the wrong way around. The function converts an array to a list, but the comment says it converts a list to an array.
