### ISSUE TITLE
Change colour for in-line code in the docs

### ISSUE THREAD

**Issue by Xandaros** [typelead/eta#225]
![](http://storage4.static.itmages.com/i/17/0211/h_1486803536_3968388_2527933921.png)

There is barely any contrast and is super hard to read.
I actually made a custom style (using the stylish plug-in) so I can read the docs...

**Comment by rahulmutt** [comment]
Be a bit courteous in the way you describe problems, thanks!

**Comment by awilliamson** [comment]
The contrast, as it stands, is very unpleasant. Bumping the contrast would massively improve readability. I struggled to read the image initially; so I'm going to say @Xandaros's point has merit. The title you changed, no longer states the issue. It sounds more like a PR. I'd suggest the phrase "Poor Readability for inline docs due to Colour/Contrast"

**Comment by Jyothsnasrinivas** [comment]
Changed the colour! @Xandaros @awilliamson can you check if it's readable now?

**Comment by Xandaros** [comment]
Well, the contrast is still pretty low, but it's certainly better to read.
This is how it looks with my custom style:
![](http://storage4.static.itmages.com/i/17/0215/h_1487132902_4272437_79f6811e80.png)

I think this is much easier to read while simultaneously showing that it is different from the rest and marking it as important.
Anyway, my point is that the in-line code is among the most important parts of the text and should always be easily readable. The actual hue doesn't matter that much. but please don't use a light colour on a light background for such an important part of the text.

**Comment by Jyothsnasrinivas** [comment]
@Xandaros Thanks for the feedback. Closing this issue for now because the core issue is resolved. We'll probably have future iterations to redesign and make it better.
