### ISSUE TITLE
Test and complete HSIConv (java port of c gnu lib iconv) error handling

### ISSUE THREAD

**Issue by jneira** [typelead/eta#232]
As commented in the issue #106 the error handling of https://github.com/typelead/eta/blob/master/libraries/base/java-utils/HSIConv.java is not complete (taking as reference the error handling of c lib iconv https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.3.html).
The last results of testing error cases has been:
- If the result is EILSEQ (malformed or unmmapable input in `java.nio`) input, the execution terminates abnormally printing `Prelude: undefined` and a generic stacktrace:
  - We'd have to compare the behaviour between ghc and eta in this case and make the neccesary fixes 
- If it is E2BIG (output buffer has no enough room), it prints the partial output buffer (f.e. `Hello ` instead `Hello World!`).  I suppose this is the same behavior than in ghc
  - We'd have to confirm this assumption is true
- I didnt find a easy way to handle the EINVAL case  (incomplete multybyte sequence at the end of input), cause java decoding handle this case as the malformed one (EILSEQ). If this case is important we could investigate a way to do it.
  - We'd have to analyze if this separate case supposes a pontentially useful error handling of the client code and implement it in HSIConv in such case

**Comment by rahulmutt** [comment]
@jneira Do we still need to take care of this? It looks like your iconv code has been fairly robust so far.

**Comment by jneira** [comment]
Yeah, i have not see any significant diff with ghc in encoding errors tests so we can close this one.
