### ISSUE TITLE
[eta-playground]: Bug - Don't use URI for sending source code

### ISSUE THREAD

**Issue by khatribharat** [typelead/eta#233]
I noticed that eta-playground uses URIs to encapsulate source code sent along with bug reports. That would throw errors even for ~150 LOC. 

Sample URI : https://github.com/typelead/eta/issues/new?title=%5Beta-playground%5D:%20Bug%20-%20%5Bdescription-here%5D&body=Source%20Code:%0A%60%60%60haskell%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0Amain%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20main%20::%20IO%20()%0Amain%20=%20print%20$%20quicksort%20%5B1,%20123,%2042,%2090,%2024,%2012,%203%5D%0A%0Aquicksort%20%5B%5D%20=%20%5B%5D%0Aquicksort%20(x:xs)%20=%20quicksort%20left%20++%20%5Bx%5D%20++%20quicksort%20right%0A%20%20%20%20where%20left%20%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3C%20x%20%5D%0A%20%20%20%20%20%20%20%20%20%20right%20=%20%5B%20y%20%7C%20y%20%3C-%20xs,%20y%20%3E=%20x%20%5D%0A%60%60%60%0A%0AOutput:%0A%60%60%60shell%0A%60%60%60%0A%0A%5Bwrite-further-description-here%5D%0A

**Comment by rahulmutt** [comment]
Thanks for the report! 

This is the only way I know of automating the bug report creation via GitHub. I figured that would be okay since most bugs that people might find via the playground can be reproduced with 5-10 lines of code max.

 If there happens to be a POST method of creating an issue with default contents, please do inform me.

The best thing we can do is to restrict the content size on the client and if it's too big, notify the user that they should manually copy the problematic code or try to create a minimal example.
