### ISSUE TITLE
epm build issue (windows 8)

### ISSUE THREAD

**Issue by Wildsoft** [typelead/eta#242]
Linking .stack-work\dist\2672c1f3\build\epm\epm.exe ...
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(Socket.o):fake:(.text+0x2ed2): undefined reference to `newAcceptParams'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(Socket.o):fake:(.text+0x2ee6): undefined reference to `acceptDoProc'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(Socket.o):fake:(.text+0x2f2c): undefined reference to `acceptNewSock'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(Internal.o):fake:(.text+0x15b): undefined reference to `getWSErrorDescr'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(Internal.o):fake:(.text+0x47b): undefined reference to `initWinSock'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(HsNet.o):HsNet.c:(.text+0x13): undefined reference to `__imp_getnameinfo'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(HsNet.o):HsNet.c:(.text+0x23): undefined reference to `__imp_getaddrinfo'
   C:\Users\me\AppData\Roaming\stack\snapshots\a4c7784c\lib\x86_64-windows-ghc-7.10.3\network-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W/libHSnetwork-2.6.3.1-C0mH8ySJgFMLyIlqp4bW3W.a(HsNet.o):HsNet.c:(.text+0x33): undefined reference to `__imp_freeaddrinfo'
   collect2.exe: error: ld returned 1 exit status

**Comment by rahulmutt** [comment]
Can you try wiping out the `.stack-work` directional and running `./install.sh` again? You may also need to wipe out the `stack` folder shown above - there might have been a problem with the compilation process.

**Comment by Wildsoft** [comment]
Thanks, cleared both (stack snapshot and .stack-work, but still get the same error. Will try to investigate it further

**Comment by rahulmutt** [comment]
It seems this is a very common stack problem on Windows, see https://github.com/commercialhaskell/stack/issues/875. If that doesn't work either, I suggest you file an issue there.

**Comment by Wildsoft** [comment]
OK, thanks

**Comment by rahulmutt** [comment]
@Wildsoft any luck on this?

**Comment by rahulmutt** [comment]
Closing because this seems to be inactive. Feel free to reopen if this issue remains in the new version or file a new issue.
