### ISSUE TITLE
eta build fails at building ghc-paths-0.1.0.9

### ISSUE THREAD

**Issue by basabuber** [typelead/eta#246]
I am unable to build eta from source. Would like to get help and help resolve this issue.

Stack version: 1.4.0.
Linux Version: Ubuntu 16.10 updated with latest patches.

The package ghc-paths fails to build:

Progress: 3/11
--  While building package ghc-paths-0.1.0.9 using:
      /tmp/stack17850/ghc-paths-0.1.0.9/.stack-work/dist/x86_64-linux-nopie/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.22.5.0 configure --with-ghc=/home/miki/.stack/programs/x86_64-linux/ghc-nopie-7.10.3/bin/ghc --with-ghc-pkg=/home/miki/.stack/programs/x86_64-linux/ghc-nopie-7.10.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/miki/.stack/snapshots/x86_64-linux-nopie/lts-6.27/7.10.3/pkgdb --package-db=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/pkgdb --libdir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/lib --bindir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/bin --datadir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/share --libexecdir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/libexec --sysconfdir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/etc --docdir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/doc/ghc-paths-0.1.0.9 --htmldir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/doc/ghc-paths-0.1.0.9 --haddockdir=/home/miki/git/eta/.stack-work/install/x86_64-linux-nopie/lts-6.27/7.10.3/doc/ghc-paths-0.1.0.9 --dependency=Cabal=Cabal-1.22.8.0-39a93ef541e462ed7a7da08beca21643 --dependency=base=base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d --dependency=directory=directory-1.2.2.0-660a7a83a753ed85c8a374c15dae2b97
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/miki/git/eta/.stack-work/logs/ghc-paths-0.1.0.9.log

    [1 of 2] Compiling Main             ( /tmp/stack17850/ghc-paths-0.1.0.9/Setup.hs, /tmp/stack17850/ghc-paths-0.1.0.9/.stack-work/dist/x86_64-linux-nopie/Cabal-1.22.5.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /home/miki/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack17850/ghc-paths-0.1.0.9/.stack-work/dist/x86_64-linux-nopie/Cabal-1.22.5.0/setup/StackSetupShim.o )
    Linking /tmp/stack17850/ghc-paths-0.1.0.9/.stack-work/dist/x86_64-linux-nopie/Cabal-1.22.5.0/setup/setup ...
    Configuring ghc-paths-0.1.0.9...
    setup: The program 'eta' is required but it could not be found.

(The last few lines are from the ghc-patchs-0.1.0.9.log. And I don't think the eta program is built at this point.)

Any help would be appreciated (and I assume other could/should hit this error.)

**Comment by rahulmutt** [comment]
Should be fixed with https://github.com/typelead/eta/commit/64399678c81817acef2553fecda49821bca2b683. Pull and try again with `./cleaninstall.sh`?

**Comment by rahulmutt** [comment]
Should be fixed with 6439967. Try again with ./update.sh?

**Comment by tonymorris** [comment]
I can confirm that it now works for me. Thanks @puffnfresh and @rahulmutt 

    % which eta > /dev/null && echo $?
    0

**Comment by basabuber** [comment]
@rahulmutt - thank you for the quick response! It builds now. On Ubuntu, I found the need to install 2 additional native libraries: libncurses5-dev and libbz2-dev.
