### ISSUE TITLE
[Request] A safe cast operation in the standard library

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#247]
A common issue when interacting with java code (an even more so when interacting with non typesafe languages such as clojure) is converting an object at runtime depending on its concrete type.

Because of the hierarchical structure of the java class system this is often most conveniently done by attempting to cast the object in question to the desired class and providing a backup in case of failure.
This is a prime use case of `Maybe`.
I therefore propose the addition of a safe casting function to the standard library.

```Haskell
-- `safeCast` as pendant to `unsafeCast`
safeCast :: Extends a b => b -> Maybe a
```

A typical use case would be like so:

```Haskell
data {-# CLASS "my.library.Binding" #-} Binding = Binding (Object# Binding) deriving Class

data FnReturn = Direct Binding | Destructure [Binding]

-- in clojure we will will either have the binding direct or a collection of them, since the support for ADT's is not as good
convertFromNative :: Object -> FnReturn
convertFromNative o = maybe (Direct $ unsafeCast o) (Destructure . fromJava) (safeCast o :: Maybe (Collection Binding))
```

**Comment by rahulmutt** [comment]
1. Run `git pull`.
2. Go into `libraries/base` and run `epm install --solver=topdown`.
3. Go to your working project and do `epm clean` and then `epm build`. The clean will remove references to the old base library.
