### ISSUE TITLE
Shake error when updating eta

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#250]
I tried to run both `update.sh` as well as `install.sh` in the repository after switching to the `0.0.5b1` tag in the eta repo.

In both cases the script ended with the following error.
```
# eta-pkg (for install)
# epm (for install)
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
Downloading the latest package list from git.etlas.eta-lang.org
warning: redirecting to https://github.com/typelead/etlas/
fatal: refusing to merge unrelated histories
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: epm update
Exit code: 128
Stderr:
warning: redirecting to https://github.com/typelead/etlas/
fatal: refusing to merge unrelated histories
)
```

**Comment by rahulmutt** [comment]
We're currently working on setting up a package index for Eta-specific packages and the changes must have bled through. 

1. Wipe out `~/.epm`
2. Checkout `0.0.5b2`
3. Run `./cleaninstall.sh`

**Comment by JustusAdam** [comment]
Running `cleaninstall.sh` fails with `<repo>/epm/Cabal/: getDirectoryContents:openDirStream: does not exist (No such file or directory)`

**Comment by JustusAdam** [comment]
I also tried deleting the repo and recloning and I got

```
Stack looks for packages in the directories configured in the 'packages' variable defined in your stack.yaml
The current entry points to /Users/justusadam/projects/eta/codec-jvm/ but no .cabal file could be found there.
```

**Comment by rahulmutt** [comment]
Can you run `git submodule init` & `git submodule update --recursive` and then try again?

**Comment by JustusAdam** [comment]
Ah all right. I must have forgotten the `--recursive` flag in the clone command. It seems to install now.

**Comment by rahulmutt** [comment]
Great. Please give me a confirmation once the installation completes successfully so I can close this issue.

**Comment by JustusAdam** [comment]
It installed, thanks for the help.
