### ISSUE TITLE
Static method exports

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#255]
```haskell

someMethod1 :: Int -> Int -> Int
someMethod1 x y = ...

someMethod2 :: Int -> Int -> IO Int
someMethod2 x y = ...

someMethod3 :: Int -> Int -> Java a Int
someMethod3 x y = ...

foreign export java "@static eta.static.SomeClass.someMethod1" someMethod1 :: Int -> Int -> Int
foreign export java "@static eta.static.SomeClass.someMethod2" someMethod2 :: Int -> Int -> IO Int
foreign export java "@static eta.static.SomeClass.someMethod3" someMethod3 :: Int -> Int -> Java a Int
```

will export to:

```java
package eta.static;

public class SomeClass {
    public static int someMethod1(int x, int y) {
       //... generated code
    }

    public static int someMethod2(int x, int y) {
       //... generated code
    }

    public static int someMethod3(int x, int y) {
       //... generated code
    }
}
```

**Comment by JustusAdam** [comment]
Thats pretty much what I had envisioned. However it would be nice to also export suff which is not in the `IO` monad.

Like so:

```Haskell

pureMethod :: Int -> Int -> Int
pureMethod x y = ...

foreign export java "@static org.myproject.AwesomeClass.pureMethod" pureMethod :: Int -> Int -> Int
```

**Comment by rahulmutt** [comment]
@JustusAdam Updated the original post to account for pure return types as well.

**Comment by JustusAdam** [comment]
Hmm ... I'm not sure the third one makes sense ... I se that it's possible but it doesn't really need the `Java` environment ... But perhaps for convenience it makes sense.

**Comment by rahulmutt** [comment]
Yes, that's purely for convenience. The `Java` environment is equivalent to the `IO` monad in static contexts. Say you have `forall a. Java a b`. That's isomorphic to `IO b` in the sense that the internal object that's carried around in the primitive state monad is used as a sequencing token.
