### ISSUE TITLE
[Suggestion] Report type errors for field imports

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#257]
If a field is imported into eta with the wrong type, like so:

```Java
class TheClass {
    public int field1;
}
```

```haskell
data {-# Class TheClass #} TheClass = TheClass (Object# TheClass) deriving Class

foreign import java "@field field1" getField1 :: TheClass -> Bool
```

We get a runtime error `FieldNotFound` (or similar), which just states that `field1` could not be found.

It would be nice if that error could state that a field with the same name but a different type exists. 

Or even better, the compiler could check that an imported field actually exists and whether it has the correct type and if it doesn't tell you what type the field actually has.

**Comment by rahulmutt** [comment]
Closing, addressed by #217.
