### ISSUE TITLE
[etlas] Support spark deployments natively

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#266]
Spark development in Eta is onerous right now because you have to wait for uberjars to build (really kills dev productivity). I propose a native support for Spark in etlas where we send the location of the dependency jars to `spark-submit` and avoid the repeated overhead of uberjar generation.

Specifying you want Spark:
`etlas configure --spark-deployment`
OR
new cabal field per executable: `deployment-mode: spark`.

`etlas run --with-spark-submit=[PATH-TO-SPARK-SUBMIT] -- [args for spark submit]`

**Comment by Jyothsnasrinivas** [comment]
The gradle plugin can support customized deployments pretty well, so it makes more sense to use it for these use cases.
