### ISSUE TITLE
[etlas] Support an extensible mechanism for deployments to JVM systems

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#267]
Current we have a need for custom deployments to servlet containers & `spark-submit`. There exist other execution frameworks.

1. Have a custom Cabal field that specifies for a given executable, test, or benchmark, how to deploy the compiled jars. I suggest `deployment-mode:`. The supported modes (as of now) should be: `jar (default), war, spark` (maybe we can add `osgi` and `docker` to the list as well?). Each mode will expect a specific directory structure that we should document thoroughly.
OR
Have a flag to `etlas configure --deployment-mode=[mode]` (same values as above).

For now we can manually add support for all the popular JVM deployment mechanisms, but we should come up with a way for users to specify custom deployments - maybe a simple yaml/json file that allows users to specify location of bash/cmd scripts for a given deployment mode which can be hosted on a git repo. Thoughts/suggestions?

**Comment by jneira** [comment]
Sadly, cabal seems to doesn't have an easy way to extend builds (at least using deployment simple):
maybe using `build-type: Custom`  and `UserHooks`?

**Comment by rahulmutt** [comment]
See my recent comment on #305.

Summary: The mechanism is using `build-type: Custom` & `UserHooks` as you suggested.

**Comment by Jyothsnasrinivas** [comment]
The gradle plugin can support customized deployments pretty well, so it makes more sense to use it for these use cases.
