### ISSUE TITLE
[etlas] Saved dump-stg files in installation directories

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#279]
To make sense of stack traces, we must get the STG dumps which know exactly what each method does. Just like `.hi` files are saved when installing, `dump-stg` files should also be saved so that they can be parsed and used to build tools that can convert a standard Java stack trace into a more useful stack trace for users. It also aids in debugging Eta RTS errors.

**Comment by jneira** [comment]
Maybe it is less needed having stackatraces
