### ISSUE TITLE
`./install.sh` fails with 404 for http://hackage.haskell.org/packages/archive/root.json

### ISSUE THREAD

**Issue by pparkkin** [typelead/eta#294]
Pulled latest `master` branch and ran `./install.sh`.

Get the following error.
```
# etlas (for install)
Warning: Caught exception during _mirrors lookup:dieVerbatim: user error
(etlas: '/usr/bin/nslookup' exited with an error:
)
Warning: No mirrors found for http://hackage.haskell.org/packages/archive
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: etlas update
Exit code: 1
Stderr:
Warning: Caught exception during _mirrors lookup:dieVerbatim: user error
(etlas: '/usr/bin/nslookup' exited with an error:
)
Warning: No mirrors found for http://hackage.haskell.org/packages/archive
Unexpected response 404for http://hackage.haskell.org/packages/archive/root.json
)

Unexpected response 404for http://hackage.haskell.org/packages/archive/root.json
```

Ubuntu 16.04.1 running in a VM on VirtualBox.

Networking seems to be fine. I can `curl` hackage.haskell.org.
```
(guest) € curl -I http://hackage.haskell.org/packages
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.0 (Ubuntu)
Content-Type: text/plain
Location: /packages/
Accept-Ranges: bytes
Date: Tue, 11 Apr 2017 07:06:11 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sin18035-SIN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1491894371.712216,VS0,VE908
```

I get the same 404 outside the VM.
```
(host) € curl -I http://hackage.haskell.org/packages/archive/root.json
HTTP/1.1 404 Not Found
Server: nginx/1.10.0 (Ubuntu)
Content-Type: text/plain
Content-Length: 43
Accept-Ranges: bytes
Date: Tue, 11 Apr 2017 07:06:40 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-itm7424-ITM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1491894400.598514,VS0,VE594
Vary: Accept-Encoding
```

**Comment by rahulmutt** [comment]
Run `etlas update -v3` and share the output (pastebin or the like). I have a feeling it may have to do with your network configuration for your VM. Can you also try accessing the `https` variants of all those urls?

**Comment by pparkkin** [comment]
https://pastebin.com/FRzYN3Tr

Everything else networking-wise works fine in the VM, and I've never had any issues with it. Also, using `curl` to get the URLs works identical in the VM and in the host.

**Comment by rahulmutt** [comment]
It looks like a DNS lookup problem - `nslookup` failure. I wiped out my `.etlas` folder to have it bootstrap and these are the messages I got:
```
Trying to locate mirrors via DNS for initial bootstrap of secure repository
'http://hackage.haskell.org/packages/archive' ...
Searching for nslookup in path.
Found nslookup at /usr/bin/nslookup
/usr/bin/nslookup '-query=TXT' _mirrors.hackage.haskell.org
located 2 mirrors for http://hackage.haskell.org/packages/archive :
- http://hackage.fpcomplete.com/
- http://objects-us-west-1.dream.io/hackage-mirror/
...
```
It turns out that even for me, `http://hackage.haskell.org/packages/archive/root.json` is not found, so `etlas` immediately goes to the next mirror (`hackage.fpcomplete.com`) which seems to be succeeding.

**Comment by rahulmutt** [comment]
As a temporary workaround, you can comment out the lines
- `unit $ cmd "etlas update"`
- `unit $ cmd ["etlas", "install", "template-haskell", "--allow-boot-library-installs"]`
in your `shake/Build.hs` to avoid an update.
(They are the only steps that require internet and you can do *need* them.)

**Comment by pparkkin** [comment]
You are correct. It was a problem with the DNS on the VM.

For anyone with the same issue, to fix it I had to turn *off* the DNS proxy and host resolver settings described here http://serverfault.com/a/453260. Note that the settings may also be in your `Vagrantfile`.
