### ISSUE TITLE
Generate Signature attribute for exported class to preserve generics information

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#298]
Credits to @filippovitale for finding out a sorely missing feature in Eta while playing around with Akka Streams and Scala interop in general.

```haskell
foreign export java someFlow :: Java Example (Flow JString JString NotUsed)
```

This export generates something like:

```java
public class Example
{
  public Flow someFlow()
  {
    ...
  }
}
```

But we want the compiler to preserve the type arguments to `Flow` and generate this output:
```java
public class Example
{
  public Flow<String,String,NotUsed> someFlow()
  {
    ...
  }
}
```
This amounts to generating `Signature` attribute in the class file, which should be fairly straightforward.

Given that this will help Scala type inference/interop, this is a high priority feature.

**Comment by filippovitale** [comment]
A workaround at the moment could be using `.asInstanceOf[]` :

```
  val e = new Example()
  val lolcatFlow = e.lolcatFlow().asInstanceOf[javadsl.Flow[String, String, NotUsed]]
```
