### ISSUE TITLE
Does etlas will auto install with eta?

### ISSUE THREAD

**Issue by JulianZhang** [typelead/eta#312]
I had install eta 0.0.5b3 follow the blow guide.

http://eta-lang.org/docs/html/getting-started.html

The guide only ask me to install eta from code and then check both eta and etlas.
But after the eta had been installed, the etlas didn't install on my Mac.

I want to know does the etlas will auto install with eta, or I need download  etlas's code and install it?
If the etlas didn't auto install with eta, I think the guide need change.

**Comment by rahulmutt** [comment]
Please do the installation steps again with `0.0.6b2`. We had a breaking change (the build tool was renamed from `epm` to `etlas`) and the docs are written for 0.0.6+.
