### ISSUE TITLE
Make RTS primops static methods

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#336]
Currently they are subclasses of `RtsFun`. There's no good reason not to make them static methods.

#335 should be tackled before this.

This change requires
1.) Transforming all children of `RtsFun` to static methods. For example,

```java
    public static RtsFun catch_ = new Catch();

    private static class Catch extends RtsFun {
        @Override
        public void enter(StgContext context) {
            StgClosure handler = context.R(2);
            StgTSO tso = context.currentTSO;
            ListIterator<StackFrame> sp = tso.sp;
            int exceptionsBlocked = tso.showIfFlags(TSO_BLOCKEX | TSO_INTERRUPTIBLE);
            sp.add(new StgCatchFrame(exceptionsBlocked, handler));
            Apply.ap_v_fast.enter(context);
        }
    }
```

```java
    public static void catch(StgContext context, StgClosure io, StgClosure handler) {
            StgTSO tso = context.currentTSO;
            ListIterator<StackFrame> sp = tso.sp;
            int exceptionsBlocked = tso.showIfFlags(TSO_BLOCKEX | TSO_INTERRUPTIBLE);
            sp.add(new StgCatchFrame(exceptionsBlocked, handler));
            io.apply(Void.void_);
        }
    }
```
2. `ETA.CodeGen.Prim.cgOpApp` must be changed to generate static method calls.

**Comment by puffnfresh** [comment]
Does this issue cover things like Apply?

**Comment by rahulmutt** [comment]
It does actually, but after #335, we won't have any more `Apply` `RtsFun`'s because they do unnecessary work where a direct call to `apply` would have been sufficient. I updated the code above to reflect the changes of #335 as well.

**Comment by rahulmutt** [comment]
Implemented in `going-stackless`.
