### ISSUE TITLE
Error decoding strings with non-ascii chars using Data.Text.Encoding.decodeUtf8With

### ISSUE THREAD

**Issue by jneira** [typelead/eta#354]
Two cases:
* `print $ decodeUtf8With strictDecode "ñ"`
  * `***Exception***: Cannot decode byte '\xf1': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream`
  * [trace.txt](https://github.com/typelead/eta/files/981183/trace.txt)
* `print $ decodeUtf8With lenientDecode "ñ"`
  * prints "" instead "ñ"
* `print $ decodeUtf8With lenientDecode "añ"`
  * `Exception in thread "main" java.nio.BufferOverflowException`
  * [trace2.txt](https://github.com/typelead/eta/files/981195/trace2.txt)

**Comment by jneira** [comment]
i've rerun the tests, comparing etlas/eta with stack/ghc (resolver lts-6.27)
* Code:
```haskell
  putStrLn "\xf1"
  putStrLn "ñ"
  putStrLn "\xc3\xb1"
  print $ decodeUtf8With lenientDecode "ñ"
  print $ decodeUtf8With lenientDecode "añ"
  print $ decodeUtf8With strictDecode "ñ"
```
* With stack/ghc:
```
ñ
ñ
Ã±
"\65533"
"a\65533"
eta-test.EXE: Cannot decode byte '\xf1': Data.Text.Internal.Encoding.decodeUtf8:
 Invalid UTF-8 stream
```
* With etlas/eta
```
±
±
├▒
"\65533"
"a\65533"
Exception in thread "main" eta.runtime.exception.EtaException: Cannot decode byt
e '\xf1': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
        at base.ghc.Exception$$Lr8O7Ylvl.enter(Exception.hs)
```

So the behaviour of `decodeUtf8With` (the cause of the issue) is the same, but the handling of unicode chars is not.
Maybe we should close this issue and open another about unicode handling in eta.

**Comment by jneira** [comment]
Examining more carefully the output it turns out eta is handling correctly utf-8 strings but in windows console you need to do some steps:
* change the console font to  `Lucida`
* change the code page to 65001: `chcp 65001`
* execute java with `-Dfile.encoding=UTF-8`

With this steps the non-ascii chars are correctly displayed.

To avoid this we would have to read the current default encoding (with System.getProperty("file.encoding") and replace `eta.runtime.io.MemoryManager.loadStringUTF8(String s)` calls with `eta.runtime.io.MemoryManager.loadString(String encoding, String s)`

**Comment by rahulmutt** [comment]
Thanks for looking into this. This looks like a recurring problem - what should be the final solutions for this? I'm not sure setting the encoding for `loadString` is the right solution since that has to do with the encoding at compile-time (the source files), while this problem appears to be the runtime. Is it safe to always send `-Dfile.encoding-UTF-8` with setting the codepage?

**Comment by rahulmutt** [comment]
Just saw you filed #515. Closing this one.
