### ISSUE TITLE
[etlas] Show running time of program after `etlas run` finishes

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#355]

**Comment by ouromoros** [comment]
I was trying to use getCPUTime around the runSystemExitWithEnv call to compute elapsed time and failed. I'm wondering how shoud I do it? Does runSystemExitWithEnv run in another thread or else? Using system time seems not to be a choice here. I'm kind of stuck.

**Comment by rahulmutt** [comment]
@ouromoros By failed, do you mean you get a really tiny value? Can you share the diff of the code changes you made?

**Comment by ouromoros** [comment]
Oh, of course. The computed time is always around 0.1 sec despite it is obvious not so. Here's related piece:
```haskell
  notice verbosity $ "Running " ++ display (exeName exe) ++ "..."
  startTime <- getCPUTime
  rawSystemExitWithEnv verbosity path (runArgs++exeArgs) env'
  endTime <- getCPUTime
  let diffTime = fromIntegral (endTime - startTime) / (10^10)
  printf "Run time: %0.3f sec.\n" (diffTime :: Double)
```

**Comment by rahulmutt** [comment]
Try using `getCurrentTime` from `Data.Time` and see what happens?

**Comment by ouromoros** [comment]
@rahulmutt Yes, it works as expected using `getCurrentTime`. In fact, after thinking about it again, it appears to me that under this context, using system time is more likely to make sense and is more intuitive. I'll submit a PR then.
