### ISSUE TITLE
Unrecognised pragma INTERFACE (asked to report)

### ISSUE THREAD

**Issue by twoquarterrican** [typelead/eta#361]
I figured out what I did wrong, so this is not really an issue for me now, but the error message requested a bug report, so here you go:

error message:
```
src/Main.hs:15:6: Warning: Unrecognised pragma

<no location info>:
    eta: panic! (the 'impossible' happened)
  (Eta version 0.0.6):
	rawTagTypeToText: You should annotate  Call

Please report this as a Eta bug: http://github.com/typelead/eta/issues
```
caused by incorrectly guessing the syntax for importing a java interface:
```
data {-# INTERFACE "okhttp3.Call" #-} Call = Call (Object# Call)
   deriving Class

**Comment by rahulmutt** [comment]
Rather confusing, but in Eta, even for interfaces, you should use the CLASS annotation. Please see #359 where I tell you the way to fix it. These confusion will be gone once we get #140.

**Comment by twoquarterrican** [comment]
BTW, I like style 1 on #140
