### ISSUE TITLE
Use Intrusive Lists to model the stack

### ISSUE THREAD

**Issue by Abhiroop** [typelead/eta#363]
The PR https://github.com/typelead/eta/pull/362 already saw a 30% performance increase by using LinkedLists instead of Vector. A further optimization would be using Intrusive Lists which has additional [performance benefits.](http://www.boost.org/doc/libs/1_35_0/doc/html/intrusive/usage_when.html)

A very simplistic model of an intrusive list would look like this: (From StackOverflow)
```java
public interface IntrusiveListElement<E extends<IntrusiveListElement<E>> {
  public void setNext(E next);
  public E getNext();
  public void setPrev(E prev);
  public E getPrev();
}

public class IntrusiveList<E extends IntrusiveListElement<E>> implements List<E> {
  // implement your run-of-the-mill double-linked list here
}
```
This would speed up `remove()` calls avoiding double dereferencing.

**Comment by rahulmutt** [comment]
Since most of the interaction with the Eta stack uses the `ListIterator` interface, we just need to make sure we can implement it for `IntrusiveList` and every else should *just work*.

**Comment by rahulmutt** [comment]
We no longer maintain a separate stack, so this issue is now irrelevant.
