### ISSUE TITLE
Optimize the performance of `readTVar`

### ISSUE THREAD

**Issue by Abhiroop** [typelead/eta#365]
The runtime traditionally uses a data structure called `Transaction Log` to maintain a buffer of reads and writes to the currently ongoing and uncommitted transaction. The `Transaction Log` is implemented using a linked list.

Each `readTVar` must traverse the log to check whether the TVar was written by an earlier `writeTVar`. Hence, `readTVar` is an O(n) operation in the length of the log.

This is wasteful when the log only contains read operations.

I suggest a probabilistic approach to speeding up the `readTVar` operation by using a Bloom Filter, which can answer **negative** membership queries in O(1) time. (False positives are possible in which case we anyways have to traverse the linked list.) A hash map/set can solve the same but this will be more space efficient.

In the absence of a writeTVar in the log, this operation will happen in O(1)(excluding the append which is already O(1))

**Comment by rahulmutt** [comment]
Implemented in the `going-stackless` branch, though we don't use a bloom filter, we just use a simple hashmap.
