### ISSUE TITLE
Derive Show for all the types in Java.Collections

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#367]

**Comment by ouromoros** [comment]
Hey, I would like to work on this issue. I know the API of Java.Collections types but am not quite sure how Eta deals with it. Can you guide me how to get started?

**Comment by rahulmutt** [comment]
@ouromoros After a second look at the issue, it's probably not a good idea to have Show instances for collections which tend to be mutable while Show is a pure function from `a -> String`. Please find another issue to work on.
