### ISSUE TITLE
New release failed in docker hub

### ISSUE THREAD

**Issue by JulianZhang** [typelead/eta#370]
Hi, I had try to run eta with docker on ubuntu, But I find the version about the eta is 0.0.5.

I had check the [link](https://hub.docker.com/r/typelead/eta/builds/) it shows that all build after 0.0.5 are failed.

**Comment by rahulmutt** [comment]
@JulianZhang After @AlexeyRaga's changes, it seems to work now. Can you give it another try?

**Comment by JulianZhang** [comment]
@rahulmutt I can check again, the new version on docker is 0.0.6b8
