### ISSUE TITLE
[etlas] Not getting an uberjar for libraries

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#396]
I have some code without a Main module. It is meant to be called from some Java code. I don't want to have to copy files out of my `~/.etlas` directory or put  them on my classpath. I would just like an Uber JAR with the dependencies instead.

I think the current Uber JAR mechanism only works for executables.

**Comment by jneira** [comment]
Maybe it is a duplicate of #305?

**Comment by puffnfresh** [comment]
@jneira yeah, I think so

**Comment by adamschoenemann** [comment]
I seem to have the same problem. It's not clear for me what the solution is exactly? Additionally, I cannot find any documentation about all this uberjar business except for scouring the issues.

**Comment by rahulmutt** [comment]
You can create an uberjar by creating a `cabal.project` file and adding the following line:

```
uberjar-mode: True
```

(or equivalently `etlas build --enable-uberjar-mode` but you must pass in that flag *every* time)

Note that this setting only applies to executable components and not library components, so the workaround for now is to make an executable component with your code and add `main = return ()` in your `Main.hs` file.

Adding support for library components is not too hard, but it does require adding an additional flag inside the compiler.

Regarding the docs, I think it might've gotten lost when we migrated to a new documentation system. We'll take a look and update it.

**Comment by adamschoenemann** [comment]
OK, thanks for the info!
