### ISSUE TITLE
Support for C FFI

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#4]
### Motivation

A suggestion was given on reddit about supporting the C FFI for greater library support on Hackage.

My reservations on this matter are:
1. Using JNI locks you onto the platforms that the C library supports. 
**Comment**: After further thought, most server-side applications in production will typically not shift between architectures/hardware very frequently and during the time they migrate then can link a different version of the library that supports that platform. @mgsloan also notes that some of the Hackage libraries make use of cross-platform C libraries, so this may not be a serious issue.
2. Too many context switches.
**Comment**: In order to call to the C FFI, first you must call a native Java method (which is a Java FFI call) and then the JVM does a context switch to the native world. So essentially, you're switching from Haskell world -> Java world -> Native world and then you have to follow that sequence of switches in reverse. I expect this to be costly, but we can test it out and see what happens. Moreover, there may be cases where it is actually faster to use the Java method that performs the same task if it exists in some library. This needs to be checked.
### Implementation

The RTS needs no special support other than that of Java FFI. The entire implementation will be in the codegen.
1. When a foreign import declaration with the ccall calling convention is used

``` haskell
foreign import ccall "someheader.h somefunc" somefunc :: Int -> Int
```

   an appropriate native method declaration is made with the Z-encoded Haskell name in the declaration. 
1. A field is generated which generates a function closure of matching arity which upon entry should call the generated native method, taking in the appropriate arguments and casting as appropriate. 
2. A static initializer block is generated to load the dynamic library containing the native method implementation.
3. After code generation, another step is performed using `javah` to generate the header file for the class and the native method declaration and to generate a `.c` file that will call the C function mentioned above in quotes.
4. After the C file generation, gcc should be run to compile the generated C file into a .dll (if windows) or .so (if linux). This part will be tricky handling all the platforms.

**Comment by mgsloan** [comment]
Hey!  Thanks for taking my suggestion into consideration, I think it could be quite cool!  On one of this guy's machines, a JNI call that just returns an `int` takes `6.657 ns`, so that's not /too/ bad.  http://stackoverflow.com/a/13977914/1164871

**Comment by rahulmutt** [comment]
No problem. It could have a huge impact on the speed at which GHCVM can support all of Hackage. Also, it's pretty cool being able to support two FFI's - that increases the scope of libraries that can be used. 

Btw, can you do me a favor and list out some frequently used Haskell libraries that use the C FFI and that are not bundled with GHC? I want to get an idea of how important those libraries are to day-to-day Haskell development and that might motivate me to pull this feature implementation back a milestone or two.

**Comment by mgsloan** [comment]
The shims for C functions used in GHCJS might give some impression of the C stuff needed for some frequently used base libraries: https://github.com/ghcjs/shims/tree/master/pkg

Without C FFI such libraries will need to be heavily modified to work via JVM APIs.

**Comment by DemiMarie** [comment]
What about using JNR?  It can generate JNI stubs, and in some cases is very fast.

**Comment by rahulmutt** [comment]
@DemiMarie I'm cool with JNR as well. I just don't want people to incur a heavy dependency for C FFI usage, but it might not be so bad.

**Comment by jneira** [comment]
I think the main direction had been towards patching hackage packages. Not sure if this continue being needed (due to other use cases). I think we can close it for know and (re)open in that case.
