### ISSUE TITLE
StackOverflowError when converting from JByteArray to strict ByteString

### ISSUE THREAD

**Issue by jonathanknowles** [typelead/eta#401]
## How to reproduce

The following code snippet ([source](https://github.com/jonathanknowles/eta-bytearray-conversion/blob/17296a1f148a23de70c39fea5a54c946b56ff5f0/source/Main.hs
)) is enough to reproduce the error:

```haskell
module Main where

import Data.ByteString (ByteString)
import Java
import System.IO (BufferMode (..), hSetBuffering, stdout)

import qualified Data.ByteString as B

createJByteArray :: Int -> JByteArray
createJByteArray i = pureJava $ anew i

toByteString :: JByteArray -> ByteString
toByteString ba = B.pack $ fromIntegral <$> bs
    where bs = fromJava ba :: [Byte]

main :: IO ()
main = do
        hSetBuffering stdout NoBuffering
        mapM_ test byteArraySizes
    where
        byteArraySizes = [2 ^ x | x <- [0 .. 24]]
        test :: Int -> IO ()
        test i = do
            putStr "Testing with array of size (bytes): "
            print i
            let j = B.length $ toByteString $ createJByteArray i
            putStr "Final converted array size (bytes): "
            print j
```
## Output
```
Testing with array of size (bytes): 1
Final converted array size (bytes): 1
Testing with array of size (bytes): 2
Final converted array size (bytes): 2
Testing with array of size (bytes): 4
Final converted array size (bytes): 4
Testing with array of size (bytes): 8
Final converted array size (bytes): 8
Testing with array of size (bytes): 16
Final converted array size (bytes): 16
Testing with array of size (bytes): 32
Final converted array size (bytes): 32
Testing with array of size (bytes): 64
Final converted array size (bytes): 64
Testing with array of size (bytes): 128
Final converted array size (bytes): 128
Testing with array of size (bytes): 256
Final converted array size (bytes): 256
Testing with array of size (bytes): 512
Final converted array size (bytes): 512
Testing with array of size (bytes): 1024
Final converted array size (bytes): 1024
Testing with array of size (bytes): 2048
Final converted array size (bytes): 2048
Testing with array of size (bytes): 4096
Final converted array size (bytes): Exception in thread "main" java.lang.StackOverflowError
        at eta.runtime.stg.AbstractArgumentStack.R(AbstractArgumentStack.java:28)
        at eta.runtime.stg.StgContext.R(StgContext.java:93)
        at main.Main$toByteString1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:116)
        at eta.runtime.apply.Apply$ApPFast.enter(Apply.java:96)
        at eta.runtime.thunk.Ap2Upd.thunkEnter(Ap2Upd.java:21)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
```

**Comment by rahulmutt** [comment]
@jonathanknowles Thanks a lot for providing a minimal example! Will look into it by this weekend.

**Comment by rahulmutt** [comment]
Had a look at this today, this is indeed a bug!

This is the STG dump of the `bytestring.data.bytestring.Internal$zdwa` closure:

```haskell
Data.ByteString.Internal.$wa
  :: GHC.Prim.Addr#
     -> [GHC.Word.Word8]
     -> GHC.Prim.State# GHC.Prim.RealWorld
     -> (# GHC.Prim.State# GHC.Prim.RealWorld, () #)
  = \ww_sW24 w_sW25 w1_sW26
        case w_sW25 of _ {
          [] -> (#,#) [w1_sW26 GHC.Tuple.()];
          : x_sW28 xs_sW29 ->
              case x_sW28 of _ {
                GHC.Word.W8# x1_sW2B ->
                    case
                        writeWord8OffAddr# ww_sW24 0 x1_sW2B w1_sW26
                    of
                    s2_sW2C
                    { __DEFAULT ->
                          case plusAddr# ww_sW24 1 of sat_sW2D {
                            __DEFAULT -> Data.ByteString.Internal.$wa sat_sW2D xs_sW29 s2_sW2C;
                          };
                    };
              };
        };
```
As you can see, there's a recursive call at the very end, but for some strange reason the loopification optimisation didn't optimise that into a loop!

**Comment by rahulmutt** [comment]
Turns out this was something the GHC devs didn't catch until recently: https://ghc.haskell.org/trac/ghc/ticket/11372

Going to backport the fix.

**Comment by rahulmutt** [comment]
Fixed. The above program now runs completely, but fails in the last case (2^24) with "GC Overhead Limit Exceeded" as mentioned in another issue.

**Comment by jonathanknowles** [comment]
That's great news @rahulmutt 

I'll make sure to check the fix on my system. :)

I'm surprised that this bug managed to find its way into GHC, given the number of functions in `base` whose performance would be affected by this optimization not triggering. (But then again, the bug report only cites a 3-5% speedup, so perhaps it was easy to miss.)

By the way, have you thought of adding a test case for this, in case a similar regression occurs in future? (Given the JVM stack limitations, it could mean that Eta is more sensitive to this kind of bug.)

**Comment by rahulmutt** [comment]
Even I was surprised that it wasn't detected until recently. This change should yield a non-trivial perf increase for Eta programs overall though, so thanks a lot for reporting this! The reason is that if the loopification isn't hit, it's as bad as writing a recursive function in Java :)

Waiting for CircleCI to run the benchmarks, so we can see how big of a change this yields. Will post a summary of the changes in this thread once it's done.

Yes, we should certainly add a test case for this. I was working on porting the GHC test suite a month ago but had to de-prioritize it because it was eating up too much time. Hopefully I'll get around to that within the coming weeks and we can add on tests like this. I'll keep this open until then.

**Comment by rahulmutt** [comment]
Updates: No significant perf increases for [eta-benchmarks](https://github.com/typelead/eta-benchmarks) mainly because it seems most of the existing benchmarks don't tickle this bug. There is one that does: `shootout/n-body` which required a ridiculous 285M of JVM stack to run to completion which now can run with the default JVM stack size settings.
