### ISSUE TITLE
Make error messages for binary index files less ominous

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#409]
When running `etlas update`, you may get errors that look like:
```
[eta-0.0.6b6] Failed to download binary index file - https://6899fa2dcac85d20d41
7-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.6.6/binaries/inde
x.i386-windows
```

This is not really an error but just that the binary index server doesn't have the required index file for your platform. The wording should be changed to indicate that it's not as serious as it sounds.

**Comment by jneira** [comment]
Resolved by https://github.com/typelead/etlas/issues/9
