### ISSUE TITLE
A compatibilty status website for Haskell packages in Eta

### ISSUE THREAD

**Issue by abhi18av** [typelead/eta#410]
Hello Eta team:)

First of this is an awesome initiative - thanks :+1: 

Now, I've seen the `etlas` and the `eta-hackage` repos and I know that there's a list of supported libraries but could you please provide a more visual way of identifying. Like the way `travis-ci` provides badges for the libs. I really recommend that such a beginner-friendly page be set-up so it might actually be advisable for Haskell beginners to try out various Haskell books and begin with `eta` itself from the very start. 

If there's already such a page, please let me know.

**Comment by rahulmutt** [comment]
The user-friendly page you're talking about is the Etlas website (in progress). We'll hopefully have that out very soon.

**Comment by abhi18av** [comment]
@rahulmutt I came across the exact thing I had in mind 

http://packages.pypy.org

Feel free to close the issue, it's meta.

**Comment by rahulmutt** [comment]
Yup we had something similar in mind. Will do an announcement on Twitter once it's out, so make sure to follow us there!
