### ISSUE TITLE
Uniform case analysis for data cons with < 6 fields

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#420]
Courtesy of @carymrobbins:
```
% ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/crobbins/dotfiles/.ghci
λ data Foo = Bar Int | Baz String deriving Show
λ foos = [Bar 2, Baz "hey"]
λ foos
[Bar 2,Baz "hey"]
λ data Thing = Spam Int | Eggs String deriving Show
λ :m + Unsafe.Coerce
λ things = unsafeCoerce foos :: [Thing]
λ things
[Spam 2,Eggs "hey"]
```

The above will cause a `ClassCastException` in the current version of Eta. By adding specialised classes `StgConstrN` for N = 0,...,6, we can actually make the above code work.

**Comment by rahulmutt** [comment]
This unfortunately is not possible without breaking the class hierarchy we have setup which is actually quite useful (a class for the type and all the data constructors subclasses from that type). The best we can do if we *really* need this is using reflection to access the fields.

**Comment by carymrobbins** [comment]
Yes, I was afraid that this would be a limitation of the JVM itself. Unless some new instruction allows for casting one class to another, we can't really convert a `Bar` to a `Spam`, and I don't foresee this being supported anytime soon.

**Comment by rahulmutt** [comment]
Not exactly a limitation of the JVM, but how we chose to encode 
```haskell
data Greeting = Hello | Hi Int
```

This is generated as:
```java
public abstract class GreetingT extends Value {}

public class HelloD extends GreetingT {}
public class HiD extends GreetingT {}
```
(`Value` is the parent classes of all evaluated data types in Eta, including functions.)

But we just as easily *not* generate these classes at all and could have just used generic, standard classes like below to instantiate an instance of `Hello` or `Hi`:
```java
public class DataCon0 extends Value {}
public class DataCon1 extends Value {}
```

You can use `DataCon0` when instantiating `Hello` or *any* nullary data constructor and `DataCon1` when instantiating `Hi` or *any* data constructor with one boxed argument. You can have a whole range of these standard classes and only use those. And with this code generate style, you can implement this issue.

But the cost? Debugging becomes more painful and we lose type information at runtime. And we lose out on JVM's opportunity to optimise each call-site based on type information.

Right now, I can run VisualVM and know exactly which data types are being allocated frequently, etc., based on the class itself. With the alternative code generation, I lose of all of this.

**Comment by carymrobbins** [comment]
Right, I actually meant it's a limitation _if_ you use this sort of type hierarchy, which doing otherwise would make not only debugging and profiling more difficult, but interop with other languages would become pretty painful as well.
