### ISSUE TITLE
eta: panic! during [ 1 of 15] Compiling Data.Array.Base

### ISSUE THREAD

**Issue by parthopdas** [typelead/eta#426]
### Repro steps
1. On macOS w/ JDK 1.8.0_101 followed [getting-started.html](http://eta-lang.org/docs/html/getting-started.html)
2. During the ./install.sh step I get the following error 

> Configuring array-0.5.2.0...
> Preprocessing library for array-0.5.2.0..
> Building library for array-0.5.2.0..
> [ 1 of 15] Compiling Data.Array.Base  ( Data/Array/Base.hs, dist/build/Data/Array/Base.jar )
> eta: panic! (the 'impossible' happened)
>   (Eta version 0.0.6b7):
> 	tcCheckFIType: Unsupported calling convention.
>   ccall unsafe "memcpy"
> 
> Please report this as a Eta bug: http://github.com/typelead/eta/issues
> 
> etlas: Leaving directory '/var/folders/74/1fq5jhms429flz19rwc19_gr0000gn/T/etlas-tmp-91673/array-0.5.2.0'
> Installed ghc-boot-th-8.0.2
> etlas: Error: some packages failed to install:
> array-0.5.2.0-2RWOOaF5GcW4U6D6pQUKE5 failed during the building phase. The
> exception was:
> ExitFailure 1
> deepseq-1.4.2.0-EXkQ3COXO601OwV0z700UR depends on deepseq-1.4.2.0 which failed
> to install.
> pretty-1.1.3.5-2k15eKcUyWL51YIy6ecc3M depends on pretty-1.1.3.5 which failed
> to install.
> template-haskell-2.11.1.0-IDOBAGt9yBT4ag7xmjhLmA depends on
> template-haskell-2.11.1.0 which failed to install.
> Error when running Shake build system:
> * install
> user error (Development.Shake.cmd, system command failed
> Command: etlas install template-haskell --allow-boot-library-installs
> Exit code: 1
> Stderr:
> etlas: Error: some packages failed to install:
> array-0.5.2.0-2RWOOaF5GcW4U6D6pQUKE5 failed during the building phase. The
> exception was:
> ExitFailure 1
> deepseq-1.4.2.0-EXkQ3COXO601OwV0z700UR depends on deepseq-1.4.2.0 which failed
> to install.
> pretty-1.1.3.5-2k15eKcUyWL51YIy6ecc3M depends on pretty-1.1.3.5 which failed
> to install.
> template-haskell-2.11.1.0-IDOBAGt9yBT4ag7xmjhLmA depends on
> template-haskell-2.11.1.0 which failed to install.
> )

**Comment by rahulmutt** [comment]
Apologise for this! We're currently transitioning over to Eta v0.0.9 and we had to make some breaking changes - we did update the `array` patch so that the changes only apply for the new Eta version, but it looks like there may be more changes to do.

**Comment by rahulmutt** [comment]
Nevermind - it looks like we just need to patch the new version of array. Will respond to this thread once that's fixed.

**Comment by rahulmutt** [comment]
Try running `./cleaninstall.sh` again?

**Comment by parthopdas** [comment]
Thanks compilation succeeded. However I get invalid jar file following these steps.
1. vi HelloWorld.hs
2. Copy paste the following code:
````hs
module HelloWorld  where

main _ = putStrLn "Hello, World!"
````
3. ~/.local/bin/eta HelloWorld.hs (compilation succeeds)
4. java -jar HelloWorld.jar -> **Error: Invalid or corrupt jarfile HelloWorld.jar**
5. I am able to open the jar file using [jd-gui](http://jd.benow.ca/)

PS: I also see a .hi file, what is it?

**Comment by parthopdas** [comment]
Got this to work, @puffnfresh helped out. The module name needs to be Main
