### ISSUE TITLE
Lexical error at '\n'

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#430]
According to @reactormonk, he's getting

```
GHC/Integer.hs:0:2: lexical error at character '\n' on compiling eta
```

This looks mostly like an encoding problem but we'll need to investigate.

**Comment by reactormonk** [comment]
`LC_ALL` is empty

```
╰─╼ env | grep LANG                                                                                                                                                                 ╾─[1]──┄
LANG=en_GB.utf8
LANGUAGE=
```
Archlinux:
```
Linux dynames 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
```

btrfs filesystem with no special settings.

**Comment by rahulmutt** [comment]
I took a look at this: https://wiki.archlinux.org/index.php/locale#LC_ALL:_troubleshooting

According to the examples shown, it seems that your `LANG` should actually be `en_GB.UTF-8`. I wonder if that missing `-` is causing problems!

**Comment by rahulmutt** [comment]
To test that you can set `LC_ALL=en_GB.UTF-8` in a terminal session and run `./cleaninstall.sh` after that.

**Comment by reactormonk** [comment]
Same error. I should probably see if I package the problem into a VM.

**Comment by rahulmutt** [comment]
Can you try setting `LANG=C` in a terminal session and running `./cleaninstall.sh`? 

And by the way, have you tried the binary installation?

**Comment by rahulmutt** [comment]
Works meaning you're able to compile and run Eta programs now? I can add this to the docs if so.

**Comment by reactormonk** [comment]
... it somehow only ever works the first time, afterwards, I get the error. Not sure if it's connected to not specifying `LANG=C` at some point.

**Comment by rahulmutt** [comment]
Not clear on what's going on - so it works the first time you run `./cleaninstall.sh` and future times the build fails with the error above?

**Comment by reactormonk** [comment]
Exactly.

**Comment by rahulmutt** [comment]
Are you doing `LANG=C` every time or just the first time? You'll need to export it to your environment whenever you work with eta programs for now. We should probably remove the locale-dependent bits in the compiler so it works regardless of locale.

**Comment by reactormonk** [comment]
It may be that not adding `LANG=C` somehow poisons the build, but I'm not 100% sure.

**Comment by reactormonk** [comment]
It may be that not adding `LANG=C` somehow poisons the build, but I'm not 100% sure.

**Comment by NickSeagull** [comment]
Somehow I cannot reproduce this, do you still get the same error nowadays @reactormonk ?

**Comment by reactormonk** [comment]
Running `./cleaninstall.sh` now works.

**Comment by NickSeagull** [comment]
Sounds great! Feel free to reopen if it appears again 😄
