### ISSUE TITLE
Putting "require-sandbox: True" in ~/.etlas/config breaks etlas

### ISSUE THREAD

**Issue by dysinger** [typelead/eta#441]
There's probably lots of stuff like this still. Just making a note.

**Comment by rahulmutt** [comment]
Thanks for the report! Can you be more specific on what breaks?

**Comment by rahulmutt** [comment]
We are pushing towards using `new-build` because it's a more space-efficient solution than sandboxes and we will deprecate the sandboxing mechanism in the future.
