### ISSUE TITLE
Exception on using `interact`: undefined

### ISSUE THREAD

**Issue by yawaramin** [typelead/eta#449]
Minimal code to repro:

```haskell
-- Main.hs
main :: IO ()
main = interact id
```

Compile above and run with: `etlas run <Main.hs` (input can be anything)

Output:

```
Exception in thread "main" eta.runtime.exception.EtaException: Prelude.undefined
...
at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Hi @yawaramin, apologies for the delay! We have recently implemented File I/O in the standard library. Please try source installing from `master` to make the above program work.

**Comment by yawaramin** [comment]
Thanks Rahul, I'm getting an error when trying to build from `master` following the instructions in http://eta-lang.org/docs/html/getting-started.html#installation :

```
...
# eta (for install)
Error when running Shake build system:
* install
Pattern match failure in do expression at Build.hs:121:3-18
```

Should I file an issue?

**Comment by rahulmutt** [comment]
Yes definitely. Share your platform details as well (i.e. os, arch, etc). That specific message seems to indicate that your `~/.eta/0.0.9.2/package-conf.d` is empty - can you verify that it is the case?

**Comment by yawaramin** [comment]
Thanks, I'll file a full issue soon, but it seems I have something in that directory:

```
$ file ~/.eta/0.0.9.2/package.conf.d/package.cache 
/Users/yamin1/.eta/0.0.9.2/package.conf.d/package.cache: data
```

**Comment by rahulmutt** [comment]
Closing this issue since it's been resolved.

@yawaramin, gentle reminder - try again and please file a new issue regarding the build if it still happens. Thanks!

**Comment by rahulmutt** [comment]
Closing this as it's now tracked on #483
