### ISSUE TITLE
Compiler fails due to "Data.Text.last: empty input"

### ISSUE THREAD

**Issue by carymrobbins** [typelead/eta#453]
This source file is producing a strange build error - https://github.com/carymrobbins/whombot/blob/b42cbc0f93fc90b8a03012c6ebbb7336f0a9f483/src/Main.hs

```
% etlas build
Preprocessing executable 'whombot' for whombot-0.1.0.0..
Building executable 'whombot' for whombot-0.1.0.0..
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/whombot/whombot-tmp/Main.jar )

<no location info>: Data.Text.last: empty input
```

**Comment by rahulmutt** [comment]
Just grepped the codebase and it's really only used in 2 places in `codec-jvm`. Testing out which one is the culprit. Will submit a patch soon.

**Comment by rahulmutt** [comment]
This should be fixed on master now - try it again?

**Comment by carymrobbins** [comment]
Fixed, thanks!
