### ISSUE TITLE
eta: panic! (the 'impossible' happened)         InvalidAbsFile "..

### ISSUE THREAD

**Issue by agocorona** [typelead/eta#454]
when there is a  -i option that has references the parent directory ".." : 

```
tests# eta  -i../src Test.hs
[1 of 7] Compiling Transient.Internals ( ../src/Transient/Internals.hs, ../src/Transient/Internals.jar ) [flags changed]
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.9b2):
        InvalidAbsFile "../src/Transient/Internals.jar"
```

**Comment by rahulmutt** [comment]
Thanks for reporting this. It looks like an error when the jar file is being assembled at the very last step. The relevant module is `ETA.Util.JAR` probably in the calls to `parseAbsFile`. I'm not satisfied with how it is being done right now. Probably the best solution is the make every path absolute and then do `parseAbsFile`. Would you be interested in submitting a patch?

**Comment by agocorona** [comment]
Yes I will  try to look at it.
