### ISSUE TITLE
Runpath/of/the/file.jar: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by agocorona** [typelead/eta#455]
the compiler tries to add "Run"  and ".jar"  prefix and suffix  to the name of the source file, but also when the source file has a path, uses the whole path as name:

```
 eta -isrc tests/Test.hs
[1 of 7] Compiling Transient.Internals ( src/Transient/Internals.hs, src/Transient/Internals.jar ) [flags changed]
Linking Runtests/Test.jar ...
Runtests/Test.jar: openFile: does not exist (No such file or directory)
```

**Comment by rahulmutt** [comment]
Relevant bit is here:
https://github.com/typelead/eta/blob/master/compiler/ETA/Main/GhcMake.hs#L445

I think I assumed that `name'` was just the file name and not the entire path. Will require a bit of extra file path manipulation to make sure it's just the file name that's changed.
