### ISSUE TITLE
stack traces produced by multithreading

### ISSUE THREAD

**Issue by agocorona** [typelead/eta#457]
This program  should create a new thread that print a message:

```haskell
import Transient.Base

main=  keep' $  do
    r <- async $ return "hello"
    liftIO $ print r
```

it prints the correct output, but also a stack trace:

```
"hello"
***Exception***: Prelude.undefined
    in base.ghc.Err$error
    in base.ghc.Err$undefined
    in transient.transient.Internals$$Lr295ZZlvl20
    in transient.transient.Internals$ds5_s2ASJ
    in transient.transient.Internals$free_$sa
    in transient.transient.Internals$a45_s2DIR
    in transient.transient.Internals$sat_s2DM8
    in transient.transient.Internals$sat_s2DM9
```

Avoiding the creation of the new thread with `threads 0` , it does not produce any error:

``` haskell
import Transient.Base

 keep' $  threads 0 $ do
    r <- async $ return "hello"
    liftIO $ print r
```

This other also produces clean results:

``` haskell
import Transient.Base
import Transient.Indeterminism

 keep' $  threads 0 $ do
    r <- choose [1..10]
    liftIO $ print r
```

without `threads 0` This latter program print the ten numbers, each one produced by a thread. and also produces stack traces

**Comment by rahulmutt** [comment]
I've updated `master` with a lot more implemented functions and replacing all the uses of `undefined` with proper error messages. After the change, there are no longer exceptions, but I do notice that it hangs after doing the core work of the program. Checking with VisualVM, I found that it's stuck on `takeMVar` which seems to have deadlocked - I assume you rely on the runtime unblocking this by throwing an exception as in #451?

**Comment by agocorona** [comment]
suddenly all these errors dissapeared  Thank you. You can close it.  I only see very ocassionally a differnt kind of error at most once in each try with 100 threads. 10 is ok, Admittedly they are a lot of threads:

```haskell
main=  keep' $  do
    r <- choose [1..100::Int]
    liftIO $ print r
```

```
95
94
97
98
99
96
***Exception***: JException java.lang.NullPointerException
    in main.transient.Internals$ds12_sRHK
    in main.transient.Internals$sat_sRK3
    in base.ghc.Base$bindIO1
    in base.ghc.Base$bindIO1
    in base.ghc.Base$bindIO1
    in base.ghc.Base$thenIO1
    in base.ghc.Base$bindIO1
    in base.ghc.conc.Sync$sat_sESFL
```

**Comment by rahulmutt** [comment]
I also have some ideas as to why deadlocking is happening. The Eta RTS uses a small thread pool and has a global run queue of TSOs (forkIO'd threads) and it may happen that when you fork a large number of threads, there might be some TSOs that are blocked from execution and which might are reposible for the putMVar calls that aren't happening, hence deadlocking. To confirm this, I'll configure the RTS to use a unbounded thread pool and see if that fixes the problem, and figure out ways to make it work with a bounded thread pool (by inspecting a closure and looking for references to MVars, etc).

Those NPEs look interesting, I'll keep this open until those are resolved.

**Comment by rahulmutt** [comment]
@agocorona I fixed a bug in STM recently and that seems to have fixed the exceptions all together. It still hangs once the program is done, but I think it has to do with the deadlocking problem? The fix is on master, so please pull the latest image.

**Comment by rahulmutt** [comment]
Turns out it was hanging because it was waiting on the MVar indefinitely - added some simple deadlock detection in the runtime for MVars.
