### ISSUE TITLE
Change the naming for datacons/tycons

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#458]
```haskell
module Hello.World where

data Greeting = Hi Int
```

We want to create data of type `Hi` from the Java side:

```java
import static hello.World.*;
import static ghc_prim.ghc.Types.*;

...
// Equivalent to (in Eta): Hi 21
GreetingT g = new HiD(new IzhD(21));
```

After the proposed change:

```java
import hello.world.datacons.Hi;
import hello.world.tycons.Hi;
import ghc_prim.ghc.types.datacons.Izh;
...
Greeting g = new Hi(new Izh(32));
...
```

Basically, remove the awkward `D`'s (for data constructors) and `T`'s for type constructors to make it more pleasant to work with on the Java/Scala/Clojure side.

Thoughts on this?

**Comment by puffnfresh** [comment]
What would happen with this one?

```haskell
data Hi = Hi Int
```

**Comment by rahulmutt** [comment]
@jneira Any comments on this?

**Comment by jneira** [comment]
nothing important to say: i agree it is cleaner without them
