### ISSUE TITLE
[eta-tour]: Bug - Something Shown in the Bottom of Page

### ISSUE THREAD

**Issue by wisn** [typelead/eta#469]
![screenshot from 2017-08-23 21-29-43](https://user-images.githubusercontent.com/8147926/29621255-66ef6164-884a-11e7-86f4-0ecc2f9192b6.png)

I'm using arrow key and scrolling down the page. In the bottom of page, I saw something "unfinished".

**Comment by rahulmutt** [comment]
Thanks for reporting this! If possible, can you share your screen resolution/size of your viewing window in your browser?

**Comment by rahulmutt** [comment]
I've deployed the fix to this - can you do a hard reload and try again?

**Comment by wisn** [comment]
![screenshot from 2017-08-24 11-42-07](https://user-images.githubusercontent.com/8147926/29649899-801f5f64-88c1-11e7-8d4a-24f0a9447a9f.png)

Well, it is better. But, at least, can you use the same color like this?

![screenshot from 2017-08-24 11-44-28](https://user-images.githubusercontent.com/8147926/29649913-9e0e01e2-88c1-11e7-9807-4befe5ee430a.png)

**Comment by wisn** [comment]
@rahulmutt The resolution is 1336x768
