### ISSUE TITLE
[eta-tour] Misleading tooltip on navigation arrows (low priority)

### ISSUE THREAD

**Issue by jdeisenberg** [typelead/eta#470]
The previous page / next page arrows at the upper left of the screen both say "Reset" as their tooltip.

**Comment by rahulmutt** [comment]
Thanks for reporting this! We'll look into it.

**Comment by rahulmutt** [comment]
Implemented this - will be visible on the next deployment tonight. We will include you in a credits list for your valuable feedback. Thanks for your time!
