### ISSUE TITLE
[eta-tour] List generator confusion

### ISSUE THREAD

**Issue by cranst0n** [typelead/eta#471]
Playing around on the tour and I can't understand why the following code:

```eta
  print $ [1,2,3,4,5]
  print $ [1..5]
  print $ last [1,2,3,4,5]
  print $ last [1..5]
```

results in the following output:

```eta
[1,2,3,4,5]
[1,2,3,4,5]
5
6
```

Shouldn't the last value be `5`?

**Comment by rahulmutt** [comment]
Hi @cranst0n, 

Yes, the last value should certainly be 5. It looks like a bug, thanks for reporting your observation!

**Comment by rahulmutt** [comment]
I am unable to reproduce this on a local eta installation but I am able to reproduce on the Tour, so it looks like an issue with the Tour's eta installation. I'll redeploy it tonight and see if that helps. 

Same as #476.

**Comment by rahulmutt** [comment]
Tracked down what causes it, temporarily disabled optimisation on the Tour to avoid incorrect results. See #478.
