### ISSUE TITLE
[eta-tour]: The buttons only work if you click on the icon, not the circle.

### ISSUE THREAD

**Issue by joehillen** [typelead/eta#473]
I think it's expected behaviour to click on the circle and not just the icon inside the circle to have it act as a button.

I think typical way to do this is instead of this:

```html
<div class="run-button">
  <a title="Run Program">
    <i class="fa fa-play" aria-hidden="true"></i>
  </a>
</div>
```

do this (put the `a` around the `div`):
```html
<a title="Run Program">
  <div class="run-button">
    <i class="fa fa-play" aria-hidden="true"></i>
  </div>
</a>
```
with some css changes.

It's an easy fix, and I'd do it myself and send a PR if you had the source published.

**Comment by rahulmutt** [comment]
Implemented this - will be visible on the next deployment tonight. We will include you in a credits list for your valuable feedback. Thanks for your time!
