### ISSUE TITLE
[eta-tour]: Bug - [description-here]

### ISSUE THREAD

**Issue by gcsolaroli** [typelead/eta#476]
I can not understand the value '11' returned by the call to 'last [1 .. 10]'. :(

----------
Source Code:
```haskell
list1 = [1 .. 10]
list2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

main = do
  print $ compare list1 list2
  print $ last list1
  print $ last list2
  print $ compare list1 [1 .. 10]
  print $ last [1 .. 10] -- 11 ???
  print $ last [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Output:
```shell
> etlas run
EQ
10
10
EQ
11
10

**Comment by rahulmutt** [comment]
This looks like a bug in the compiler - will investigate this. Thanks!

**Comment by rahulmutt** [comment]
I just tried this locally and I am unable to reproduce this.

**Comment by rahulmutt** [comment]
But I am able to reproduce it on the Tour, so it looks like an issue with `eta`

**Comment by rahulmutt** [comment]
Tracked down what causes it, temporarily disabled optimisation on the Tour to avoid incorrect results. See #478.
