### ISSUE TITLE
[eta-tour] Tour issues

### ISSUE THREAD

**Issue by trepidacious** [typelead/eta#485]
I've been working through the tour - very informative :) I've got a few typos and bits that seem confusing, I'm new to Haskell so it might just be me. Note these might not be in page order, sorry! The last one is probably the only one where the content seems to be wrong rather than just a typo or a suggestion about explanations.

### Hello Name! 1/5
Would make more sense to have the explanation of navigation on the first page, since you need to guess that you should press the top left `->` arrow to get to the second page that explains what it does :)

### Bindings (4/14)
When I got here I wondered what was up with the `$` - I've always wondered about this in Haskell code but never managed to look it up, luckily you explain it later! Might be worth adding something here to point out that the reader shouldn't worry about exact syntax for the whole example, unfamiliar parts will be explained later. Actually this might be best covered with a comment like `- Prints out the bindings - syntax explained later!`

### Types (8/14)
Might be good to have a note on roughly what `add` is, and that there is more on functions and currying later?

### Arithmetic Operations (11/14)
`will be discuss in a` -> `will be discussed in a`

### List Operations (13/14)
`so it just a list` -> `so it is just a list`

### Functions - Introduction (1/7)
Maybe describe the `\` thing?

### Functions - Composition (3/7)
This is only right for 2 functions?

> that the right-most function operates first, followed by the left-most function

Maybe instead:

> that the right-most function operates first, then the function to its left, and so on to the left-most function

### Shapeshifting Functions (3/7) 
```
-- You can also write it more simply:
-- transformList :: List a -> List b
```
I think this should be the following (which does compile and run):
```
transformList :: (a -> b) -> List a -> List b
```
In the description this could be:
> The keyword and variable list are not required and are often omitted since the meaning is clear.

**Comment by rahulmutt** [comment]
Very informative feedback, thanks! Will add these changes in the next iteration.

**Comment by rahulmutt** [comment]
Implemented every bit of feedback - will be visible on the next deployment tonight. We will include you in a credits list for your extremely valuable feedback. Thanks for your time!

**Comment by trepidacious** [comment]
You're very welcome :)
