### ISSUE TITLE
Make sure built script forces Java 1.7 options to javac

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#516]
The `shake/Build.hs` build script should pass etlas options `-optjava=“-source 1.7 -target 1.7”` because the eta compiler doesn't really use Java 8 features yet and it helps out the people trying to use Eta for Android.

**Comment by dgaw** [comment]
Just experimenting with this. I've added the following in **bold** to the buildLibrary function in shake/Build.hs:

buildLibrary :: Bool -> (String -> String) -> String -> [String] -> Action ()
buildLibrary debug binPathArg lib _deps = do
  let dir = library lib
      installFlags = ["--allow-boot-library-installs"]
                  ++ nonNullString (binPathArg "../../")
      configureFlags = if debug
                          then ["--enable-optimization=0"
                                ,"--eta-options=-ddump-to-file -ddump-stg -dumpdir=dump"]
                          else ["--enable-optimization=2"
                                ,**"--eta-options=-optjavac=\\"-source 1.7 -target 1.7\\""]**

No luck though, the libraries are still compiled to java 1.8. Any suggestions?

**Comment by rahulmutt** [comment]
Yes, that's in the right direction. Also add a `-v3` flag into the mix and watch out for the call to `javac` - it should display all the arguments that it passed. If it didn't, let me know.

**Comment by dgaw** [comment]
Thanks. I got most of the libs to compile to java 1.7 but a few still get compiled to 1.8. Specifically the following ones:

./eta/integer/Utils.class
  major version: 52
./eta/base/Utils.class
  major version: 52
./eta/base/HSIConv.class
  major version: 52

Are these some special cases?

**Comment by puffnfresh** [comment]
Those are referenced via the "java-sources" Cabal field. I guess etlas doesn't use eta-options for that. We might not be able to reuse eta-options and might need a more specific flag instead.

**Comment by jneira** [comment]
maybe with etlas `--javac-option(s)`?

**Comment by rahulmutt** [comment]
It turns out that the value of `opt-javac` was getting added to the wrong part of the `javac` options (at the end after the source file) so it wasn't taking effect. The `eta` compiler now forcefully sends the options `-source 1.7 -target 1.7` which can be overrided with `opt-javac` if desired.

**Comment by rahulmutt** [comment]
I'll be cutting the `0.0.9b2` release shortly which will have binaries with the correct versions.

**Comment by rahulmutt** [comment]
The `0.0.9b2` binary release is available now and this should be fixed. Let me know if it works.
