### ISSUE TITLE
Optimise the Wadler space leak at runtime

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#517]
GHC does an optimisation in the GC that will evaluate selector thunks (thunks that just pick out a single field of a product type) to avoid space leaks and Eta doesn't do it yet.

Example of selector thunk:

```haskell
let x = case p of (a,_) -> a
```

A straight forward solution to this is to store a global list of weak references to selector thunks + their product type:

```java
Set<WeakReference<Thunk>,WeakReference<Thunk>> globalSelectorThunks;
```
And in `Capability.blockedLoop()` which is called periodically, iterate through this set and perform the optimisation. Remove elements that are not needed anymore.

**Comment by rahulmutt** [comment]
On top of the above runtime changes, we should also implement GHC Trac #2607: https://ghc.haskell.org/trac/ghc/ticket/2607

which can boost performance via releasing unnecessary references early.

**Comment by puffnfresh** [comment]
What's the performance improvement of 4619f63?

**Comment by rahulmutt** [comment]
Can't quantify, but memory usage can be cut down drastically where it becomes a bottleneck (heavy use of state monads and any type of monad that returns a boxed tuple) so the performance you gain is from reduction of load on the GC. Selector thunks are pretty common and have a tendency to build long indirect thunk chains. The optimization I included frees overwrites the selector thunk and shorts out the indirections as well.

Thunk clearing though caused a drastic jump - test `selectorThunks01` went from 60s -> 36s locally on my system after re-enabling it. @jneira observed a drop in peak mem usage from > 2G to ~ 750MB while running the `dhall-eta`. I'm currently working on further increasing the performance of thunk clearing by generating specialized code to do clearing as opposed to reflection as it is done now.

**Comment by nomeata** [comment]
I am also curious about some hard evidence of how important the selector thunk optimization is.

So, are the `dhall` improvements due to selector thunks, or is this “thunk clearing” you refer to something else?
