### ISSUE TITLE
Error trying to build

### ISSUE THREAD

**Issue by rpeszek** [typelead/eta#519]
I get this when trying stack build or stack install eta:
```
   /.../eta/compiler/ETA/CodeGen/Monad.hs:394:3:
        Not in scope: ‘mkClassFileWithAttrs’
    
    /.../eta/compiler/ETA/CodeGen/Monad.hs:397:32:
        Not in scope: ‘mkSourceFileAttr’
        Perhaps you meant ‘sourceFileAttr’ (line 397)
```
And in fact I cannot find mkClassFileWithAttrs defined anywhere, I am finding mkClassFile only.  

I am on OS-X Sierra. 
I just done pull and git revision is 83f8fb2b1d0b0ebaf63f33ed78faa3140e353f7d

The change is 16 days old so I am puzzled what am I missing.

**Comment by puffnfresh** [comment]
You probably have an old version of the submodules. Run this:

```
git submodule update --init
```

**Comment by rpeszek** [comment]
Oops, I just noticed that too.  Thanks!
```
git submodule update --init --recursive
```
done it for me.  Sorry.
