### ISSUE TITLE
[eta-tour]: Bug in sample code - Modules (2/14)

### ISSUE THREAD

**Issue by ErikCupal** [typelead/eta#528]
The module name should be capitalized (`Main` instead of `main`).

Source Code:
```haskell
module main where

main :: IO ()
main = putStrLn "Erik Cupal's first module!"
```

Expected output:
```shell
Erik Cupal's first module!
```

Actual output:
```shell
Main.eta:1:8: parse error on input ‘main’
```

**Comment by rahulmutt** [comment]
This is not a bug. This is part of the tour - making mistakes in the code so that you can fix them. The description on the left should've given you an idea of how to fix it!

**Comment by ErikCupal** [comment]
Oh, I get it :D. Sorry for spam.

**Comment by rahulmutt** [comment]
No worries! It's better to report a potential bug than not.
