### ISSUE TITLE
binary download links are broken

### ISSUE THREAD

**Issue by xmonader** [typelead/eta#569]
Links here are broken http://eta-lang.org/docs/html/getting-started.html#method-1-binary-installation

```
wget http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.1.0.0/binaries/x86_64-linux/etlas
--2017-11-29 09:42:46--  http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.1.0.0/binaries/x86_64-linux/etlas
Resolving 88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com... 95.101.72.201, 95.101.72.216, 2600:1417:3::5f64:aa58, ...
Connecting to 88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com|95.101.72.201|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-11-29 09:42:47--  (try: 2)  http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.1.0.0/binaries/x86_64-linux/etlas
Connecting to 88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com|95.101.72.201|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-11-29 09:42:49--  (try: 3)  http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.1.0.0/binaries/x86_64-linux/etlas
Connecting to 88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com|95.101.72.201|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.


```

**Comment by rahulmutt** [comment]
I was able to download it via a browser successfully. Perhaps you need to download using https or maybe you are behind some firewall?

**Comment by xmonader** [comment]
@rahulmutt  Sadly I can't from browser i get connection resetted. I live in Egypt maybe that's the problem. Can you please provide another mirror, archlinux package or maybe add bin releases to github?

**Comment by rahulmutt** [comment]
I can look into adding bin releases to github. We'll need someone to volunteer to build a package for archlinux.

**Comment by rahulmutt** [comment]
For now you can do source installation - I recall we have many arch users who've built successfully from source.

**Comment by xmonader** [comment]
I just got so disappointed of having stack on my machine which is prerequisite and thought Eta maybe a good solution, haskell compatible with less tooling size :(

**Comment by rahulmutt** [comment]
You can actually build this with cabal if you wish. Stack just makes the builds reproducible, but I'm sure cabal will work just as fine. I'd be happy to help if you face any issues making it build with cabal.

**Comment by xmonader** [comment]
Thank you so much! Feel free to close this issue ^_^

**Comment by rahulmutt** [comment]
Great, thanks! Closing.
