### ISSUE TITLE
Migrate runtime options to properties

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#577]
In the JVM world, it's natural and convenient to configure an application through a properties file. The Eta runtime system is currently configurable either through:

1. Passing `+RTS [rts flags] -RTS` to command line arguments. This was taken from GHC but it doesn't make much sense on the JVM and is a bit awkward.

2. Calling functions in `Eta.Runtime` which can help you configure some parameters dynamically.

Instead, it would be a lot simpler to make the only configuration method properties since they can be configured both statically and dynamically via existing mechanisms (properties file + Java APIs for handling properties).

**Comment by Jyothsnasrinivas** [comment]
Closing this one since it's implemented with #682.
