### ISSUE TITLE
[etlas] Automatically fix broken packages

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [typelead/eta#581]
When package A depends on package B and you reinstall package B, package A will now be broken. We should have a mechanism to (1) store *how* the package was installed (either locally or through a package server) (2) reinstall all broken packages in topologically sorted order. 

This will be extremely helpful when fixing bugs in packages that are deep in the dependency chain.

**Comment by rahulmutt** [comment]
With the `new-build` mechanism (which is now default in etlas-1.3.0.0), this is no longer an issue.
