### ISSUE TITLE
[etlas] Incorrect classpath to package library in the package executable launch script

### ISSUE THREAD

**Issue by jneira** [typelead/eta#582]
When you install a package which has a library and a executable, the launch script of the latter seems to have a incorrect path for its lib when you executes the global copy in `$ETLAS_DIR/bin` (f.e. with `etlas exec exec-name` instead `etlas run`)
The nix script generated contains:
```shell
$ETA_JAVA_CMD $JAVA_ARGS $JAVA_OPTS $ETA_JAVA_ARGS -classpath "$DIR\wai-servlet-jetty-example.jar;$DIR/../HSwai-servlet-handler-jetty-0.1.0.0-DMCQsc8EeUMHtnbzY4tt1c.jar;other_deps;$ETA_CLASSPATH" eta.main "$@"
```
The package lib jar (`HSwai-servlet-handler-jetty-0.1.0.0-DMCQsc8EeUMHtnbzY4tt1c.jar`) is not there for the script copied in $ETLAS_DIR/bin (although it works for the script placed in `$project/dist/...` )
Same for windows in the MANIFEST.MF of the launcher.jar

**Comment by jneira** [comment]
I think we could change the path of the lib to point to the etlas database in the nix script or windows launcher.jar in the dist dir of the project to copy that version to etlas/bin, when doing `etlas install` . 
Cause each `etlas build` or `install` regenerates de dist dir it would point alway to the correct version of the lib (the project local copy with `build` and the global lib with `install`).
Do you know what data in the LocalBuildInfo or ComponentLocalBuildInfo tells us if the command is build or install?

**Comment by rahulmutt** [comment]
At what point in the execution do you need to determine whether it's a build or install?

**Comment by jneira** [comment]
I think the ideal point would be the [`libPaths` subexpression of `getDependencyClassPaths` function](https://github.com/typelead/etlas/blob/master/etlas-cabal/Distribution/Simple/Eta.hs#L638-L645) in Eta.hs

**Comment by jneira** [comment]
As commented with @rahulmutt, i am exploring the possible solution of generating a special script/jar launcher in the install phase with the correct classpath an copy them to ~/etlas/bin instead of the launchers generated in the build phase.
The current wip version is in the [fix-global-exec branch of my etlas fork](https://github.com/typelead/etlas/compare/master...jneira:fix-global-exec?expand=1)

**Comment by jneira** [comment]
Finally i got a initial working version that handles the three possibles types of library dir
* relative: used by `Distibution.Simple.ETA.buildExe` 
  * the path is `$DIR/../libName.jar`
* absolute and local (the project dir): used by `etlas deps` 
  * the path is `path-to-project/dist/build/libName.jar`
* absolute and global: used by `Distibution.Simple.ETA.installExe` 
  * the path is `~/etlas/eta-version/libName/libName.jar`

I've put examples of the launchers for windows and nix in the [eta-test project](https://github.com/jneira/eta-test/tree/master/test-data)

**Comment by jneira** [comment]
Testing the changes we've detected that when you do an `etlas configure --enable-uberjar-mode`, the next `etlas build`s honours it when generating the classpath for launchers files. The classpath only includes the uberjar.
However `etlas install` ignores the configuration and generates the files with an incorrect classpath: it includes the full one. As the install phase always call the build phase, it generates incorrectly the launchers of both, replacing the correct ones generated by `etlas build` .
It seems it is the designed behaviour in cabal (and etlas) cause you can pass the `--enable-uberjar-mode` in the `etlas install` call and then it uses it and generates correctly the classpath.
The solution could be change the install phase to make it read the configuration written by `etlas configure` in `./dist/etlas-config-flags` and use from it the value of `uberjar-mode` setting (and its alias `executable-dynamic`)

**Comment by rahulmutt** [comment]
I wonder if this is just a bug in `etlas`. I think we should verify first that in `cabal`, the configure flags are indeed ignore for the `install` command.

**Comment by jneira** [comment]
You are right, i've done a test (somewhat incomplete but i think is valid):
- `cabal configure --enable-executable-dynamic & cabal build` : i get an error:  `Perhaps you haven't installed the "dyn" libraries for package base-4.9.0.0`
- `cabal clean & cabal configure --enable-executable-dynamic & cabal install`: the executable is built and installed succesfully
  - after that if i do a `cabal build` i dont get the error (and the `dist/setup-config` file has changed)
- `cabal clean & cabal install --enable-executable-dynamic`: i get the same error as above.. `Peharps..`
- `cabal clean & cabal build --enable-executable-dynamic`: i get the error : `cabal: unrecognized 'build' option '--enable-executable-dynamic'`

I think cabal is able to recreate the executable (making it dynamic or static) between phases, although the project has not source changes that triggers a ghc compile. 
Etlas in the install phase call eta but if there arent source changes (or --fforce-recompile flag) the jar is not recreated by eta. However etlas recreates the script/jar launchers and then we have the inconsistence between the (uber)jar and the classpath of the launchers. Does that conclusion make sense?

**Comment by jneira** [comment]
So other option could be force eta to recompile the jar in the install phase if we detect that the config value for uberjar-mode is different between the last `etlas build` and the actual `etlas install`. The behaviour would be more similar to cabal in this way.

**Comment by jneira** [comment]
I have to note that the tests has been done with cabal version  1.24.0.2 and maybe the behaviour has changed in 2.*

**Comment by rahulmutt** [comment]
The test should ideally be done in 2.* since `etlas` is based on that.

**Comment by jneira** [comment]
Yeah, i've tested it with version 2.0.0.1 and update the relevant comments (the behaviour has not changed)

**Comment by jneira** [comment]
Commenting with @rahulmutt about the issue we tought that maybe the best option to regenerate the executable jar could be make eta relinking the sources when the input files other than modules or packages (taht is, java sources and lib jars) changed. That is a feature in its own, tracked in #594.

**Comment by jneira** [comment]
I turns out that java sources are included in the executable jar in the compiler phase of eta. At this point we need eta to do a "relinking" cause the difference between the uberjar and normal modes is about the maven/modules jars included by etlas in its call to eta. Java sources are included in the executable jar in both modes.
So I filed a new issue about: #609

**Comment by jneira** [comment]
* Global classpath fixed by https://github.com/typelead/etlas/pull/28
* Recreation of jar file when switching between uberjar and normal modes by #622
