### ISSUE TITLE
[etlas] Allow Nix to provide packages

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#583]
The usual way Nix provides packages to the Cabal library is by setting `GHC_PACKAGE_PATH`. We need something similar for the Etlas library.

We also need Etlas to not download patches or sources itself. We should be able to tell Etlas where the patches and sources exist for a package.

**Comment by rahulmutt** [comment]
1) You can do something similar with `etlas` as follows:

```
`etlas --package-db=clear --package-db=[location-of-package-db] ...
```

Those flags should be available for the `etlas install` command.

2) This will require a couple of steps:

- Create `eta-hackage` as a nix binding and lock it down to a commit of `eta-hackage`. It should essentially copy the `patches` directory into the nix store.

- Download the tarball for the package you want directly (for Hackage). For packages in `etlas-index`, you can specify a git repo/tag.

- Using the previous defined `eta-hackage` binding, add some logic to check if `[pkgname]-[version].patch` exists in the store, and if so, apply the patch via 

`git apply --ignore-space-change --ignore-whitespace [path-to-patch]`

- When installing you may also want to specify a location in the nix store to install a package.

`etlas install --package-db=clear --package-db=PACKAGE_DB --libdir=LIBDIR --libsubdir=LIBSUBDIR --bindir=BINDIR`

- `PACKAGE_DB` is the absolute path to the package database you're installing to.
- `LIBDIR` is the absolute path to the root location of the libraries you're going to install (most likely `/nix/store` in this case.)
- `LIBSUBDIR` is a relative path to `LIBDIR` which your library will be installed to. (most likely `[package-name]-[nix-hash]` in this case.)
- `BINDIR` is the absolute path to the directory in which to install the executable
(in most cases there won't be any).

**Comment by rahulmutt** [comment]
And some details on building the boot libraries:
- `rts` package needs to be installed as follows:
  1. Build all the `*.java` files under `rts/src` with the following flags:
     `javac -XDignore.symbol.file -Xlint:unchecked -source 1.7 -target 1.7 [files]`
   2. Combine the class files generated above into a jar and send it to `libraries/rts/build/HSrts.jar`
   3. Run `etlas install --allow-boot-library-installs ...` in the `libraries/rts` folder.
- `ghc-prim`, `integer`, `base` all should be built by going into the respective directories and running `etlas install --allow-boot-library-installs ...`. Again you can use the extra flags above to customize the local to which they're installed.

**Comment by puffnfresh** [comment]
I'll write the code using the existing Shake code. I'll refactor anything which isn't exposed.

The first problem I'm running into is the prompt:

> Would you like to help us make Eta the fastest growing programming language, and help pure functional programming become mainstream? (y/n)

Nix isn't giving it stdio, therefore it crashes with:

```
<stdin>: hGetChar: end of file
```

**Comment by puffnfresh** [comment]
Got past that problem with https://github.com/typelead/etlas/pull/26

**Comment by puffnfresh** [comment]
I have to pass `--disable-auto-update` to Etlas, otherwise it tries to download the index via git and fails.

**Comment by puffnfresh** [comment]
I did an install of ghc-prim but it doesn't expose GHC.Prim - I see that the Shake build has [`fixGhcPrimConf`](https://github.com/typelead/eta/blob/master/shake/Build.hs#L110) but it doesn't seem to be used anywhere.

**Comment by rahulmutt** [comment]
You can update the Etlas config at `~/.etlas/config` and set `auto-update` to True.

Hmm well the CI is somehow passing even without that. @jneira discovered that GHC.Prim was being exported twice and removed the `fixGHCPrimConf`. Are you getting errors when building `integer`?

**Comment by puffnfresh** [comment]
Etlas puts GHC.Prim into the exposed modules by looking at the unit-id. I'm using "etlas register" on the .cabal file, which doesn't read the ghc-options to execute the unit-id hack.

I've written a dodgy awk script to work around this for now.

**Comment by rahulmutt** [comment]
So updating `etlas register` to handle this should keep all this ad-hoc logic inside of etlas right?

**Comment by puffnfresh** [comment]
@rahulmutt yeah that's right

**Comment by rahulmutt** [comment]
Does your nix overlays work satisfy this issue? What else is remaining on that front?

**Comment by puffnfresh** [comment]
Yeah it does pretty much what you said in the second comment.
