### ISSUE TITLE
[etlas] etlas build with modified base requirements

### ISSUE THREAD

**Issue by hvze** [typelead/eta#584]
I began with my project [Refract](https://github.com/hvze/Refract) and tried to use `etlas build` with it, but it spat this back out at me.

```
阴霾 Haskell/Refraction ‹master*› » etlas build
Resolving dependencies...
Configuring Refraction-0.1.0.0...
Preprocessing library for Refraction-0.1.0.0..
Building library for Refraction-0.1.0.0..
etlas: HSbase-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF.jar doesn't exist
```

**Comment by rahulmutt** [comment]
It looks like your installation is broken.

Can you share the output of

```
etlas list --installed --simple
```

**Comment by rahulmutt** [comment]
@hvze You mentioned on Gitter that cleaning out `~/.eta` and `~/.etlas` fixed your problem so I'm closing this.
