### ISSUE TITLE
Backpack Support

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#589]
We already have a good chunk of code to support Backpack in both the Eta compiler and the Etlas build tool. We can backport the remaining code and enable Backpack in Eta since the stable version of Backpack is out.

**Comment by NickSeagull** [comment]
+1 To this, I'm very excited with Backpack, and for creating implementations of signatures using bindings to Java libraries, it would be very useful. :smile:

**Comment by Jyothsnasrinivas** [comment]
Closing this one since it's implemented on 593bad1c9f7ebfca10f233f40474ea7203d1cada
