### ISSUE TITLE
NullPointerException from show and text pack

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#592]
I get a NullPointerException with the following:

```haskell
import Data.Monoid
import Data.Text

main :: IO ()
main =
  print $ "test" <> pack (show 4)
```

**Comment by rahulmutt** [comment]
Seems related to #541 and #564 as well as the current blocking bug in eta-ffi.

All the examples share on thing in common: using the `text` package which eventually generates a case-of-case expression in STG [1] in which the scrutinee expression contains let-no-escape bindings. 

This bug fix is the highest priority right now and should be fixed soon.



[1] This should ideally be optimized, but we can't do it without breaking join points until we backport the join points changes from GHC 8.

**Comment by rahulmutt** [comment]
This turned out to be a bug in how `codec-jvm` detects & removes redundant goto instructions. Fixed on `master`.
