### ISSUE TITLE
Different behaviour of program with "etlas run"  and with "java -jar RunProgram.jar"

### ISSUE THREAD

**Issue by agocorona** [typelead/eta#593]
Running this code : https://gist.github.com/agocorona/e138f02ec34e4adfa1f82249dc748bf2

with `etlas run` produces:
```text
root@ec3dfec39c7c:/fiber# etlas run
Preprocessing executable 'fibers' for fibers-0.1.0.0..
Building executable 'fibers' for fibers-0.1.0.0..
Running fibers...
"hello"
"hello"
"hello"
"hello"
"world"
"world"
"world"
"world"
"world2"
"world2"
"world2"
```
and stop. it should not stop and it should not switch from thread to thread since it does not use yield and it uses one single capability

but   with `eta src/Fibes-new.hs &&   java -jar  src/RunFibers-new.jar `  produces the expected behaviour

**Comment by rahulmutt** [comment]
By default `etlas` builds with `-O2` enabled. 

Can you try `eta -O2 src/Fibes-new.hs && java -jar src/RunFibers-new.jar` and see if that matches `etlas run`?

**Comment by rahulmutt** [comment]
@agocorona I think this is resolved, so I'm closing this. Feel free to re-open if you face the same issue again.
