### ISSUE TITLE
[etlas] Recompilation checking for java source files

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#594]
If you change the Java sources listed in the `java-sources:` field, `etlas` will not rebuild the new file since it doesn't do any checking for that at the moment. It should be changed so that it does.

**Comment by jneira** [comment]
The change could be compute the input files hashes, saving them and compare the possible new input files in subsequent calls to trigger either a compile or only a linking if modules had not been changed and is possible.
This can be done in etlas at first but at some point the compiler could be changed so it will have this behaviour.

**Comment by jneira** [comment]
* With #622 eta makes a new jar if java sources change
