### ISSUE TITLE
Failed to install binary-0.8.5.1: Cannot parse #if directive

### ISSUE THREAD

**Issue by phanimahesh** [typelead/eta#595]
Trying to compile https://github.com/simonmichael/hledger/tree/master/hledger-lib with eta, using gradle

### `build.gradle`
```
buildscript {
  repositories {
    mavenLocal()

    dependencies {
      classpath 'com.typelead:gradle-eta:0.0.1-SNAPSHOT'
    }
  }
}

apply plugin: 'eta'

eta {
    etlasVersion = '1.1.0.0'
}
```

And got:
```
Found patch in eta-hackage for binary-0.8.5.1
Configuring binary-0.8.5.1...
Building data-default-instances-containers-0.0.1...
Building mtl-2.2.1...
Building pretty-show-1.6.15...
Building binary-0.8.5.1...
Failed to install binary-0.8.5.1
Build log ( $PROJECTS/hledger/hledger-lib/.cabal-sandbox/logs/eta-0.0.9.6/binary-0.8.5.1-XCulyUW0jLDfM8QjWWONO.log ):
etlas: Entering directory '/tmp/etlas-tmp-20990/binary-0.8.5.1'
Configuring binary-0.8.5.1...
Preprocessing library for binary-0.8.5.1..
Building library for binary-0.8.5.1..
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.9b6):
	Cannot parse #if directive in file src/Data/Binary/Get/Internal.hs  at line 64 col 1:
    end of input

Please report this as a Eta bug: http://github.com/typelead/eta/issues
```

I have no idea what's happening, just following the instructions. :P 

Trying to compile hledger-lib to use it in an android project for something, got this far and got stuck. I thought a patch is missing and may be needed, but no, a patch exists. What's happening here? What can I try now?

**Comment by rahulmutt** [comment]
Sorry about that, there's a mistake in the patch that only gets executed on the older versions of Eta. I fixed the patch. Start the project from scratch and try again.

**Comment by phanimahesh** [comment]
binary compiles fine, but there are other dependencies that still need patching. Should I open patch requests on eta-hackage? I can try to write the patches myself but will probably need some initial handholding.

**Comment by rahulmutt** [comment]
Sure, go ahead. I'm closing this issue since it's solved.
