### ISSUE TITLE
Installation of attoparsec fails

### ISSUE THREAD

**Issue by hardliner66** [typelead/eta#597]
I tried to install aeson, which depends on attoparsec.

But the installation of attoparsec failed with the following output:
```
Preprocessing library for attoparsec-0.13.2.0..
Building library for attoparsec-0.13.2.0..
eta.exe: panic! (the 'impossible' happened)
  (Eta version 0.0.9b6):
        Cannot parse #if directive in file ./Data/Attoparsec/ByteString/Lazy.hs  at line 58 col 1:
    end of input
```

**Comment by rahulmutt** [comment]
Just pushed a fix. Run `etlas update` and try installing `attoparsec` again. Everything should work fine.

**Comment by hardliner66** [comment]
That was fast.

I tried to run etlas update but it failed:
```
etlas update
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
Updating binary package index.
dieVerbatim: user error (etlas: Failed to download
http://objects-us-west-1.dream.io/hackage-mirror/01-index.tar.gz : No Status
Code could be parsed from response: Ausnahmefehler während einer
WebClient-Anforderung.
)
```

**Comment by rahulmutt** [comment]
Looks like some server issue. You can update just the patches manually:

```shell
cd ~/.etlas/patches
git pull
```
Then try installing again.

**Comment by rahulmutt** [comment]
Filed #598 to add a flag to `etlas update` that can update just the patches.

**Comment by hardliner66** [comment]
I reinstalled eta and it worked.

but etlas update still doesn't work. Maybe there is a problem with the update command.

**Comment by rahulmutt** [comment]
It looks like an issue with the Hackage package index download and we don't have control over that. Try it again over the after a while (say hours, maybe even tomorrow) and let us know if it's still giving you the same error.

**Comment by hardliner66** [comment]
I will retry some other day. Thanks.
