### ISSUE TITLE
Random runtime exceptions due to MemoryManager

### ISSUE THREAD

**Issue by hardliner66** [typelead/eta#599]
OS: Windows 10 x64
JDK: 1.8.0_144

While trying out some stuff with eta, I got the following exception:
`Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.RuntimeException: java.lang.IllegalStateException: getBoundedBuffer#0: The block that corresponds to the address 8096 is not allocated in memory`

I ran etlas run again and everything worked again.

After that I tried to reproduce the exception and wrote a batch script, which executed the jar file 100 times and logged the output.

2 of the 100 runs failed with an exception.
1)
`Exception in thread "main" eta.runtime.exception.EtaException: <stdout>: commitBuffer: failed`
2)
`Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.RuntimeException: java.lang.IllegalStateException: getBoundedBuffer#0: The block that corresponds to the address 4294965272 is not allocated in memory`

This is the project I used to reproduce this behaviour:
[eta-first_random_bug.zip](https://github.com/typelead/eta/files/1597804/eta-first_random_bug.zip)

The log file is located in logs/output_jar.txt

This behaviour is reproducible with `etlas run` (no uberjar) and with `java -jar eta-first.jar` (uberjar)

**Comment by rahulmutt** [comment]
Thanks for the report!

This bug has been around for a while and it has to do with Eta's Memory Manager which handles off-heap memory.

This is actually our highest priority right now and work is being done on the `managed-heap` branch. The main implementation was finished yesterday and we are currently resolving some bugs that occur in very special cases. As soon as it stabilizes, we'll cut a release.

I just realized that there's no open issue that tracks these related bugs we'll make this issue track that.

**Comment by rahulmutt** [comment]
@hardliner66 Just did a binary release for Eta v0.7 which should have the fix above. Please test it out and close this issue if it's fixed.

**Comment by hardliner66** [comment]
It works now. I let it run 1000 times and it didn't crash once.
