### ISSUE TITLE
"Cannot parse #if directive" while installing dependencies

### ISSUE THREAD

**Issue by joshsh** [typelead/eta#606]
I get a strange failure message when attempting to install a dependency via `etlas`, version 1.1.0.0. See below. The dependency version in question is already available via `cabal`.

Steps to reproduce:
* use `etlas init` to create a minimal executable project with the default `Main.hs`
* at this point, a 19 MB uber-jar can be successfully created using `etlas configure --enable-uberjar-mode` and `etlas build`
* in the *.cabal file, add a dependency, e.g. `  build-depends:       base >=4.8 && <4.9, parsec >= 3.1 && < 3.2` -- after first installing the dependency via `cabal` and checking the version, e.g. `cabal install parsec`.
* at this point, issuing `etlas configure --enable-uberjar-mode` yields an error message about a missing dependency, which suggests running `etlas install --dependencies-only`
* running `etlas install --dependencies-only` fails as follows

```
$ etlas install --dependencies-only
Resolving dependencies...
Found patch in eta-hackage for binary-0.8.5.1
Configuring binary-0.8.5.1...
Building binary-0.8.5.1...
Failed to install binary-0.8.5.1
Build log ( /Users/joshsh/.etlas/logs/eta-0.0.9.6/binary-0.8.5.1-XCulyUW0jLDfM8QjWWONO.log ):
etlas: Entering directory '/var/folders/21/6bv0ggqs4_gbd8y69dbzjfy00000gn/T/etlas-tmp-37317/binary-0.8.5.1'
Configuring binary-0.8.5.1...
Preprocessing library for binary-0.8.5.1..
Building library for binary-0.8.5.1..
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.9b6):
	Cannot parse #if directive in file src/Data/Binary/Get/Internal.hs  at line 64 col 1:
    end of input

Please report this as a Eta bug: http://github.com/typelead/eta/issues

etlas: Leaving directory '/var/folders/21/6bv0ggqs4_gbd8y69dbzjfy00000gn/T/etlas-tmp-37317/binary-0.8.5.1'
etlas: Error: some packages failed to install:
binary-0.8.5.1-XCulyUW0jLDfM8QjWWONO failed during the building phase. The
exception was:
ExitFailure 1
parsec-3.1.11-6oyvVDJqwG5KD8OdgTkffr depends on parsec-3.1.11 which failed to
install.
text-1.2.2.2-F2cHT27bZB4JWqGrmupXOq depends on text-1.2.2.2 which failed to
install.
```

**Comment by rahulmutt** [comment]
Do you still get this error after running `etlas update`? I recently fixed the `binary` patch. Another alternative is to upgrade to Eta v0.7 with `etlas select latest`.

**Comment by joshsh** [comment]
Thank you; running `etlas update` solved the problem.
