### ISSUE TITLE
[etlas] etlas test missing dependencies error message

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [typelead/eta#608]
According to @indegro, etlas gives this error message when running `etlas test` with missing dependencies: 

`etlas: Encountered missing dependencies: HUnit -any, hspec >=1.3, mockery -any, temporary -any Run 'etlas install --dependencies-only' to install the dependencies.`

It should suggest to add the `--enable-tests` flag.

**Comment by jneira** [comment]
Last version of etlas with the new build system is not affected by that.
