### ISSUE TITLE
Trigger the linker phase when linked files other than modules change 

### ISSUE THREAD

**Issue by jneira** [typelead/eta#609]
Actually eta does not regenerate the main jar if the jars included as input files to be linked change. 
If you do a `etlas --make Module.hs module-dep.jar` and later `module-dep.jar` changes, a second call doesn't generate a new run-module.jar with those changes. This is so even if you add or remove jars from the call.
A full build including compile would not be neccesary, only a new linking.

**Comment by jneira** [comment]
The change could be modify the [ETA.Main.DriverPipeline.linkingNeeded](https://github.com/typelead/eta/blob/master/compiler/ETA/Main/DriverPipeline.hs#L1280-L1304) to take in account all the files involved in the link phase. 
Actually [ghc](https://github.com/ghc/ghc/blob/ghc-7.10/compiler/main/DriverPipeline.hs#L435-L467) check if linking is needed:
- checking if any of object files or extra_ld_inputs are newer than the last executable
- doing a similar check for the included haskell libraries
- saving in the executable the call to linker to [compare it to next calls and trigger the link phase if they don't match](https://github.com/ghc/ghc/blob/ghc-7.10/compiler/main/DriverPipeline.hs#L471-L486).

A posiible solution for eta could be save the linked info with all files involved in the final jar (f.e. in a file called .link-info in the root). 
This info could be a line for each file linked with the name and a hash. In each call to eta, it would build that info and compare it with the last one, triggering the link if they don't match.
The hash of each file could be a checksum of the file content or a hashed string with the full path, modification time and size.

As `__extras.jar` with the java sources is one of those files we could use its hash to trigger the compile and link of java sources when they change, as required in the issue #594.

**Comment by rahulmutt** [comment]
I like this solution a lot better and as you said, it'll fix a lot of problems at once.

**Comment by jneira** [comment]
Closed by #622
