### ISSUE TITLE
RFC: Require keyword

### ISSUE THREAD

**Issue by NickSeagull** [typelead/eta#612]
A lot of the times we find ourselves writing code like:

```haskell
import qualified Data.Text as Text
import Data.Text (Text)
```

Maybe it would be possible to write a `require` keyword that joins these two by importing unqualified all the types and the rest qualified? The `as` part would default to the last part of the module name:

```haskell
require Data.Text    -- Imported as Text
require Data.Vector  -- Imported as Vector
```

If someone had trouble with colliding types, one could write:

```haskell
require Data.ByteString hiding (ByteString)
require Data.ByteString.Lazy hiding (ByteString) as LazyByteString
```

This way would make the code much cleaner in my opinion, while having backwards compatibility.

```haskell
require Data.Text
require Data.Vector

foo :: Text -> Vector Int
foo = Vector.map length 
    . Vector.fromList
    . Text.unpack
```

Looking forward for opinions :smile:

**Comment by rahulmutt** [comment]
I've wanted this exact functionality myself, but I'm wary of adding new syntax when it can be avoided. For foreign import/foreign export syntax, we have freedom to change it however we like (as mentioned in your previous RFC).

I feel like this will be less of a problem once we have the IDE support ready. Basically, I imagine having a tool that automatically generates *exact* imports for you and it would be integrated into the IDE that will run as a preprocessing step before building.

I recall there was a ticket about this on [GHC Trac](https://ghc.haskell.org/trac/ghc/ticket/10478) though I don't think it includes automatically qualifying the last bit of the module name which is really nice to have.

**Comment by NickSeagull** [comment]
I see, makes sense to me, it was a crazy idea I had and I wanted to propose it :smile: 

Looking forward for IDE support!
