### ISSUE TITLE
[eta-tour]: Bug - Modules (2/14) - Invalid module name declaration

### ISSUE THREAD

**Issue by pzmi** [typelead/eta#613]
I should really pay attention to descriptions...

Source Code:
```haskell
module main where

main :: IO ()
main = putStrLn "pzmi's first module!"
```

Output:
```shell
Main.eta:1:8: parse error on input ‘main’
```

Hi.
Shouldn't module name start with capital letter? In this example module name is `main` and this snipped does not compile.
When changed to `Main`, it's ok.

**Comment by rahulmutt** [comment]
Hi @pzmi, the error is intentional and meant for you to fix. It's part of the tour :)

**Comment by pzmi** [comment]
It's even in the description, now I feel dumb. I should really read the description before starting :)

**Comment by rahulmutt** [comment]
No worries. It happens! Closing, since this is resolved.
