### ISSUE TITLE
eta-fib-service sample repo empty

### ISSUE THREAD

**Issue by FrankTaylorLieder** [typelead/eta#618]
Following the first web service tutorial at: https://eta-lang.org/docs/eta-tutorials/web-services/the-api

I found the following:

refrain:eta$ git clone https://github.com/typelead/eta-fib-service
Cloning into 'eta-fib-service'...
warning: You appear to have cloned an empty repository.

**Comment by rahulmutt** [comment]
Thanks for catching that! Try again - it should work.
