### ISSUE TITLE
eta panic building library for crypto-api-0.13.2

### ISSUE THREAD

**Issue by mfussenegger** [typelead/eta#619]
```
[ 1 of 11] Compiling Crypto.Util      ( Crypto/Util.hs, dist/build/Crypto/Util.jar )
eta: panic! (the 'impossible' happened)
  (Eta version 0.7.0b1):
	tcCheckFIType: Unsupported calling convention.
  ccall unsafe "value c_constTimeEq"

Please report this as a Eta bug: http://github.com/typelead/eta/issues
```

Occurred after adding `wreq` to a projects dependencies.

**Comment by rahulmutt** [comment]
Hello @mfussenegger! Thanks for the report. There happens to be a C FFI call in `crypto-api` that implements a secure equals function for hashes. I have successfully replaced that with a Java implementation locally but for some reason the hs-boot files in the library are not compiling. Will need to take a deeper look.

**Comment by rahulmutt** [comment]
The patch for `crypto-api-0.13.2` is now available.
