### ISSUE TITLE
[etlas] curl: (7) Failed to connect to metrics.eta-lang.org port 80: Timed out

### ISSUE THREAD

**Issue by jcolivo** [typelead/eta#621]
Hello!
I am trying to install/update etlas and eta according to the instructions at:
https://eta-lang.org/docs/eta-concepts/getting-started/install-eta

Howerver, I am encountering a time out when the Etlas is connecting to metrics.eta-lang.org. Below is the command line input and output from a Windows 10 machine. 

Thank you for your help!

---------------------------------------------------------------------------------------------------------

C:\Users\jc>etlas update
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
Updating binary package index.
To revert to previous state run:
    etlas update --index-state='2018-01-24T13:48:17Z'
Updating the eta-hackage patch set.
etlas: 'C:\ProgramData\chocolatey\bin\curl.exe' exited with an error:
curl: (7) Failed to connect to metrics.eta-lang.org port 80: Timed out

**Comment by jcolivo** [comment]
Also, below is the output when I enter the command: curl --version.
---------------------------------------------------------------
C:\Users\jc>curl --version
curl 7.57.0 (x86_64-pc-win32) libcurl/7.57.0 OpenSSL/1.1.0g (WinSSL) zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.28.0
Release-Date: 2017-11-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL

**Comment by rahulmutt** [comment]
The telemetry server is going to be down for a couple days - you can turn it off for now and I'll update this issue when it's back up. 

Ideally, `etlas` shouldn't fail even if the telemetry server is down, so this should be considered a bug.

Check the instructions here:
https://eta-lang.org/docs/faq#opt-out-eta-telemetry

**Comment by jcolivo** [comment]
Thank you very much!
I followed the instructions, and it seems that the command **etlas update** ran perfectly fine. 

Now, I have another obstacle:
When I try to run the command: **eta Main.hs** I get the following error:

C:\Users\jc\Desktop>etlas exec eta -- Main.hs
[1 of 1] Compiling Main             ( Main.hs, Main.jar )
Linking ./RunMain.jar ...

C:\Users\jc\Desktop>eta Main.hs
'eta' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rahulmutt** [comment]
@jcolivo `eta` is not installed globally so it makes sense that `eta Main.hs` doesn't work. `etlas` managed `eta` versioning for you making it easier to upgrade `eta` whenever you have time. If it mentions anywhere in the docs that you should run that command, please let us know and we'll fix it.

**Comment by jcolivo** [comment]
Thank you for your response. 
I stepped away from my computer for a break, and when I came back, the tutorial did mention that `eta Main.hs` was the same as `etlas exec data -- Main.hs`. I am sorry that I overlooked that sentence, but am glad to know that those two commands do the same thing. This is a newbie mistake: not reading thoroughly. 

Another newbie question (thank you for your patience!)
I was able to compile Main.hs using both. When I run `java -jar RunMain.jar` I get the following message (the last line is the output from the Main.hs program shown in the getting started tutorial https://eta-lang.org/docs/eta-concepts/getting-started/first-program). What could be causing the warnings? Thank you for your help!

C:\Users\jc\Desktop>java -jar RunMain.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by eta.runtime.Runtime (file:/C:/Users/jc/Desktop/RunMain.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of eta.runtime.Runtime
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
The 101st prime is 547

**Comment by rahulmutt** [comment]
By chance are you using Java 9?

**Comment by jcolivo** [comment]
Yes. Here is the output from the command line:

C:\Users\jc\Desktop>java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by rahulmutt** [comment]
Ok for now, you can just ignore the warnings and keep working. We'll eventually fix those warnings.

**Comment by jcolivo** [comment]
Will do. Thank you!

**Comment by rahulmutt** [comment]
I filed #623 and #624 to address the bugs that were found in this issue. The telemetry server is now back up and you can turn it back on with these instructions: https://eta-lang.org/docs/faq#opt-in-eta-telemetry.
