### ISSUE TITLE
[eta-tour]: Bug -- compilation broken in Firefox

### ISSUE THREAD

**Issue by marcin-kozinski** [typelead/eta#627]
Source Code:
```haskell
main :: IO ()
main = putStrLn "Hello World!"
```

Output:
```shell
Error[error]:
```

I'm using Firefox 60 (currently in the Nightly channel) on macOS 10.13.3.

**Comment by rahulmutt** [comment]
Thank you for catching this @marcin-kozinski! We just fixed this, can you do a hard reload and try again?

**Comment by marcin-kozinski** [comment]
Nice 👍 Can confirm it's working now!
