### ISSUE TITLE
ping: cannot resolve etlas.typelead.com: Unknown host

### ISSUE THREAD

**Issue by chenyong** [typelead/eta#632]
Got this domain in:

```
=>> etlas update
Welcome to Etlas, the awesome build tool for the Eta programming language!

We are working hard to make the best platform for pure functional programming
on the Java Virtual Machine.

Etlas will periodically send usage statistics to help us:

* Make decisions on how to evolve the language

* Build a community portal that displays the data we collect in visual form

* Build an Etlas package repository that will accurately display package popularity

* And more!

For more details, please consult our privacy policy:

        http://eta-lang.org/docs/html/privacy-policy.html

Would you like to help us make Eta the fastest growing programming language,
and help pure functional programming become mainstream? (y/n)

Y
Thank you for trying out Eta.

If you face any issues, you can:

* File an issue at:
      https://github.com/typelead/eta/issues/new

* Post your question on Eta-Discuss:
      https://groups.google.com/forum/#!newtopic/eta-discuss

* Ask on the Gitter channel:
      https://gitter.im/typelead/eta

Config file path source is default config file.
Config file /Users/chen/.etlas/config not found.
Writing default configuration to /Users/chen/.etlas/config
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com           <----------------------- here
```

Update took very long time. I doubted it server is down:

```
=>> ping etlas.typelead.com
ping: cannot resolve etlas.typelead.com: Unknown host
```

**Comment by rahulmutt** [comment]
Hi @chenyong, can you run `etlas update -v3` and share the trace in a Gist? 

`etlas.typelead.com` doesn't exist (yet) and is currently backed by a [Git repository](https://github.com/typelead/etlas-index), although the message doesn't tell you (which it should). Moreover, the message doesn't indicate order. Both indexes are queried in parallel and often, the Hackage query takes a long time since the index it's downloading can be up to 400MB.

**Comment by chenyong** [comment]
https://gist.github.com/chenyong/5a3106b9fb71f9581eef6e90a6beddf4

**Comment by chenyong** [comment]
Besides:

```
=>> eta
-bash: eta: command not found
=>> etlas
etlas: no command given (try --help)
```

not sure what happened but it's not like what's told in docs.

**Comment by rahulmutt** [comment]
Which steps in the docs are you following? It looks like the trace shows that the update happened successfully.

**Comment by chenyong** [comment]
I tried twice(or 3 times), and made it work. Just curious why that domain is printed and why it's slow. If that's expected to be slow, please show an progress bar.

I installed with binary on Mac https://eta-lang.org/docs/eta-concepts/getting-started/install-eta

```
chmod +x /path/to/etlas
etlas update
etlas select latest
```

Should `eta` be available after these steps?

**Comment by rahulmutt** [comment]
Read the next section: https://eta-lang.org/docs/eta-concepts/getting-started/first-program

It explains that `eta` is managed by `etlas` to allow you to switch versions easily and shows you how you can access the `eta` compiler directly if you need it via `etlas exec`.

**Comment by rahulmutt** [comment]
Filed #633 to track that we need to add progress bars.

**Comment by chenyong** [comment]
Thanks. So the issue is just why `etlas.typelead.com` is printed given that it doesn't exist anymore. No actual problems left.

**Comment by rahulmutt** [comment]
@chenyong Thanks! Filed #634 and #635 to address all the issues mentioned in this post. Closing this since everything else was resolved.
