### ISSUE TITLE
Not able to install eta from binary on Windows

### ISSUE THREAD

**Issue by duester** [typelead/eta#637]
Hello all! I'm a newbie to eta and trying to install it on Windows 7. Unfortunately, it fails. After downloading the executable and doing 'etlas update' I get an error: "Unable to find base package base-4.8.2.0 in binary package index"
[etlas_update.log](https://github.com/typelead/eta/files/1689128/etlas_update.log)

After cleaning out the directory %APPDATA%\Roaming\etlas and running 'etlas update -v3' the error is still present:
[etlas_update_full.log](https://github.com/typelead/eta/files/1689136/etlas_update_full.log)

Is there something I'm missing? Thanks for help.

Max

**Comment by duester** [comment]
Thanks for your tip! The result of these commands is nearly the same:
[etlas_select.log](https://github.com/typelead/eta/files/1689564/etlas_select.log)
[etlas_select_full.log](https://github.com/typelead/eta/files/1689565/etlas_select_full.log)

**Comment by rahulmutt** [comment]
Can you download the new [etlas-1.2.0.0 binary](https://cdnverify.eta-lang.org/eta-binaries/etlas-1.2.0.0/binaries/x86_64-windows/etlas.exe) and clean out your `Roaming\etlas` and see if the new binary works out for you? We're just about to complete an infrastructure migration and the failure you see above may be related to it. The new version of etlas has a patch to support the peculiarities of the new infrastructure.

**Comment by duester** [comment]
Ok, I'll try this.

**Comment by duester** [comment]
Alas, the latest binary does not bring anything new:
[etlas_select_full.log](https://github.com/typelead/eta/files/1690009/etlas_select_full.log).  Hmm, what can else be the issue?

**Comment by rahulmutt** [comment]
Can you try `etlas select -v3 0.7.0b2` and see if that works? We recently re-deployed `0.7.0b1` because of some errors and it may be that the Content Delivery Network is caching the invalidated files.

**Comment by duester** [comment]
Sorry, could not try it out yesterday. Just ran it again. It still fails, always because of not finding base-4.8.2.0. ;-(    I wonder if someone else experience the same issue.

**Comment by duester** [comment]
Ok, I found out that it only does not work on my workplace PC. On my home PC it works! So now I have to investigate what is different on the other computer. Thanks for helping!

**Comment by rahulmutt** [comment]
@duester Thanks for the info! Given the fact that it wasn't working on your work computer which typically have secure network setups, I wonder if `base-4.8.2.0-bin.tar.gz` is being blacklisted for some reason. It contains a large jar file inside - about 17MB in side so I wonder if that has anything to do with it. We may need to add an option to etlas to download files in chunks for certain networks.

The error log you submitted unfortunately is not giving information on the exact failure so what I'll do is update etlas to add proper debug messages on failed requests so we can see exactly what's going on.

**Comment by duester** [comment]
Ok, let me know as soon as you have updated the installer. I would be glad to test it and so to help fix this download issue.

**Comment by jneira** [comment]
Let's close this one, feel free to reopen if the bug persists with last version of etlas/eta
