### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#641]
The code in [this repo](https://github.com/rahulmutt/eta-bug/tree/eta-641) fails to parse the JSON even though it's valid.

**Comment by betterclever** [comment]
Working on this.

**Comment by rahulmutt** [comment]
@betterclever Sounds great. There are several mechanisms available to debug code generated by Eta, so let me know if you need me to share that info.

**Comment by rahulmutt** [comment]
@betterclever It looks like @jneira beat you to it by fixing an unrelated bug that also happened to fix this with #654. Closing this issue.
