### ISSUE TITLE
Make tailCallThreshold configurable

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#661]
The current threshold for trampoline bouncing is a constant at around 30 which means every 30 tail calls it’ll rewind. This number is quite low, but at the same time we can't assign a constant for *all* applications, so it should be configurable.

We want to move towards a property-based configuration mechanism so this should be exposed as a property: `eta.rts.tailCallThreshold`.

https://github.com/typelead/eta/blob/master/rts/src/main/java/eta/runtime/stg/Stg.java#L69-L72

**Comment by puffnfresh** [comment]
30 seems really really really low. I think GHCJS used something like 10k or 100k when it first got trampolining. I can't figure out what it currently is but that seems closer to the right default.

**Comment by rahulmutt** [comment]
Sure. That number was just from Odersky's paper on tail calls with exceptions that I linked on the TCO for CPS programs issue and I haven't given it much of a thought since the focus at the time was just making sure the stack doesn't blow up with CPS'd parsers (like `aeson`, `binary`, etc).

It would be awesome if someone did experiments with CPS'd parsers and came up with a nice number to set as a default. The first step would be implementing this issue and setting up benchmarks which vary the `tailCallThreshold`.

My only concern with making the number too big is that the GC time will increase with higher thresholds. If the JIT is smart enough to realize all those local variable references on the stack won't be used, then it won't be a issue, but again, we should do some experiments and verify.

**Comment by rahulmutt** [comment]
I should also be clear that the 30 tail call limit only applies after using the `trampoline` function from `Data.Function`. It's an opt-in runtime TCO which will trigger new codepaths that count the number of tail calls once the function is used.

**Comment by njayinthehouse** [comment]
Ping! Can I have some starting tips on this one?

**Comment by rahulmutt** [comment]
Sure. So you'll need to add some code in `eta.runtime.Runtime` that stores the `taillCallThreshold` and initializes the value by reading the System properties, see [here](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html) for an overview of properties in Java.

**Comment by rahulmutt** [comment]
@njayinthehouse With the work @ouromoros has done, in #682, the changes required to implement this is quite simple. Add a new runtime integer property called `tailCallThreshold` and make sure to read from that in the `eta.runtime.stg.Closure`.

**Comment by betterclever** [comment]
@rahulmutt Read in eta.runtime.stg.Stg right? I don't see it being used in Closure class.

**Comment by betterclever** [comment]
@rahulmutt Read in eta.runtime.stg.Stg right? I don't see it being used in Closure class.

**Comment by rahulmutt** [comment]
@betterclever Yes you are right!

**Comment by rahulmutt** [comment]
@puffnfresh I've changed the threshold to 10k as you suggested. Here's a basic estimate that shows why it's a reasonable number:

Stack size in bytes: 2^20 (1024KB)
We want to consume at most half of the stack in the worst case to avoid being on the edge of a stackoverflow, hence, the available stack space is:

2^20/2 = 2^19

Now let's assume that each stack frame takes 50 bytes on average - (amounts to 6 longs or 12 ints) which is fairly reasonable.

2^19 / 50 =~ 10,500

**Comment by puffnfresh** [comment]
Awesome stuff @rahulmutt. Performance is much better with that?

**Comment by rahulmutt** [comment]
Haven't checked yet, it would be great if someone can verify.

**Comment by rahulmutt** [comment]
While working on the external interpreter which makes heavy use of the `binary` library, we discovered that 10000 is too lenient of a limit and causes StackOverflowErrors. After some tuning it looks like 1000 is a better default. Only more aggressive use of the trampolining feature can tell us what the *best* default will be.

**Comment by rahulmutt** [comment]
So after lots of usage (using `happy` and `alex` on non-trivial generators) we bumped it down to 400 so that both of those can run without any tuning. We can always bump this number up as we optimize local variable usage (which is directly related to stack size) and as we figure out a general way to break up large compiled methods into small ones.

Closing it as the key issue has been resolved - using `-Deta.rts.tailCallThreshold=[n]` you can configure the threshold to whatever you want.

**Comment by rahulmutt** [comment]
#339 is the issue tracking local variable usage.
