### ISSUE TITLE
Expose runtime configuration as properties

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#662]
The runtime system is quite configurable
https://github.com/typelead/eta/blob/master/rts/src/main/java/eta/runtime/Runtime.java#L16-L158

But we need a better interface. We should read from properties to initialize those values, so that we can do something like

```
java -Deta.rts.maxLocalSparks=50 ...
```

to configure the runtime.

Please list out the property names that you will be selecting before continuing further.

**Comment by ouromoros** [comment]
As I see it, using properties would involve reading a property fiile(probably `~/.etlas/.properties`?). So I think adding a initialization step before running the program would do it.

Snce `getPropertie` returns only String, we would have to parse the return value to the corresponding type for every paramater. I think a helper function is needed for this parsing task or there would be *many* tedious try-catch phrases and the code won't be very extencible.

I think all the paramaters in the referenced lines can be added, or is there something I'm missing? I'll work on it if you think it's fine.

**Comment by rahulmutt** [comment]
The properties file should actually be a resource in the compiled JAR file:
https://www.javaworld.com/article/2077352/java-se/smartly-load-your-properties.html

This is because you would want to configure the Eta runtime in an application-specific manner and not the same way for every application.

We can make a convention that we expect it to be `eta/rts.properties`. So there are two levels of properties here:
1) Properties from the `eta/rts.properties` file that has been added as a *resource*.
2) System properties provided on the command line via `-D` flag.

For a given property, the value specified by 2) should override the value specified by 1).

Go ahead and work on this :) 

I agree that the bulk of the work will be parsing the options. You can create a new class `RuntimeOptions` and put all your parsing code there.

**Comment by rahulmutt** [comment]
@ouromoros Before you waste your time writing parsing utilities, you can use the following methods:
- `Boolean.getBoolean("[property-name]")` for parsing boolean properties,
- `Integer.getInteger("[property-name]")` for parsing integer properties

and so on for all the standard primitive wrapper classes.

**Comment by rahulmutt** [comment]
Disregard my last comment. You still have to parse the properties that are read from the file.

**Comment by rahulmutt** [comment]
Resolves with #682.
