### ISSUE TITLE
An FAQ for Android apps looks wrong

### ISSUE THREAD

**Issue by y-taka-23** [typelead/eta#665]
The FAQ list has "Can I build Android apps in Eta?" section, but the actual contents is for CLR/.NET support. Surely pasted erroneously.

https://eta-lang.org/docs/faq

**Comment by Jyothsnasrinivas** [comment]
Thanks for the catch! We’ll fix this asap.

**Comment by Jyothsnasrinivas** [comment]
Should be fixed now. Thanks again, @y-taka-23! :smile:
