### ISSUE TITLE
Create branches to track stable and latest versions of eta repo

### ISSUE THREAD

**Issue by jneira** [typelead/eta#667]
* Currently [the docs](https://eta-lang.org/docs/eta-concepts/getting-started/install-eta#source-installation) suggests to  "manually" get the versions of latest and stable versions of eta from readme to clone the repo
* However maybe it would be useful to have named tags or branches in addition to the numeric versions to make it even easier cloning the repo, pinning up the git command to `git clone  --branch stable --recursive --depth 1 https://github.com/typelead/eta`
* Although it adds some more maintaining effort those branches/tags (`stable` and `latest`), it could be used in other contexts like ci builds

**Comment by Jyothsnasrinivas** [comment]
I've created the branches `stable` and `latest`. For reference, the command to change the branch pointer is:

```
git branch -f [branch-name] [commit/tag]
```

See https://stackoverflow.com/questions/5471174/move-branch-pointer-to-different-commit-without-checkout.
