### ISSUE TITLE
Check over the use of --shallow-submodules when clonning the eta repo

### ISSUE THREAD

**Issue by jneira** [typelead/eta#668]
* It seems that the use of the `--shallow-submodules` does not clone correctly all the submodules, at least with some versions of git
* As @rajcspsg reported in gitter (and tested by myself), it throws an error: `Server does not allow request for unadvertised object [hash], Fetched in submodule path 'codec-jvm', but it did not contain [hash]`
  * My git version is 2.11.1
* Cloning without the `--shallow-submodules` option works correctly

**Comment by Jyothsnasrinivas** [comment]
I've updated the docs to remove `--shallow-submodules`. Thanks @jneira!
