### ISSUE TITLE
Building shake package causes panic

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#669]
See https://github.com/rahulmutt/eta-bug for reproducing.

The error is:
```
[58 of 58] Compiling Development.Shake.Config ( src/Development/Shake/Config.hs, dist/build/Development/Shake/Config.jar )

<no location info>:
    eta: panic! (the 'impossible' happened)
  (Eta version 0.7.0b2):
	unequal assigmnents

Please report this as a Eta bug: http://github.com/typelead/eta/issues
```
@jarekratajski This panic is coming from your recent multiAssign changes. 

The tail end of `Config.dump-cg-trace`:
```
...
Generating (mutually recursive) readConfigFile_go
StgCase wild_sF1XY Alg HashMap
StgApp ds_sF1XW []
cgIdApp: EnterIt
StgApp z1_sF1XV [eta_sF1XX]
cgIdApp: SlowCall
StgCase sat_sF1Y1 Prim Int#
StgOpApp sizeofSmallArray# [dt1_sF1Y0] Int#
StgApp $s$wgo2_rF1KD [dt1_sF1Y0, sat_sF1Y1, 0, z1_sF1XV, eta_sF1XX]
cgIdApp: JumpToIt
```
So that indicates the problem occurred when generating a call to `$s$wgo2_rF1KD`.

The context from `Config.dump-stg`:
```haskell
...
        case ds_sF1XW of _ [Occ=Dead] {
          Data.HashMap.Base.Empty -> z1_sF1XV eta_sF1XX;
          Data.HashMap.Base.BitmapIndexed _ [Occ=Dead] dt1_sF1Y0 ->
              case sizeofSmallArray# [dt1_sF1Y0] of sat_sF1Y1 {
                __DEFAULT ->
                    $s$wgo2_rF1KD dt1_sF1Y0 sat_sF1Y1 0 z1_sF1XV eta_sF1XX;
              };
...
```

I wonder if there's some assumption we made about multi assignments that's getting invalidated here?

**Comment by jarekratajski** [comment]
I have no idea. I will start analyzing that in ~8  hours from now.

**Comment by jarekratajski** [comment]
One strange thing is I  cannot understand how could **readConfigFile** be recursive.

**Comment by jarekratajski** [comment]
After adding debug I see:
in cgTrace
```
J:cgLocs: [local: False ObjectType (IClassName "eta/runtime/io/Array") 6,
           local: False BaseType JInt 7, local: False BaseType JInt 8,
           local: True ObjectType (IClassName "eta/runtime/stg/Closure") 9]
J:cgLocsL:4 depsL:5  -- this is our problem (unequal number of assigns/codes)
J:argsL:5
J:args: [dt1_sF342, sat_sF343, 0, z1_sF33X, eta_sF33Z]
```
I have no idea how to interpret it, as I still do not see this recursion.
This '0' looks strange.

**Comment by rahulmutt** [comment]
That 0 appears to be an STG Literal value. How do you deal with literals in your algorithm?

**Comment by jarekratajski** [comment]
I used the old code `multiAssign` with same  debug
```
    traceCg (str "cgIdApp: JumpToIt")
      codes <- getNonVoidArgCodes args
      traceCg (str "J:cgLocs:" <+> ppr cgLocs)
      traceCg (str $ "J:cgLocsL:" ++ show ( length cgLocs )  ++ " depsL:" ++ show ( length codes )  )
      traceCg (str $ "J:argsL:" ++ show ( length args ))
      traceCg (str "J:args:" <+> ppr args)
      emit $ multiAssign cgLocs codes
```
It compiles. 
But debug info looks strange to me:
```StgApp $s$wgo2_rF2UD [dt1_sF380, sat_sF381, 0, z1_sF37V, eta_sF37X]
cgIdApp: JumpToIt
J:cgLocs: [local: False ObjectType (IClassName "eta/runtime/io/Array") 6,
           local: False BaseType JInt 7, local: False BaseType JInt 8,
           local: True ObjectType (IClassName "eta/runtime/stg/Closure") 9]
J:cgLocsL:4 depsL:5
J:argsL:5
J:args: [dt1_sF380, sat_sF381, 0, z1_sF37V, eta_sF37X]
```
multiAssign is called with 4 cgLocs and 5 codes.
My (mostly ghc to be honest :-) ) implementation cannot work with that.
Old implementation is such case ignores last "orphaned" codes (zipWith does that).
Is it expected behaviour?

**Comment by rahulmutt** [comment]
Ok so the key here is that `getNonVoidArgCodes` will filter out those arguments who have a type `State# s` which have no representation at runtime. In multiAssign, you should probably filter out the cgLocs which have a void representation.

**Comment by jarekratajski** [comment]
I have a 'fix' that seems to at least not fail. 
Basically in cases of "unbalanced" assignments it works as before (no fail -  last code is simply  ignored).

I will analyze it - the question is if I should simply in case of void remove the exact corresponding cgLoc.
Question is if I  should process with `isVoidRep` pairs StgArg and Code. (not only StgArg as now)?

**Comment by rahulmutt** [comment]
Yes, you should remove the corresponding cgLoc, since void cgLoc's cant be assigned since they dont exist at runtime.

**Comment by jarekratajski** [comment]
Pushed solution that should remove only corresponding cgLoc from the list - not the last ones.
The funny thing is - this does not work at all - fail (VerifyClass error) on simple fibonacci . The previous (naive) solution worked ok.

Maybe I have some stupid bug there - but I do not see it now.

**Comment by rahulmutt** [comment]
The VerifyError above indicates that you're loading a Closure and and trying to assign it to a local variable that stores int. This means there's probably a bug lurking in your algorithm somewhere.

**Comment by JustusAdam** [comment]
I get the same issue. I recently got a very similar `VerifyError` that said

```
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ohua_jvm_integration/clojure/Core.$wwithMeta(Leta/runtime/stg/StgContext;Ljava/lang/Object;Leta/runtime/stg/Closure;)Leta/runtime/stg/Closure; @91: invokeinterface
  Reason:
    Type long_2nd (current frame, stack[5]) is not assignable to 'java/lang/Object'
```

So the first thing I did was update Eta to make sure I wasn't working with an old issue and now the following happenend when compiling the `uniplate` library.

```
Building library for uniplate-1.6.12..
[ 1 of 21] Compiling Data.Generics.Uniplate.Internal.Utils ( Data/Generics/Uniplate/Internal/Utils.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/Uniplate/Internal/Utils.jar )

Data/Generics/Uniplate/Internal/Utils.hs:27:1: Warning:
    Ignoring ANN annotation, because this is a stage-1 compiler or doesn't support GHCi
[ 2 of 21] Compiling Data.Generics.Uniplate.Data.Instances ( Data/Generics/Uniplate/Data/Instances.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/Uniplate/Data/Instances.jar )
[ 3 of 21] Compiling Data.Generics.Uniplate ( Data/Generics/Uniplate.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/Uniplate.jar )
[ 4 of 21] Compiling Data.Generics.UniplateOn ( Data/Generics/UniplateOn.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/UniplateOn.jar )
[ 5 of 21] Compiling Data.Generics.Str ( Data/Generics/Str.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/Str.jar )
[ 6 of 21] Compiling Data.Generics.Uniplate.Internal.Data ( Data/Generics/Uniplate/Internal/Data.hs, dist/dist-sandbox-4e79ce96/build/Data/Generics/Uniplate/Internal/Data.jar )
eta: panic! (the 'impossible' happened)
  (Eta version 0.7.0b2):
	unequal assigmnents

Please report this as a Eta bug: http://github.com/typelead/eta/issues

etlas: Leaving directory '/var/folders/7r/0m95hr6x2l54ykj_4f3qww8w0000gn/T/etlas-tmp-7910/uniplate-1.6.12'
```

I would like to add that previous uniplate *did* compile though I cannot tell you which eta version I was on then. I think maybe it was 0.7.0b1

**Comment by jarekratajski** [comment]
@JustusAdam can You check if it works with my intermadiete fix (pull request here)?
Fix is problemmatic  - because I do not reaaly understand what is happening there - but it should work not worse than the version before my "fix" for #603

**Comment by rahulmutt** [comment]
@jarekratajski I did a quick review of your original code again the core code for `emitMultiAssign` is fine. The problem is here:
https://github.com/typelead/eta/blob/master/compiler/ETA/CodeGen/Expr.hs#L157-L172

Notice that in `dependencies`, you ignore those `StgArg`'s that have a `VoidRep`, but you do not filter out the `cgLocs` accordingly. I think if you rewrote the `dependencies` to take `[(CgLoc, StgArg])` instead, it would fix it.

**Comment by jarekratajski** [comment]
@rahulmutt  I already did as You write  and this does not work.   check this commit:
https://github.com/jarekratajski/eta/commit/dceadce52fdbee3c959586fb3e7913cf102f51be

In original code (before #603  fix) - the coresponding cgloc was not removed...  and unmatched cgLocs were simply ignored.  Current state of pull request reverts to that behavior ( ignoring instead of panic).

**Comment by rahulmutt** [comment]
@JustusAdam Can you try again or provide steps so that we can verify that the fix worked for you?

**Comment by JustusAdam** [comment]
Sure. What eta version/tag/commit should I try?

**Comment by rahulmutt** [comment]
@JustusAdam https://github.com/typelead/eta/commit/061df4af322df5031bbfffd6b6fd6b6288269c50 should contain the fix.

**Comment by JustusAdam** [comment]
I checked out that commit and ran `./install.sh` and I get this build error 

```
Failed to install rts-0.1.0.0
Build log ( /Users/justusadam/.etlas/logs/eta-0.7.0.2/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.log ):
etlas: Entering directory '.'
Configuring rts-0.1.0.0...
Preprocessing library for rts-0.1.0.0..
Building library for rts-0.1.0.0..
eta-pkg: Couldn't open database dist/package.conf.inplace for modification: dist/package.conf.inplace/dist/package.conf.inplace/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.conf: openBinaryFile: does not exist (No such file or directory)
etlas: Leaving directory '.'
etlas: Error: some packages failed to install:
rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w failed during the building phase. The
exception was:
ExitFailure 1
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: etlas install --allow-boot-library-installs
Current directory: /Users/justusadam/projects/eta/libraries/rts
Exit code: 1
Stderr:
etlas: Error: some packages failed to install:
rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w failed during the building phase. The
exception was:
ExitFailure 1
)
```

**Comment by JustusAdam** [comment]
I also tried `./cleaninstall.sh`, same error.

**Comment by rahulmutt** [comment]
@JustusAdam Try doing `etlas select local` before running `./cleaninstall.sh`. The build log shows that you're using an older version of `eta` to build the boot libraries. The `select local` step should happen inside of the `./cleaninstall.sh` itself but there is a minor bug right now that is breaking the build so we've disabled that step for now. Let me see if I can fix it.

**Comment by JustusAdam** [comment]
Since I am now in dependency-resolution hell again I have a question while I try and fix my broken library set:

@rahulmutt, what do you think about adding some way to obtain a `cabal.config` with the `eta-hackage` constraints? Either a command, or add one to the `eta-hacakge` repo. That way I could make sure my project does not use unpatched/incompatible packages?

**Comment by rahulmutt** [comment]
@JustusAdam It should already be done for you - `etlas-index` contains all the constraints:
https://github.com/typelead/etlas-index/blob/master/00-index.tar#L21-L112

But I just realized it doesn't have proper lower bounds so the only issue you might get is if the dependency resolver determines that you need an older version for which there doesn't exist a package.

These are just "preferences" so if you use something like `--allow-newer`, I think the dependency solver will ignore it.

Can you share the exact build issues you're getting?

**Comment by rahulmutt** [comment]
Btw, please file a new issue to discuss this matter since this issue is about something else.
