### ISSUE TITLE
[eta-tour] Wrong current version mentioned in the intro module

### ISSUE THREAD

**Issue by gabejohnson** [typelead/eta#674]
The most recent tag is `v0.7.0b2`. However, the introductory module refers to `v0.0.9b1` in the second paragraph at https://tour.eta-lang.org/start#3

This makes the entire paragraph erroneous.

**Comment by rahulmutt** [comment]
@gabejohnson Thanks for catching this. We've updated the tour so you can see the change with a hard refresh.
