### ISSUE TITLE
Upgrade to base-4.11 

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#688]
`base-4.10` has imported a lot of typeclasses into the standard library (`Semigroup`, `MonadIO`, etc) which are very useful. We should upgrade to it.

**Comment by NickSeagull** [comment]
Whats your opinion on fixing this and #657 together?

**Comment by jneira** [comment]
This upgrade would imply that the default prelude would be the one included with 4.10 (with foldable-traversable and other changes), no?
If so, it would be somewhat related with https://github.com/typelead/eta-proposals/pull/4

**Comment by NickSeagull** [comment]
Yep, definitely. :smile:

**Comment by jneira** [comment]
@rahulmutt what do you think what would be the best approach? i tried to get base-4.10 and build with etlas/eta and i has a lot of features of ghc > 8 (type in type, type parameters, ..). Maybe we should do a list of desired changes and try to backport them to the actual version, but it seems it will suppose a lot of work...

**Comment by rahulmutt** [comment]
I think instead, we should be discussing which changes we will not be able to port and what we should do about it. In most cases we'll probably just have to avoid porting specific changes but in some cases I think they are reasonable alternatives we can provide.

**Comment by jneira** [comment]
I'm trying to adapt base-4.11.0 to eta in this repo: https://github.com/jneira/packages-base.

**Comment by jneira** [comment]
thank to the amazing work of @Jyothsnasrinivas i think that one is fulfilled

**Comment by rahulmutt** [comment]
Indeed it is! Closing.
