### ISSUE TITLE
createDirectoryIfMissing doesn't work (throws unexpected error)

### ISSUE THREAD

**Issue by kemphack** [typelead/eta#689]
`jCreateDirectoryIfMissing dir = io $ createDirectoryIfMissing True (fromJava dir)`

`foreign export java "@static Tools.createDirectoryIfMissing"
    jCreateDirectoryIfMissing :: JString -> Java a ()`

`Tools.createDirectoryIfMissing("./folder");`
does work but 
`Tools.createDirectoryIfMissing("./folder/folder");` 
doesn't: throws error
`Exception in thread "main" eta.runtime.exception.EtaException: JException java.nio.file.NoSuchFileException: folder/folder`

**Comment by NickSeagull** [comment]
Is this the function from `System.Directory`? If so, you should pass `True` as the first parameter so it creates parents. If not, it will throw.

**Comment by kemphack** [comment]
` io $ createDirectoryIfMissing True (fromJava dir)` it throws with True. Yes, it's from System.Directory

**Comment by NickSeagull** [comment]
Could you please add the bytecode and the STG info as described [here](https://github.com/typelead/eta/blob/master/docs/source/eta-user-guide.rst#debugging-stack-traces)? Thanks! 😄

**Comment by kemphack** [comment]
I don't think that bytecode of IOError can be usefull in this case. Something bad happens inside of java realization of createDirectoryIfMissing:
`eta.runtime.exception.EtaException: JException java.nio.file.NoSuchFileException: folder/folder/folder
	at base.system.io.Error.tryIOError2(Error.hs)
	at base.system.io.Error$tryIOError2.apply1V(Error.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:166)
	at directory.system.Directory.$Lr1CS8a2(Directory.hs:350)
	at directory.system.Directory.$Lr1CSAa3(Directory.hs:346)
	at directory.system.Directory.createDirectoryIfMissing1(Directory.hs:341)
`

**Comment by NickSeagull** [comment]
🤔 Can you create a repo with this issue to see if I can try to reproduce?

**Comment by kemphack** [comment]
Here it is https://github.com/kemphack/directoryMissingBug

**Comment by jneira** [comment]
hi! i've check the code of directory and[ it catches an `IOError` to check if it have to create the intermediate folders (sic!)](https://github.com/haskell/directory/blob/master/System/Directory.hs#L335)
As java is throwing a JException instead an IOError the check fails.
As @rahulmutt has suggested maybe we should make a mapping between java io exceptions and IOError to fix all client code calls.

**Comment by jneira** [comment]
@kemphack As a temporal workaround we can patch directory package to use directly `java.nio.file.Files.createDirectory` or `java.nio.file.Files.createDirectories`

**Comment by jneira** [comment]
When https://github.com/typelead/eta-hackage/pull/77 is merged the bug should be fixed (after an `etlas update`)

**Comment by jneira** [comment]
@kemphack hi, the patch finally is merged and `createDirectoryIfMissing` should work correctly. Remember to do an `etlas update` to get the actual patch to directory package.

**Comment by jneira** [comment]
@kemphack hi, have you had the chance to try it? it works fine in my tests, so i close the issue. Feel free to reopen if you continue having problems with it.
