### ISSUE TITLE
Can't install eta on Ubuntu 17.10

### ISSUE THREAD

**Issue by bkyrlach** [typelead/eta#705]
I first tried downloading the ```etlas``` binary, but running ```etlas update``` gave me an error message saying I should create an issue here. Instead, I thought maybe I'd have more luck doing a full installation from source. However, after cloning, I get the following error message running ```install.sh```.

```
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

'--local-bin-path' will be removed in a future release.
Please use '--local-bin' instead.


Copying from /home/dcpdev/eta-dev/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta to /home/dcpdev/.local/bin/eta
Copying from /home/dcpdev/eta-dev/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta-build to /home/dcpdev/.local/bin/eta-build
Copying from /home/dcpdev/eta-dev/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta-pkg to /home/dcpdev/.local/bin/eta-pkg
Copying from /home/dcpdev/eta-dev/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/etlas to /home/dcpdev/.local/bin/etlas
Copying from /home/dcpdev/eta-dev/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/example to /home/dcpdev/.local/bin/example

Copied executables to /home/dcpdev/.local/bin:
- eta
- eta-build
- eta-pkg
- etlas
- example

WARNING: Installation path /home/dcpdev/.local/bin not found on the PATH environment variable
Cleaning files in rts/build, libraries/*/dist
# etlas (for clean)
Welcome to Etlas, the awesome build tool for the Eta programming language!

We are working hard to make the best platform for pure functional programming
on the Java Virtual Machine.

Etlas will periodically send usage statistics to help us:

* Make decisions on how to evolve the language

* Build a community portal that displays the data we collect in visual form

* Build an Etlas package repository that will accurately display package popularity

* And more!

For more details, please consult our privacy policy:

        http://eta-lang.org/docs/html/privacy-policy.html

Would you like to help us make Eta the fastest growing programming language,
and help pure functional programming become mainstream? (y/n)

y
Thank you for trying out Eta.

If you face any issues, you can:

* File an issue at:
      https://github.com/typelead/eta/issues/new

* Post your question on Eta-Discuss:
      https://groups.google.com/forum/#!newtopic/eta-discuss

* Ask on the Gitter channel:
      https://gitter.im/typelead/eta

Config file path source is default config file.
Config file /home/dcpdev/.etlas/config not found.
Writing default configuration to /home/dcpdev/.etlas/config
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
Build completed in 0:04m
# eta (for uninstall)
Cleaning files in /home/dcpdev/.eta/0.7.0.1
Build completed in 0:01m
# eta (for install)
# eta-pkg (for install)
# etlas (for install)
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
Updating binary package index.
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: etlas update
Exit code: 1
Stderr:
/home/dcpdev/.etlas/binaries/cdnverify.eta-lang.org/index: openFile: does not exist (No such file or directory)
)

/home/dcpdev/.etlas/binaries/cdnverify.eta-lang.org/index: openFile: does not exist (No such file or directory)
```

**Comment by jneira** [comment]
Hi @bkyrlach, it seems there is some problem with the fetching of files needed by etlas. 
The installation should have installed etlas, eta and eta-pkg in `/home/dcpdev/.local/bin`. Please, execute `etlas update -v3` to get a more verbose output and share it here.

**Comment by bkyrlach** [comment]
```
./etlas update -v3
no user package environment file found at /home/dcpdev/.local/bin
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
Searching for curl in path.
Found curl at /usr/bin/curl
Searching for powershell in path.
Cannot find powershell on the path
Searching for wget in path.
Found wget at /usr/bin/wget
Selected http transport implementation: curl
Updating index cache file
/home/dcpdev/.etlas/packages/hackage.haskell.org/01-index.cache ...
Searching for git in path.
Found git at /usr/bin/git
/usr/bin/git --version
etlas: Could not read index. Did you call 'checkForUpdates'?
```

**Comment by rahulmutt** [comment]
@bkyrlach Can you try `etlas update --http-transport=wget` and `etlas update --http-transport=plain-http` and see if that helps?

**Comment by bkyrlach** [comment]
```
$ ./etlas update --http-transport=wget
etlas: unrecognized 'update' option `--http-transport=wget'
$ ./etlas update --http-transport=http
etlas: unrecognized 'update' option `--http-transport=http'
```

**Comment by bkyrlach** [comment]
A few things worth mentioning...

- My MacBook that I have previously installed eta-lang on is no longer able to successfully update using ```etlas update```
- I'm doing this from work, and my work does have a fairly restrictive proxy
- Trying to hit ```https://cdnverify.eta-lang.org/index``` gives me a 404 in the browser.

Here's the response XML I get in my browser.

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:2b18f264-001e-012b-1e32-c1083f000000
Time:2018-03-21T16:33:59.1522376Z</Message></Error>
```

**Comment by rahulmutt** [comment]
@bkyrlach The link you should be trying is `https://cdnverify.eta-lang.org/eta-binaries/index`. So you're saying in an older version you were able to successfully download stuff behind the same restrictive proxy? The main difference from before and now is that before, the binaries were being downloaded over HTTP and recently we shifted it to HTTPS to make it more secure. By chance is this causing a problem? 

@jneira is also behind a proxy on Windows and he's reporting similar problems.

**Comment by bkyrlach** [comment]
In the output from ```etlas update```, it looks like it's trying to hit the URL I posted. I am able to access the URL you provided without an issue.

**Comment by bkyrlach** [comment]
Note that this binary was made using ```install.sh``` from a fresh clone of the ```eta``` repo as of yesterday. ```etlas --version``` returns the following.

```
./etlas --version
etlas version 1.1.0.0
compiled using version 2.1.0.0 of the etlas-cabal library 
```

**Comment by rahulmutt** [comment]
Hmm it seems the state of your `eta` clone is corrupt since the current version of `etlas` on `master` should be 1.3.0.0! Are you sure that you added the `--recursive` flag when cloning? You can also run:
```
git submodule sync
git submodule update --init --recursive
./cleaninstall.sh
```

`etlas` versions older than `1.2.0.0` can no longer perform binary installations because they have a bug where it doesn't add the `eta-binaries` prefix as you observed above. Have you tried downloading `etlas-1.2.0.0` from the [main website](https://eta-lang.org/docs/eta-concepts/getting-started/install-eta#binary-installation)?

**Comment by bkyrlach** [comment]
I'm super confused. I did initially try using the etlas binary from the website with similar results. However, downloading a fresh copy today, I was able to install. I think we can close this issue now. Sorry for the bother.

**Comment by jneira** [comment]
@bkyrlach Dont worry, maybe the original error with the etlas binary was caused with a temporal problem with the servers hosting the required files. Happy hacking with eta!
