### ISSUE TITLE
Error installing some packages with new-build: eta-java-interop, integer-logarithms

### ISSUE THREAD

**Issue by jneira** [typelead/eta#706]
* Trying to install wai-servlet with `etlas build` using the last version, that uses new-build i've got some errors:
```
PS C:\Users\Javier\dev\lang\eta\wai-servlet> etlas build
Resolving dependencies...
In order, the following will be built (use -v for more details):
....
Failed to build eta-java-interop-0.1.3.0. The failure occurred during the
final install step.
Build log (
C:\Users\Javier\AppData\Roaming\etlas\logs\eta-0.7.1.2\eta-java-inte_-0.1.3.0-ccedb436a14d65ea38b6a00be882e06b8214a7ae.log
):
Installing library in C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\eta-java-inte_-0.1.3.0-ccedb436a14d65ea38b6a00be882e06b8214a7ae\lib
copyFile: does not exist (El sistema no puede encontrar la ruta especificada.)jar )
...
Failed to build integer-logarithms-1.0.2. The failure occurred during the
final install step.
Build log (
C:\Users\Javier\AppData\Roaming\etlas\logs\eta-0.7.1.2\integer-logar_-1.0.2-885a1f087fdfe25a7026e7d9c549dea1ab25b99b.log
):
Installing library in C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\integer-logar_-1.0.2-885a1f087fdfe25a7026e7d9c549dea1ab25b99b\lib
copyFile: does not exist (El sistema no puede encontrar la ruta especificada.)nteger ( src\Math\NumberTheory\Powers\Integer.hs, dist\build\Math\NumberTheory\Powers\Integer.jar )
...
Failed to build transformers-0.5.5.0. The failure occurred during the final
install step.
Build log (
C:\Users\Javier\AppData\Roaming\etlas\logs\eta-0.7.1.2\transformers-0.5.5.0-728c63beb36750afd7f3e7d4c360b22bf3bf2507.log
):
Installing library in C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\transformers-0.5.5.0-728c63beb36750afd7f3e7d4c360b22bf3bf2507\lib
copyFile: does not exist (El sistema no puede encontrar la ruta especificada.)e.hs, dist\build\Data\Functor\Compose.jar )
....
etlas.exe: Failed to build eta-java-interop-0.1.3.0 (which is required by
wai-servlet-0.1.5.0). See the build log above for details.
Failed to build integer-logarithms-1.0.2 (which is required by
wai-servlet-0.1.5.0). See the build log above for details.
Failed to build transformers-0.5.5.0 (which is required by
wai-servlet-0.1.5.0). See the build log above for details.
```
[(Full log here)](https://gist.github.com/jneira/f915b8c8635a590fb8164f49a94cb93d)

**Comment by rahulmutt** [comment]
Which commit of `wai-servlet`? Version `0.1.5.0`?

**Comment by jneira** [comment]
@rahulmutt i am on master

**Comment by rahulmutt** [comment]
Hmm there's some weird path concatenation going on:
```
Installing library in C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\transformers-0.5.5.0-728c63beb36750afd7f3e7d4c360b22bf3bf2507\lib
```
should be
```
Installing library in C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\transformers-0.5.5.0-728c63beb36750afd7f3e7d4c360b22bf3bf2507\lib
```

Note that `C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504` is the lock file for the installation and `C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\transformers-0.5.5.0-728c63beb36750afd7f3e7d4c360b22bf3bf2507\lib` is where the library should *actually* be installed. Somehow, etlas is deciding to merge the two paths.

I have not been able to reproduce this locally on mac os x - it may be a windows specific issue.

**Comment by rahulmutt** [comment]
@jneira I was able to successfully reproduce this on Windows Server 2016, while I was attempting to reproduce #707. I'll see if I can add some debug statements and figure out why the paths are corrupted.

**Comment by rahulmutt** [comment]
@jneira I added similar debugging outputs on both Windows and Mac and I discovered that the "installing library in..." message above is completely correct! It seems like another case of long paths causing issues on Windows. A way to relocate the `.etlas/store` would probably solve this issue.

**Comment by jneira** [comment]
yeah, C:\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-1504\Users\Javier\AppData\Roaming\etlas\store\eta-0.7.1.2\eta-java-inte_-0.1.3.0-ccedb436a14d65ea38b6a00be882e06b8214a7ae\lib has more than 170 chars
Closing this as duplicate of #691

**Comment by jneira** [comment]
Reviewing the link about the limit i just realized that is 260 chars  (and no 170) so maybe the cause could be other

**Comment by jneira** [comment]
Hi, i've realized another test with this steps:
* Wipe out the etlas and eta user directories
* Do a `cleanInstall` of etlas, eta-pkg, eta, etc (master) 
* Build a [simple project](https://github.com/jneira/eta-test) with a simple dependency (directory)
  * Using `etlas build`
  * The build is succesful
* Add eta-java-interop as a dependency
  * This steps fails with this error:
```
Installing
D:\mypatheta\subpath\jneira\ws\eta\eta-test\dist\build\x86_64-windows\eta-0.7.1.2\eta-java-interop-0.1.3.0\build\HSeta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a.ffimap
to
C:\Users\adm\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-5256\Users\adm\AppData\Roaming\etlas\store\eta-0.7.1.2\eta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a\lib\HSeta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a.ffimap
copyFile: does not exist (El sistema no puede encontrar la ruta especificada.)
....
?callStack, called at .\Distribution\Compat\Stack.hs:45:13 in etlas_JfmbUsCcpuqCjYzOWzNe8g:Distribution.Compat.Stack
  callStack, called at .\Distribution\Simple\Utils.hs:591:44 in etlas_JfmbUsCcpuqCjYzOWzNe8g:Distribution.Simple.Utils
  withCallStackPrefix, called at .\Distribution\Simple\Utils.hs:628:7 in etlas_JfmbUsCcpuqCjYzOWzNe8g:Distribution.Simple.Utils
  withMetadata, called at .\Distribution\Simple\Utils.hs:353:15 in etlas_JfmbUsCcpuqCjYzOWzNe8g:Distribution.Simple.Utils
  die', called at .\Distribution\Client\ProjectOrchestration.hs:904:8 in etlas_8YAUwHc5dDCF5YUTRHO1O8:Distribution.Client.ProjectOrchestration

etlas: Failed to build
eta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a. The failure
occurred during the final install step.
Failed to build eta-test-0.1.0.0 because it depends on eta-test-0.1.0.0 which
itself failed to build.
```
* The file `D:\mypatheta\subpath\jneira\ws\eta\eta-test\dist\build\x86_64-windows\eta-0.7.1.2\eta-java-interop-0.1.3.0\build\HSeta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a.ffimap` exists and has less chars than 260
  * But the destination `C:\Users\adm\AppData\Roaming\etlas\store\eta-0.7.1.2\incoming\new-5256\Users\adm\AppData\Roaming\etlas\store\eta-0.7.1.2\eta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a\lib\HSeta-java-inte_-0.1.3.0-ad69cecaab897d3711f659be32c38328030d562a.ffimap` has 261!!
* *The version picked of eta-java-interop is 1.3.0 instead the last one 1.5.0*
* An `etlas install eta-java-interop` succeded
* After installing the package globally the `etlas build` succeeds too

@rahulmutt you analysis was correct, the cause is the same than #691 so close this one
