### ISSUE TITLE
Error installing package with cpp condition over package base version using etlas new-build

### ISSUE THREAD

**Issue by jneira** [typelead/eta#707]
* In double-conversion-2.0.2.0 there is a module (Data.Double.Conversion.Text) with a cpp condition:
```haskell
#if MIN_VERSION_base(4,4,0)
import Control.Monad.ST.Unsafe (unsafeIOToST)
#else
import Control.Monad.ST (unsafeIOToST)
#endif
```
* with etlas new-build it fails with:
```
Data\Double\Conversion\Text.hs:30:26:
    Module `Control.Monad.ST' does not export `unsafeIOToST'
```
* it seems the cpp condition is not working
* with `etlas old-build` it works

**Comment by rahulmutt** [comment]
Thanks for reporting this! Will look into it before the release.

**Comment by rahulmutt** [comment]
It's surprising that your build made it that far - mine failed with this error:
```
Configuring library for double-conversion-2.0.2.0..
Preprocessing library for double-conversion-2.0.2.0..
Building library for double-conversion-2.0.2.0..
etlas: '/Users/rahulmuttineni/.jenv/shims/java' exited with an error:
Cannot parse dependencies:
Malformed dependency: c++
```

By chance did you make a local patch?

**Comment by jneira** [comment]
ops, sorry, i've applied the patch that is in [my branch of eta-hackage for dhall](https://github.com/jneira/eta-hackage/blob/dhall-patches/patches/double-conversion-2.0.2.0.patch)

**Comment by rahulmutt** [comment]
I fetched your fork and checked out that branch and did `etlas get double-conversion` and got your patch applied automatically. Doing an `etlas build` worked fine for me. Wonder if it's another windows specific bug? Can you share the output of `etlas build -v3`? I'll see if the right flags are being sent to the `eta` compiler.

Off topic, but you forgot to include `Utils.java` in your patch and you didn't add a `java-sources:` field with that file. It'll probably throw an error at runtime.

**Comment by jneira** [comment]
Yeah, the patch is incomplete. I did a quick one to be able to compile dhall.

**Comment by jneira** [comment]
Hi, after a fresh install of eta and etlas (removing user dirs of eta and etlas) i've got the same error. The output of `etlas build -v3 > output.txt 2>&1` is https://gist.github.com/jneira/f4fb1a5ac21a4edf1e619a33ed412995

**Comment by jneira** [comment]
* `etlas install --only-dependencies && etlas old-build && etlas install` works fine

**Comment by rahulmutt** [comment]
The key part in the build output is the `eta` invocation at the bottom. The macro you're referring to is generated by `etlas` in a file called `cabal_macros.h`:
```
"-optPD:\mypatheta\subpath\jneira\ws\eta\dhall\double-conversion-2.0.2.0\dist\build\x86_64-windows\eta-0.7.1.2\double-conversion-2.0.2.0\build\autogen\cabal_macros.h"
```
I wonder if the option above is not getting forwarded properly to the c-preprocessor. Let me check to see what options are generated for Mac.

**Comment by rahulmutt** [comment]
@jneira Can you share the `-v3` output for `etlas old-build`? I think if we diff the two we can identify the problem easily.

**Comment by jneira** [comment]
sure: https://gist.github.com/jneira/371f9e66607655fa656b51308a477f03

**Comment by jneira** [comment]
with both `etlas build` and `etlas old-build` i see the cabal_macros.h with the content:
```
...
/* package base-4.8.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.8.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  8 || \
  (major1) == 4 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_base */
....
/*

**Comment by rahulmutt** [comment]
The difference is that `new-build` sends an absolute path to `cabal_macros.h` while `old-build` sends a relative path. I think this is causing a problem on Windows for some reason - maybe the drive letter?

**Comment by rahulmutt** [comment]
I confirmed by adding extra debug outputs to the `eta` compiler when it does the cpreprocessing step. On Windows Server, it's showing "missing file" for include files even they exist. Turns out that this it the code in `cpphs` to read include files: 
```
-- | Attempt to read the given file from any location within the search path.
--   The first location found is returned, together with the file content.
--   (The directory of the calling file is always searched first, then
--    the current directory, finally any specified search path.)
readFirst :: String             -- ^ filename
        -> Posn                 -- ^ inclusion point
        -> [String]             -- ^ search path
        -> Bool                 -- ^ report warnings?
        -> IO ( FilePath
              , String
              )                 -- ^ discovered filepath, and file contents

readFirst name demand path warn =
    case name of
       '/':nm -> try nm   [""]
       _      -> try name (cons dd (".":path))
  where
    dd = directory demand
    cons x xs = if null x then xs else x:xs
    try name [] = do
        when warn $
          hPutStrLn stderr ("Warning: Can't find file \""++name
                           ++"\" in directories\n\t"
                           ++concat (intersperse "\n\t" (cons dd (".":path)))
                           ++"\n  Asked for by: "++show demand)
        return ("missing file: "++name,"")
    try name (p:ps) = do
        let file = cleanPath p++'/':cleanPath name
        ok <- doesFileExist file
        if not ok then try name ps
          else do content <- readFileUTF8 file
                  return (file,content)
```
As you can see, it only checks whether the first letter is `/` to determine whether it's an absolute path! Hence absolute paths on windows will *not* be detected.

`cpphs` doesn't seem to be maintained any longer so I think we should switch over to `hpp` package which is maintained even now. A temporary fix could be to relativize include arguments before sending them to `cpphs`. I'll give it a shot to transition over to `hpp` and see how it goes.

**Comment by jneira** [comment]
Yeah, i test again the call to eta made by `etlas build` making all the paths relative and it works!

**Comment by rahulmutt** [comment]
Ok cool. I've made a branch with using `hpp` but there seem to be some cases it's not handling well. I'll give it another day and see if I can resolve the bugs. Otherwise, I'll just add a patch to relativize the paths for `-include` arguments to `cpphs`.

**Comment by jneira** [comment]
@rahulmutt and fix that function in cpphs? would be it possible?

**Comment by rahulmutt** [comment]
@jneira Missed that! Can you add a version contraint in `eta.cabal` and see if it fixes it? I've made good progress with the `hpp` transition.

**Comment by jneira** [comment]
Hi, i test an eta version bumping up the version of cpphs (adding a lower bound in `eta.cabal` and a `extra-dep` in `stack.yaml`) and it seems to work fine.
However i agree to use hpp is a better option overall.

**Comment by jneira** [comment]
I think that is resolved by @rahulmutt fork of hpp: https://github.com/rahulmutt/hpp/tree/fix-escaped-literals used last version of eta
