### ISSUE TITLE
Let user control where eta binaries are installed

### ISSUE THREAD

**Issue by jneira** [typelead/eta#708]
* In protected envs (specially in windows) it is usually forbidden the copy of executables in the actual directory used by etlas to download eta and eta-pkg executables (%APPDATA%\etlas\binaries). It would be useful be able to change that directory (for other reasons too)
* Maybe we can add a  `eta-binaries` config option (in cabal/config file and as comand line arg) to point to another directory

**Comment by rahulmutt** [comment]
@jneira You can either do `etlas --binaries-dir=[path] ...` or add `binaries-dir: [path]` in your `~/.etlas/config` or `binaries-dir: [path]` in your `cabal.project` file if you want to test it for a single project.
