### ISSUE TITLE
Typos on Eta Tour

### ISSUE THREAD

**Issue by sam543381** [typelead/eta#717]
I just spotted a language error on the Eta website.
see [https://tour.eta-lang.org/start#5](https://tour.eta-lang.org/start#5)
and search for `and it located within the base package`

original paragraph :
`
Every Eta program automatically imports the Prelude module which consists of standard functions and it located within the base package, which is standard library for Eta.
`

**Comment by sam543381** [comment]
https://tour.eta-lang.org/start#19
`in order to be construct a value` -> in order to construct a value
I'm not a native speaker, but I think this one is a mistake too.

**Comment by NickSeagull** [comment]
Thanks for reporting the typos Sam! They will be fixed as soon as possible :smile:

**Comment by Jyothsnasrinivas** [comment]
@sam543381 Thanks for reporting the typos. They are fixed now :)
