### ISSUE TITLE
[etlas] Support environment variable expansion for `maven-repos:` field

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#724]
As requested by @alexknvl, it would be nice to have `etlas` expand out environment variables to allow things like:

`maven-repos: $HOME/.m2`

without being too specific to a given user.

**Comment by jneira** [comment]
Using the new `etlas.dhall` file we could add env vars:
`let mvn = ( env:HOME as Text ) ++ ".m2" in { ..., maven-repos: mvn, ... }`

**Comment by rahulmutt** [comment]
Agreed, that's much cleaner. Closing.
