### ISSUE TITLE
gradle installation seems to hang forever

### ISSUE THREAD

**Issue by jneira** [typelead/eta#730]
Reported by @dumptruckman and tested by myself, both in windows
Following the steps in https://eta-lang.org/docs/eta-concepts/getting-started/install-eta#gradle-installation the execution of `.\gradlew.bat run` seems to hang out forever (up to 45 min)

**Comment by rahulmutt** [comment]
@jneira Thanks for reporting this. I was able to reproduce this on Windows Server, will investigate.

Btw, for future Gradle plugin related issues, please file them on https://github.com/typelead/gradle-eta

**Comment by jneira** [comment]
Hi, with the last version of eta-init/gradle-plugin i am not able to reproduce so i will close this one.
@dumptruckman feel free to reopen this issue if you continue having the same error (in https://github.com/typelead/gradle-eta as suggested by @rahulmutt)
