### ISSUE TITLE
[docs] Main page layout breaks at ~1100 px width

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#735]
The main page (eta-lang.org) has an unintended layout overlap when the screen size/browser window is around 1100 px wide.

<img width="1148" alt="screen shot 2018-04-15 at 18 23 11" src="https://user-images.githubusercontent.com/5824532/38780694-e5dba7fa-40da-11e8-9eb5-5d9c99495a1c.png">

This was taken on chrome on a mac but I suspect other browsers won't be much different.

**Comment by Jyothsnasrinivas** [comment]
@JustusAdam this should be fixed now. Can you do a hard reload and let me know if it looks better now?

**Comment by JustusAdam** [comment]
Looks good to me. It jumps around a bit when making the window smaller, but it no longer overlaps.

**Comment by Jyothsnasrinivas** [comment]
@JustusAdam Thanks for confirming! Closing this one.
