### ISSUE TITLE
Add support for OverloadedLabels

### ISSUE THREAD

**Issue by tjhunter** [typelead/eta#738]
I am trying to port some code from GHC to Eta and a blocking import is the following dependency chain:
 - lens-labels
 - proto-lens

`proto-lens` is very convenient for parsing and writing protocol buffers using lenses, but it unfortunately requires GHC8 features to work. When trying to use lens-labels as a dependency in an Eta project, the following error gets triggered:

```
Failed to build lens-labels-0.2.0.0.
Build log (
/Users/tjhunter/.etlas/logs/eta-0.7.2.1/lens-labels-0.2.0.0-7fe1e6c34f4abf91976b389df04076566f746fe7a32dd702c7e43064a349a4f4.log
):
Configuring library for lens-labels-0.2.0.0..
Preprocessing library for lens-labels-0.2.0.0..
Building library for lens-labels-0.2.0.0..
src/Lens/Labels.hs:58:8: error:
    Could not find module ‘GHC.OverloadedLabels’
    Use -v to see a list of the files searched for.
   |
58 | import GHC.OverloadedLabels (IsLabel(..))
   |        ^^^^^^^^^^^^^^^^^^^^
```

I tried a number of protocol buffers-related packages and this one is by far the most convenient. If the choice is between good support for the jvm and good support for protocol buffers, I will pick the former for now.

Do you have a sense of the complexity of porting `OverloadedLabels` to Eta?

Link: https://hackage.haskell.org/package/lens-labels

**Comment by rahulmutt** [comment]
Hi @tjhunter, thanks for your request. `OverloadedLabels` is becoming one of the most frequently used GHC features and many libraries have started adopting in. Given that, it makes lots of sense to get it ported to Eta to maintain ecosystem compatibility.

Moreover, thanks for providing a very nice use case for them - that's what we look for when justifying the backport an extension.

**Comment by rahulmutt** [comment]
With regard to complexity, it shouldn't be too hard to backport. But we probably won't get around to doing the backport anytime soon since we are currently working on other things. PRs are welcome.

**Comment by Jyothsnasrinivas** [comment]
@tjhunter We've backported OverloadedLabels. It should work with the current master and will be available in the next binary release. Closing this issue for now. If you face anymore problems feel free to open an issue.
