### ISSUE TITLE
Broken Links on website.

### ISSUE THREAD

**Issue by p-h** [typelead/eta#742]
https://www.deadlinkchecker.com gives me the following:

- https://eta-lang.org/docs/eta-tutorials/web-services/overview
- https://eta-lang.org/docs/user-guides/eta-user-guide/installation/gradle-installation
- https://eta-lang.org/docs/user-guides/eta-user-guide/installation/etlas-installation
- https://eta-lang.org/docs/user-guides/eta-user-guide/installation/docker-installation
- https://eta-lang.org/docs/user-guides/eta-user-guide/installation/source-installation
- https://eta-lang.org/docs/user-guides/eta-user-guide/installation/nix-installation
- https://eta-lang.org/manifest.json
- https://eta-lang.org/docs/eta-tutorials
- https://eta-lang.org/contributors-license/index
- https://eta-lang.org/css/ajax-loader.gif
- https://eta-lang.org/css/fonts/slick.ttf
- https://eta-lang.org/fonts/BrandonText-light.otf
- https://eta-lang.org/css/fonts/slick.eot
- https://eta-lang.org/css/fonts/slick.woff
- https://eta-lang.org/fonts/BrandonText-light.ttf
- http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html
- https://eta-lang.org/css/wp-content/themes/kinsta/images/home-hero.svg
- https://eta-lang.org/docs/eta-concepts/java-interop/java-generics
- https://eta-lang.org/docs/eta-concepts/java-interop/jwts
- https://eta-lang.org/docs/user-guides/etlas-user-guide/basics/intializing

**Comment by Jyothsnasrinivas** [comment]
Thanks for reporting @p-h ! We've fixed all the broken links. Closing this issue.
