### ISSUE TITLE
[eta-tour]: Bug - hello world type program produces no output

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta#748]
The following code produces no output in the console:

Source Code:
```haskell
main :: IO ()
main = do

  putStrLn "Interact with me!"
```

Output:
```shell
```

[write-further-description-here]

**Comment by rahulmutt** [comment]
@jstr045329 I am unable to reproduce this. Maybe it was a transient error on the backend side. Are you seeing any errors in the console?

**Comment by rahulmutt** [comment]
Closing, as the bug was not reproducible.
