### ISSUE TITLE
Error building packages with modules containing ANN pragmas (f.e. optparse-applicative, aeson)

### ISSUE THREAD

**Issue by jneira** [typelead/eta#755]
* Trying to build the package optparse-applicative-0.14.0.0 with last version of eta with template haskell support i ve got this error, related with ghc [ANN pragmas](https://downloads.haskell.org/~ghc/8.4.1/docs/html/users_guide/extending_ghc.html#annotating-values):
```
C:\Users\Javier\dev\lang\eta\dhall>etlas get optparse-applicative-0.14.0.0 && cd optparse-applicative-0.14.0.0 && etlas build
Unpacking to optparse-applicative-0.14.0.0\
Found patch in eta-hackage for optparse-applicative-0.14.0.0
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - ansi-terminal-0.6.2.3 (lib:ansi-terminal) (requires build)
 - ansi-wl-pprint-0.6.8.2 (lib) (requires build)
 - optparse-applicative-0.14.0.0 (lib) (first run)
Found patch in eta-hackage for ansi-terminal-0.6.2.3
Configuring ansi-terminal-0.6.2.3 (all, legacy fallback)...
Building ansi-terminal-0.6.2.3 (all, legacy fallback)...
Configuring ansi-wl-pprint-0.6.8.2 (lib)...
Building ansi-wl-pprint-0.6.8.2 (lib)...
Configuring library for optparse-applicative-0.14.0.0..
Preprocessing library for optparse-applicative-0.14.0.0..
Building library for optparse-applicative-0.14.0.0..
[ 8 of 16] Compiling Options.Applicative.Help.Core
Options\Applicative\Help\Core.hs:68:15: error:
    No instance for (Functor f1) arising from a use of ‘fmap’
    The type variable ‘f1’ is ambiguous
    Note: there are several potential instances:
      instance Functor (Const m) -- Defined in ‘Control.Applicative’
      instance Control.Arrow.Arrow a => Functor (WrappedArrow a b)
        -- Defined in ‘Control.Applicative’
      instance Monad m => Functor (WrappedMonad m)
        -- Defined in ‘Control.Applicative’
      ...plus 60 others
    In the second argument of ‘maybe’, namely ‘fmap’
    In the expression: maybe id fmap (optDescMod opt) (render desc')
    In the expression:
      let
        ns = optionNames $ optMain opt
        mv = stringChunk $ optMetaVar opt
        descs = map (string . showOption) (sort ns)
        ....
      in maybe id fmap (optDescMod opt) (render desc')
   |
68 |   in maybe id fmap (optDescMod opt) (render desc')
   |
.....
Another 15 errors about ambiguous instances (????)
....
Options\Applicative\Help\Core.hs:177:1: error:
    Exception when trying to run compile-time code:
      terminateProcess: permission denied (Permission denied)
    In the annotation:
      {-# ANN footerHelp "HLint: ignore Eta reduce" #-}
    |
177 | {-# ANN footerHelp "HLint: ignore Eta reduce" #-}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
If i comment out the ANN pragmas the package can be built (no errors about instances)

**Comment by rahulmutt** [comment]
Strangely enough, I am unable to reproduce this on OS X. That `terminateProcess: permission denied (Permission denied)` implies there may be some Windows permission problem. Perhaps Windows has restrictions on how subprocesses can be terminated?

**Comment by jneira** [comment]
Maybe related with https://github.com/haskell/process/pull/111?

**Comment by jneira** [comment]
@rahulmutt what do you think about comment out ANN pragmas in eta-hackage patches for now?

**Comment by rahulmutt** [comment]
Yeah that's fine. Do you think you can make a fork of the `process` package, apply the patch in the linked PR, add your fork via Git dependency to the `stack.yaml` in your `eta` repo and see if that fixes the problem? If so, we can try to push the PR to get merged and use the fork in the meantime.

**Comment by rahulmutt** [comment]
@jneira Have you verified that it fixed it?

**Comment by jneira** [comment]
Oh, i closed it in the commit without wanting, thank you for reopen.
Btw, i get to build process in windows (it needs a sh with `autoconf` and `m4` and after run `autoconf` in mingw64 i had to manually add https://hackage.haskell.org/package/process-1.0.1.3/src/include/HsProcessConfig.h.in cause autoconf didnt create it)
And... it didn't fix the error :worried:

Could be that error mask another previous error? When using my version of eta-serv.jar manually modified with proguard, `etlas repl`throwed the same error...

**Comment by rahulmutt** [comment]
@jneira Yes you may be right about error masking. `terminateProcess` is only called in the first place if some exception happened on the eta-serv side. Let me try it out on the Windows node.

**Comment by rahulmutt** [comment]
@jneira I was unable to reproduce this on the Windows node (ran `etlas repl optparse-applicative` and it succesfully loaded the REPL without issues). I wonder if permission issues are occurring. 

You can try running:

```
etlas repl optparse-applicative --eta-options="-v4 -opti-v"
```
And share the contents of the `optparse-applicative` build log which can be found in `~/.etlas/logs`.

**Comment by jneira** [comment]
* Works for me in windows 10 now (the original log is from that env)
* Will test it in windows 7 asap

**Comment by jneira** [comment]
Works in windows 7 too.. :+1:
