### ISSUE TITLE
Compiling Numeric.Half    eta: panic!

### ISSUE THREAD

**Issue by davips** [typelead/eta#767]
I am trying to compile a Gloss project that I used to compile with Stack/Cabal, but no success.
It stops in the dependence Numeric.Half.

```
  Building library for half-0.3..
  
  [1 of 1] Compiling Numeric.Half    eta: panic! (the 'impossible' happened)
    (Eta version 0.8.0b2):
        tcCheckFIType: Unsupported calling convention.
    ccall unsafe "value hs_halfToFloat"
  
  Please report this as a Eta bug: http://github.com/typelead/eta/issues
  
  
  Failed to build pretty-show-1.7.

```

**Comment by Jyothsnasrinivas** [comment]
@davips Thanks for reporting. Gloss requires a windowing manager backend. For Eta this means that someone needs to write a JavaFX backend for Gloss to work.

**Comment by davips** [comment]
That makes sense, thanks

**Comment by rahulmutt** [comment]
Closing this issue as Gloss won't be supported soon (although we're happy to help anyone who tries to port it with JavaFX!) and given that `half` is now patched.
