### ISSUE TITLE
Better error message on foreign export

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#77]
According to @NCrashed:

> Just to note, the current implementation fails on the:
> 
> import Primes
> import GHC.Base
> 
> foreign export java takePrime :: Int -> Java a Int
> 
> takePrime i = return . fromIntegral $ primes !! i
> 
> primes = filterPrime [2..]
>   where filterPrime (p:xs) =
>           p : filterPrime [x | x <- xs, x `mod` p /= 0]
> With:
> 
> ghcvm: panic! (the 'impossible' happened)
>   (GHCVM version 0.0.1):
>     No type variables for the Java foreign export!

The panic should be replaced with a notice that you cannot have a quantified variable in the tag position of the Java monad for exports (yet). This should be done in `GHCVM.TypeCheck.TcForeign`.

**Comment by tibi77** [comment]
why can't it be done in compiler/ETA/Utils/Panic.hs just by changing the panic output or maybe by giving the sorry output instead[1]? "sorry! (unimplemented feature or known bug)\n"

**Comment by rahulmutt** [comment]
@tibi77 So the idea is to give a "human-readable" error that clearly states what mistake the programmer made and how they can fix it. I think you might have misunderstood it.

**Comment by NickSeagull** [comment]
Did this get fixed in #341 ? :smile:

**Comment by jneira** [comment]
@rahulmutt yeah, it seems it can be closed

**Comment by rahulmutt** [comment]
Great, closing!
