### ISSUE TITLE
Deterministic builds for JAR files

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [typelead/eta#770]
With commit 2548001d2212af77f76f4d88a722195d0834f2a6 we have deterministic interface files. We need to work on deterministic JAR files. 

The files marked red show that the hashes are different for the JAR files. We need to investigate all the sources of non-determinism in the code generator.

<img width="1280" alt="screen shot 2018-06-18 at 11 39 59 am" src="https://user-images.githubusercontent.com/13062967/41520652-645ed1f4-72ec-11e8-8a4e-f2c5319dbf0c.png">

**Comment by rahulmutt** [comment]
Builds are fully reproducible after resolving #775.
