### ISSUE TITLE
Make clear all the possible classes for ffi exports in docs

### ISSUE THREAD

**Issue by jneira** [typelead/eta#772]
[Actual docs for ffi exports](https://eta-lang.org/docs/user-guides/eta-user-guide/java-interop/java-interop-basics#exporting-eta-methods) should be updated to take in account all possible cases:
* The `[export string]` is optional and it can have the `@static` annotation or not
* You can export an instance method of a new class defined in eta code subclassing an existing java interface, abstract class or nomal class
  * For example `wai-servlet` [define a new `network.wai.servlet.DefaultWaiServlet`](javax.servlet.GenericServlet) that extends the abstract class [`javax.servlet.GenericServlet`](https://docs.oracle.com/javaee/7/api/javax/servlet/GenericServlet.html) and then it lets you export it implementing [the abstract method `service`](https://github.com/jneira/wai-servlet/blob/master/src/Network/Wai/Servlet/Examples.hs#L91)
  * Although the idomatic use of non static ffi exports is the previous one, you can export instance methods for non abstract classes (example [here](https://github.com/jneira/eta-test/blob/print-ffi/src/Lib.hs#L21-L38))
  * If you write an ffi export without the `@static` annotation and without `[export-jwt]` eta generates an instance method in the module class and it can drive to unexpected behaviour, cause it generates a static method with the same name of the function (see #710)
* The ffi accepts `IO [return-type]` instead `Java [export-jwt] [return-type]` as result type

**Comment by jneira** [comment]
@rahulmutt Maybe the compiler should reject non static ffi exports without `[export-jwt]`?

**Comment by rahulmutt** [comment]
@jneira Yes, definitely.

**Comment by jneira** [comment]
I think it can be closed, filling a new issue for the suggestion in https://github.com/typelead/eta/issues/772#issuecomment-398002748
