### ISSUE TITLE
Remove .eta-link-info from jar files

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#776]
To detect changes in Java source files and Java dependencies and recompile accordingly, an `.eta-link-info` file is stored into the output jar and contains a set of hashes to later compare for changes. The problem is that this file is a bit volatile and keeps changing so it hurts build reproducibility. It should be stored separately in the build output folder instead.

**Comment by jneira** [comment]
Agree, i'll try to take a look asap.

**Comment by rahulmutt** [comment]
Resolved with #777
