### ISSUE TITLE
Can't generate Haddock for eta-repl

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#779]
I tried to build the Haddock for eta-repl and I got an error at this line:

https://github.com/typelead/eta/blob/eb9e98b4734df62c973ea79546c8e3ab8651081c/libraries/eta-repl/Eta/REPL/Message.hs#L50

**Comment by puffnfresh** [comment]
Same with eta-meta with this comment:

https://github.com/typelead/eta/blob/eb9e98b4734df62c973ea79546c8e3ab8651081c/libraries/eta-meta/Language/Eta/Meta/Server.hs#L95-L96

**Comment by rahulmutt** [comment]
Reproduced this with `stack haddock`. It seems the issue is this: https://github.com/haskell/haddock/issues/43

Prefix comments are not supported in 7.10.3 it looks like. Will convert them all to normal comments for now until we migrate to GHC 8 completely.

**Comment by puffnfresh** [comment]
Thanks! :heart:
