### ISSUE TITLE
"Getting Started" link in README.md is broken

### ISSUE THREAD

**Issue by Kawzeg** [typelead/eta#794]
The getting started link in README.md currently points to https://eta-lang.org/docs/eta-concepts/getting-started/what-is-eta, which returns 404.

I *assume* it moved to https://eta-lang.org/docs/user-guides/eta-user-guide/introduction/what-is-eta?

**Comment by rahulmutt** [comment]
@Kawzeg Yes, that's correct. If you're up for it, we'd be happy to accept a PR to change that.

**Comment by Kawzeg** [comment]
@rahulmutt Okay, I'm doing that. I also noticed that the proposals link points to the bug report page instead of the proposals, so I'll fix that as well.
