### ISSUE TITLE
Website broken between 1025px and 1225 in width

### ISSUE THREAD

**Issue by tomhodgins** [typelead/eta#801]
Hey, I was a little surprised by loading up your website yesterday to check out the project. The homepage of the website appeared broken to me (buttons overlaying text, backgrounds overlaying text) and so I'm reporting this bug on the website itself.

My first impression of Eta has been that whoever built the homepage, my first impression of the project and the very first thing you see when you get linked to Eta by somebody who tells you to check it out, has clearly never even once loaded up their own homepage in a web browser and viewed it between the widths of 1025px and 1225px. The layout works when the browser is smaller than that, and the layout works when the browser is wider than that, but making your browser somewhere between 1025-1225 pixels wide is common for desktop users, which means many people might be seeing this website in its broken state as their first impression of Eta.

Here's a video of resizing the browser so you can see the 'dead zone' in the design: http://staticresource.com/eta-broken.mp4

After seeing the state of this website my first impressions of the Eta project are:

- they have a severe lack of attention to detail
- they have an apparent total lack of testing? clearly this homepage wasn't even looked at _once_

So you might want to update the homepage if ^ those aren't the first qualities you want to communicate strongly to new people checking out your project.

screenshots:
![screen shot 2018-07-09 at 10 21 05 am](https://user-images.githubusercontent.com/955601/42457086-7cca088e-8364-11e8-9455-a6c6db99f938.png)

![screen shot 2018-07-09 at 12 16 21 am](https://user-images.githubusercontent.com/955601/42457087-7cdfbd96-8364-11e8-8aeb-dfa6677c7821.png)

**Comment by Jyothsnasrinivas** [comment]
Thanks @tomhodgins for the detailed issue. I've deployed a fix for this. Please do a hard reload and try again. Let me know if there are anymore problems.

**Comment by tomhodgins** [comment]
That seems to have resolved the issue I was seeing!
