### ISSUE TITLE
eta: panic! (the 'impossible' happened) on eta-scala-interop

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#804]
Using Eta as of b68dbcb8fdb5e864806f14fed85c2a16df1d0628, I am trying to build https://github.com/typelead/eta-scala-interop

If I do `etlas build` I get:

```
[1 of 1] Compiling Interop.Scala   eta: panic! (the 'impossible' happened)
  (Eta version 0.8.0b3):
        Prelude.Enum.Bool.toEnum: bad argument
```

If I do `etlas repl` I get:

```
eta: panic! (the 'impossible' happened)
  (Eta version 0.8.0b3):
        Ix{Int}.index: Index (3942645760) out of range ((0,357))
```

The problem is probably in eta-scala-interop but I think the error could be better here.

**Comment by rahulmutt** [comment]
Run `rm -rf ~/.etlas/store` and try again. It looks like you have stale interface files.

**Comment by puffnfresh** [comment]
Yeah, reinstall worked. Thanks!
