### ISSUE TITLE
eta-fib-service doesn't build on mac

### ISSUE THREAD

**Issue by babusri** [typelead/eta#807]
etlas build

Configuring library for unix-2.7.2.2..
Preprocessing library for unix-2.7.2.2..
etlas: can't find source for System/Posix/Resource in ., dist/build/autogen,
dist/build/global-autogen
etlas: Failed to build unix-2.7.2.2 (which is required by exe:eta-fib-service
from eta-fib-service-0.1.0.0). See the build log above for details.

**Comment by jneira** [comment]
Hi, it seems some change in dependencies makes etlas pick up servant-server-0.13.0.1, that does not have a patch in eta-hackage to avoid unix/win32. Until that version get the patch i have managed to build eta-fib-service changing in `eta-fib-service.cabal` the bounds of servant-server to:
```
 servant-server == 0.12
```

**Comment by rahulmutt** [comment]
@jneira Can you submit a PR for `eta-fib-service`? Having that bound is useful to ensure a working version of servant gets picked up everytime.

**Comment by jneira** [comment]
@rahulmutt sure!

**Comment by jneira** [comment]
[Dependencies are already fixed for `eta-fib-service`](https://github.com/typelead/eta-fib-service/pull/2) , @babusri could you try again after pulling the lastest master?

**Comment by babusri** [comment]
Works.
Thanks.

**Comment by babusri** [comment]
btw, I modified my local version to
myfibseq = 1:1:zipWith (+) myfibseq (tail myfibseq)
fastfib :: Int -> Integer  (to avoid overflow)
fastfib n = head $ reverse $ take n myfibseq

and it works fine.
http://localhost:9000/fibonacci/100 ==> {"fast fib":354224848179261915075,"n":100}

**Comment by Jyothsnasrinivas** [comment]
Closing this issue because it seems like the problem is resolved!
