### ISSUE TITLE
Unknown option -Wno-too-many-guards

### ISSUE THREAD

**Issue by puffnfresh** [typelead/eta#808]
Using GHC 8.2.2 I'm being told the `-Wno-too-many-guards` option doesn't exist at this line:

https://github.com/typelead/eta/blob/f6a0255d81c1a4e04164754170909fdc207e2516/compiler/Eta/Types/OptCoercion.hs#L5

**Comment by Jyothsnasrinivas** [comment]
@puffnfresh I've updated the `OptCoercion` module with the latest flag. Can you check if it works?

**Comment by puffnfresh** [comment]
That fixed it, thanks @Jyothsnasrinivas !!
