### ISSUE TITLE
[nix] Remove the need for additional commands after starting the shell

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#810]
This issue is a response to @puffnfresh's [comment](https://github.com/typelead/eta/issues/809#issuecomment-404780622) in #809. 

In summary, `eta-build install` does the following:
1) `etlas update`
2) `etlas select local` - ensures that the local etlas will get selected by default.
3) Copies `utils/couriser/coursier` to `~/.etlas/tools/coursier`
4) Compiles `utils/class-verifier/Verify.java` with `javac` and copies the resulting `Verify.class` to `~/.etlas/tools/classes/Verify.class`.
  - `Verify.java` rarely ever changes so we may just get away with stashing `Verify.class` into the repo.
5) Builds all the libraries in the `libraries` subfolder with the command `etlas install --allow-boot-library-installs`.
6) `etlas install template-haskell-2.11.1.0 --allow-boot-library-installs`
7) Run `./gradlew proJar` inside the `eta-serv` subfolder. Move the resulting `eta-serv/build/eta-serv.jar` to  `~/.etlas/tools/eta-serv.jar`.

It would be great if those steps are included in the Nix script so that the user doesn't have to initiate it themselves when loading the shell.

**Comment by puffnfresh** [comment]
Is there an environment variable or flag we can set to specify where the Etlas libraries are installed? That way we can get them stored in the Nix store.

**Comment by puffnfresh** [comment]
I've started on this but got a bit stuck on the eta-serv Gradle part. I'm just going to write the Nix to build that manually, without Gradle.

**Comment by rahulmutt** [comment]
@puffnfresh Yes that can be done. We wanted to make sure that `eta-serv.jar` was as tiny as possible, so we had to add steps to make an uberjar and then proguard the result. Building an uberjar with gradle is a lot faster than with `eta` and we don't have proguard support yet inside of Etlas so we had to go with Gradle at the time. In the long term though, it would be great to build it with Etlas itself.

A workaround for now is:
1) Build an uberjar with etlas itself by adding a `cabal.project` inside of `eta-serv` and add the following contents:
```
uberjar-mode: True
```
2) Run proguard on the result. You should be able to write a nix derivation for proguard as it is distributed as a standalone jar.

**Comment by jneira** [comment]
I had to change eta-serv to be built by etlas and copying the uberjar in the correct dir worked fine. If i remeber correctly i had to create a minimal `eta-serv.cabal` file.

**Comment by rahulmutt** [comment]
@jneira Can you submit that as a PR? It won't interfere with the existing gradle setup.

**Comment by jneira** [comment]
@rahulmutt hi, i've submitted #837 with the cabal config files needed to build eta-serv

**Comment by puffnfresh** [comment]
There's a few improvements I can make but I have a version here for testing:

https://github.com/eta-lang/eta-nix/tree/etaPackages

It's able to build packages such as Dhall and PureScript so I think it's working pretty well. My next step is to make some small improvements then change this repo's Nix code to reference my new work.
