### ISSUE TITLE
etlas cheatsheet shows wrong command

### ISSUE THREAD

**Issue by justjoheinz** [typelead/eta#817]
At https://eta-lang.org/docs/cheatsheets/etlas-cheatsheet an alternative to `etlas --version` is given as `etlas -v`. The latter command does not work:

```
~$ etlas -v
etlas: unrecognised command: -v (try --help)
```

**Comment by Jyothsnasrinivas** [comment]
@justjoheinz Thanks for pointing out. There was a minor typo in the cheatsheet.  

The correct command is `etlas --v`, which should be updated on the docs now. 

So closing this one.
