### ISSUE TITLE
[eta-tour]: Bug - [Slide 3 of 5 in Interact with the Tour] - There is no Format button!

### ISSUE THREAD

**Issue by VincePlatt** [typelead/eta#824]
The example code has this text:  "Click Format button", which obviously doesn't exist.  Just a nitpick, but a wee bit confusing.

Source Code:
```haskell
main :: IO ()
main = do

  putStrLn "Interact with me!"

  putStrLn "Click Run button"

  putStrLn "Click Reset button"

  putStrLn "Click Format button"
```

Output:
```shell
Hello

**Comment by Jyothsnasrinivas** [comment]
@VincePlatt Thanks for reporting this! I deployed a fix for this so closing the issue.
