### ISSUE TITLE
Gradle installation hangs on Windows 10 when telemetry is disabled

### ISSUE THREAD

**Issue by nmaehlmann** [typelead/eta#828]
Following the user guide for the gradle installation (https://eta-lang.org/docs/user-guides/eta-user-guide/installation/gradle) using Windows 10, the installation process hangs when the user chooses to not send metrics:

The command `$ gradlew.bat run -PetaSendMetrics=false`
hangs on step `> Task :setupEnvironmentEta` showing 0% progress after 5 minutes.

However running  `$ gradlew.bat run -PetaSendMetrics=true` works.

**Comment by rahulmutt** [comment]
I was not able to reproduce this on OS X and most likely it will work in Linux as well. We do have a special case in the `gradle-eta` plugin that handles Windows so that special case may not be working as intended. I'll test it out on our windows node.

**Comment by rahulmutt** [comment]
@nmaehlmann A workaround is to edit `%APPDATA%\Roaming\etlas\config` - there's a field called `send-metrics` and you should set it to `False`:
```
send-metrics: False
```

**Comment by rahulmutt** [comment]
This bug is now fixed on master. The next version of etlas will handle this case properly.
