### ISSUE TITLE
Gradle installation failing

### ISSUE THREAD

**Issue by RobTrew** [typelead/eta#836]
```
* What went wrong:
Error resolving plugin [id: 'com.typelead.eta', version: '0.7.5']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for com.typelead.eta:com.typelead.eta.gradle.plugin:0.7.5
      > Could not get resource 'https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.5/com.typelead.eta.gradle.plugin-0.7.5.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.5/com.typelead.eta.gradle.plugin-0.7.5.jar'.
            > Connection reset
```
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:comman
```

(OS X 10.13.6)

**Comment by rahulmutt** [comment]
@RobTrew Can you share the configuration of the project you were trying to build when this happened? Does upgrading to `0.7.8` fix the problem?

**Comment by RobTrew** [comment]
@rahulmutt Rather than a project build, the context was simply that of following first-time Eta-lang install instructions from: 

https://eta-lang.org/docs/user-guides/eta-user-guide/installation/gradle

**Comment by rahulmutt** [comment]
I am not able to reproduce this. Most likely the error is coming from a restricted network as evidenced by this part of the error message:
```
Could not HEAD 'https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.5/com.typelead.eta.gradle.plugin-0.7.5.jar'.
            > Connection reset
```

Can you check your networking configurationand allow `plugins.gradle.org` if it's blocked?

**Comment by RobTrew** [comment]
Not behind a network here (personal OS X system with direct connection at home) and no local network filters enabled.

Attempting to fetch 
```
https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.5/com.typelead.eta.gradle.plugin-0.7.5.jar
```

yields:
```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```

**Comment by rahulmutt** [comment]
@RobTrew Which version of Java are you using? And have you used Gradle before for other projects?

**Comment by RobTrew** [comment]
@rahulmutt Java version 8 update 181

and no – I haven't used Gradle before.

**Comment by rahulmutt** [comment]
This looks like a Gradle issue. Can you share the output of `./gradlew run -d --stacktrace` in a Gist?

**Comment by RobTrew** [comment]
Certainly:

https://gist.github.com/RobTrew/6ee8cc7abfc6c0ed7ba1ea29b4cf35b7

**Comment by RobTrew** [comment]
Some progress ... thank you ... but this time:

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: com/typelead/gradle/eta/plugins/EtaPlugin : Unsupported major.minor version 52.0
> com/typelead/gradle/eta/plugins/EtaPlugin : Unsupported major.minor version 52.0

**Comment by rahulmutt** [comment]
By chance did you install Java 1.7 at some point? 52.0 is Java 8 which shouldn't be a problem if Java 8 was being picked up by Gradle.

**Comment by RobTrew** [comment]
No, I've never installed Java 1.7, to my knowledge.

**Comment by RobTrew** [comment]
Ah ... thank you ... I did find a Java 1.7 - now removed, and all seems well.

Very much appreciate you time. Thank you !

**Comment by rahulmutt** [comment]
Great to hear your problem is resolved!
