### ISSUE TITLE
Creating classes in Eta?

### ISSUE THREAD

**Issue by bradrn** [typelead/eta#838]
Is it possible to create a new class and use it, all within Eta code? Currently if I try doing something like this I get a nasty error:
```haskell
module Main where

import Java

data NewClass = NewClass @my.application.NewClass deriving Class

foreign import java unsafe "@new" newNewClass :: Java a NewClass

main :: IO ()
main = java (newNewClass) >> putStrLn "Everything works!"
```
I know I can just drop down to Java and write the class there, but it would be so nice to just be able to do it in Eta...

**Comment by jneira** [comment]
Hi! eta actually can *export* classes through exporting methods: see https://eta-lang.org/docs/user-guides/eta-user-guide/java-interop/java-interop-basics#exporting-eta-methods. However it cant add contructors (the class only would have the empty default one) 
Otoh there is plans to automatically export java classes from eta types:  https://github.com/typelead/eta/issues/690
Hope it helps, feel free to ask if you have any question.

**Comment by bradrn** [comment]
I am aware that Eta can export classes to Java; however, I'm wondering if there is a way to _use_ the class in Eta as well. Although I actually did manage to solve the particular problem I was having while perusing https://github.com/typelead/eta-examples/blob/master/2-javafx/src/JavaFX/Methods.hs, I still think that this functionality could be useful.

**Comment by jneira** [comment]
Mmm, could you share the concrete problem and the final solution? not sure if i understand the use case cause you actually can use (for some meaning of use) the exported class in eta. For example, extending the example in [docs](https://eta-lang.org/docs/user-guides/eta-user-guide/java-interop/java-interop-basics#exporting-eta-methods):
```haskell
-- Importing an existing class
data JavaCounter = JavaCounter @eta.example.Counter 
   deriving Class

-- eta.example.EtaCounter will be generated by eta
data EtaCounter = EtaCounter @eta.example.EtaCounter 
   deriving Class

-- Required to make EtaCounter a subclass of JavaCounter
type instance Inherits EtaCounter = '[JavaCounter]

-- Importing methods from JavaCounter with ( c <: JavaCounter )
-- to make it works for its subclasses (including EtaCounter)
foreign import java unsafe get :: ( c <: JavaCounter )
                               => Java c Int

foreign import java unsafe set :: ( c <: JavaCounter )
                               => Int -> Java c ()
```
with
```haskell
foreign import java unsafe "@new" newEtaCounter  :: Java a EtaCounter

createAndUseEtaCounter :: Java a Int
createAndUseEtaCounter = do
  c <- newEtaCounter
  c <.> (set 10)
  c <.> get
```
you could do
```haskell
main = do
  i <- java $ createAndUseEtaCounter
  putStrLn $ "The value is " ++ show i  
```

**Comment by bradrn** [comment]
> could you share the concrete problem and the final solution?

The problem I had was trying to write a class deriving `ActionListener` for use with the AWT package - I had missed [the relevant section in the documentation](https://eta-lang.org/docs/user-guides/eta-user-guide/java-interop/java-generics#working-with-java-interfaces).

**Comment by jneira** [comment]
I think we could close this one, feel free to reopen if there is some pending question
