### ISSUE TITLE
show (0::Double) == "--0.0"

### ISSUE THREAD

**Issue by RossPaterson** [typelead/eta#841]
It should, of course, be "0.0".  The issue appears to result from `GHC.Float.isNegativeZero (0::Double)` being `True` in this implementation. The same is true of `Float`.

Tested on Debian buster x86_64.

**Comment by RossPaterson** [comment]
Ah, I see the underlying bug (in `isFloatNegativeZero` and `isDoubleNegativeZero`) was fixed as #649.

**Comment by rahulmutt** [comment]
We've been fixing many bugs recently - will be available in the next release :) You can build from source or use the docker image (which gets built for every commit on `master`) for now to play around.
