### ISSUE TITLE
Organise FFI Documentation

### ISSUE THREAD

**Issue by bradrn** [typelead/eta#844]
I've been to learn Eta from a Haskell background over the past few days, and I'm finding the docs to be really lovely with great coverage of the language. Unfortunately though, I've also found the FFI section to be quite poorly organised - and this is quite significant, as this is Eta's main (only, even?) divergence from Haskell. As a reference, here's the existing layout of the docs (simplified slightly):

```
# Basics
## Prerequisites
## Quick Start
## Defining a Java Wrapper Type
## The Java Sequenceable
## Java Foreign Import Declarations
## Exporting Eta Methods

# Java Wrapper Types
## General Syntax
## Examples of JWT
## Deriving Standard Typeclass Instances
## Marshalling Between Java and Eta Types
## Java Classes & Arrays

# Java Foreign Imports
## General Syntax
## Importing Instance Methods
## Importing Static Methods
## Importing Constructors
## Importing Instance Fields
## Importing Static Fields
## Working with the Java Monad

# Java Arrays and Subclasses
## Working With Arrays
## Primitive Arrays
## Object Arrays
## Working with Java Subclasses
## The Extends typeclass
## The Inherits type family
## Problem Resolution

# Java Generics and Enums
## Working With Java Generics
## Working With Java Enums
## Working with Variable Arguments
## Working with Java Converters
## Working With Java Interfaces
## Working With Covariance and Contravariance

# Java Dependencies
## Overview
## Adding Java Files
## Adding Maven Dependencies
```

With this as a reference, here's some things I particularly dislike about the organisation of the docs and some suggestions for improvement:
- The `Java Generics and Enums` seems to have turned into a 'catch-all' category for anything which doesn't quite fit into any of the other categories; I would transfer its sections to other pages where they make more sense. This actually impacted me: I almost gave up learning Eta (and started #838) when I couldn't figure out how to work with interfaces; I never even thought of looking under `Java Generics and Enums`, because it didn't seem relevant.
- Why are `Java Arrays and Subclasses` lumped together on the same page? I would split this into two pages.
- Why is `Working with the Java Monad` in the `Java Foreign Imports` page? I would have looked for it in `Basics`. I think this section should be merged with the other section in `Basics` called `The Java Monad`.
- The titles refer to both the Java _Monad_ and the Java _Sequenceable_, which are the same thing; this is a bit confusing.
- `Java Classes and Arrays` (under `Java Wrapper Types`) seems to be mislabeled; that section only contains one brief reference to arrays. In fact, it seems to cover very similar content as the previous section `Marshalling Between Java and Eta Types`, so I would merge them.

With this in mind, I would reorganise the docs as follows: (with notes on my changes at the right)

```
# Basics
## Prerequisites
## Quick Start
## Defining a Java Wrapper Type
## Working with Java Converters                  (moved from 'Java Generics and Enums')
## The Java Monad                                (renamed from 'The Java Sequenceable')
## Java Foreign Import Declarations
## Exporting Eta Methods

# Java Wrapper Types
## General Syntax
## Examples of JWT
## Deriving Standard Typeclass Instances
## Marshalling Between Java and Eta Types        (merged with following section 'Java Classes and Arrays')

# Java Foreign Imports
## General Syntax
## Importing Instance Methods
## Importing Static Methods
## Importing Constructors
## Importing Instance Fields
## Importing Static Fields
## Importing Java Generics                       (moved from 'Java Generics and Enums')
## Importing Java Enums                          (moved from 'Java Generics and Enums')
## Importing Variable Arguments                  (moved from 'Java Generics and Enums')
## Working With Java Interfaces                  (moved from 'Java Generics and Enums')

# Java Arrays                                    (split from 'Java Arrays and Subclasses')
## Working With Arrays
## Primitive Arrays
## Object Arrays

# Java Subclasses                                (split from 'Java Arrays and Subclasses')
## The Problem
## The Extends typeclass
## The Inherits type family
## Problem Resolution
## Working With Covariance and Contravariance    (moved from 'Java Generics and Enums')

# Java Dependencies
## Overview
## Adding Java Files
## Adding Maven Dependencies
```

**Comment by Jyothsnasrinivas** [comment]
@bradrn Thank you so much for the detailed response. I appreciate the effort you've taken to reorganize the sections. The main reason we've deferred these changes is that the upcoming [Direct Java Interop feature](https://github.com/typelead/eta/issues/647) will make these changes less relevant.

In the meantime, if you would like to update the documentation feel free to submit a PR. The docs are all in markdown format and can be found [here](https://github.com/typelead/eta/tree/master/docs/0-user-guides/0-eta-user-guide).

**Comment by bradrn** [comment]
You're welcome. I don't have much on, so I can have a go at implementing this today. One last suggestion: some older code uses the `CLASS` pragma which was removed recently, and it really confused me seeing what I thought was an 'undocumented feature', so I'm thinking it might also be a good idea to add a section about this pragma stating that it is deprecated.
