### ISSUE TITLE
org.bouncycastle:bcprov-jdk15on:1.59 not able to be used in Eta lang

### ISSUE THREAD

**Issue by politrons** [typelead/eta#848]
## Description
I add a new dependency in my project 

    compile eta('mysql-haskell:0.8.3.0')

But it's trying to download a transitive dependency org.bouncycastle:bcprov-jdk15on:1.59
  and it failing 

## Actual Behavior
Compilation fails since It cannot download dependecy

org.bouncycastle:bcprov-jdk15on:1.59

## Steps to Reproduce
Add this dependency 

    compile eta('mysql-haskell:0.8.3.0')

## Context
Building mysql-haskell-0.8.3.0 (lib)...

> Task :compileJava NO-SOURCE
> Task :compileEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.bouncycastle:bcprov-jdk15on:1.59.
  Searched in the following locations:
      file:/Users/pabloperezgarcia/.gradle/caches/etlas/org/bouncycastle/bcprov-jdk15on/1.59/bcprov-jdk15on-1.59.pom
      file:/Users/pabloperezgarcia/.gradle/caches/etlas/org/bouncycastle/bcprov-jdk15on/1.59/bcprov-jdk15on-1.59.jar
  Required by:
      project : > eta-0802:mysql-haskell:0.8.3.0-ab393c52a169ae1101343431b35d84e760768f536401e6d92c35f77aff0ca5f0 > eta-0802:cryptonite:0.24-cc4c5762a2c80533ddd00687b7c9fa536fba9416db0e75e819326b9694f40951

**Comment by rahulmutt** [comment]
In your `build.gradle` file, try adding this:
```
repositories {
  mavenCentral()
}
```

**Comment by politrons** [comment]
I just did but same problem. 

Here my project gradle.build https://github.com/politrons/Eta-Haskell-server/blob/master/build.gradle

**Comment by politrons** [comment]
Now adding this it seems to work

repositories {
    mavenCentral()
    maven {
        url "http://repo.akka.io/snapshots/"
    }
}

Thanks!
