### ISSUE TITLE
When we will have Base-4.10.1.0

### ISSUE THREAD

**Issue by politrons** [typelead/eta#849]
## Description

My program needs to use Base-4.10.1.0 The last one tat can be used is base:4.8.2.0 as far as I know

I know base since there're a some libraries as network:2.6.3.5 which is needed in my programing and is working with base-4.10.x 

Kudos for the hard and nice work!

**Comment by politrons** [comment]
Thanks, if I have time I will take a look. Otherwise normally how do you announce new versions normally?. Any estimation of when is the new binary release.

**Comment by Jyothsnasrinivas** [comment]
@politrons We typically announce on our blog, twitter, google groups and via GitHub releases. The next release is out you can go ahead and try it. The announcement will be done in couple of hours. 

```gradle
eta {
  version = '0.8.6b1'
  etlasVersion = '1.5.0.0'
}
```

**Comment by politrons** [comment]
I´m afraid with the new configuration and dependencies is not working

My build.gradle

```
plugins {
    id 'com.typelead.eta' version '0.7.7'
    id 'application'
}

eta {
    version = '0.8.6b1'
    etlasVersion = '1.5.0.0'
}

repositories {
    mavenCentral()
    maven {
        url "http://repo.akka.io/snapshots/"
    }
}


dependencies {
    compile eta('aeson:1.2.4.0')
    compile eta('scotty:0.11.1')
    compile eta('text:1.2.3.0')
    compile eta('io-streams:1.5.0.1')
    compile eta('bytestring:0.10.8.2')
    compile eta('network:2.6.3.5')
    compile eta('mysql-haskell:0.8.3.0')

}
```

And the error

```
> Task :setupEnvironmentEta
> Task :resolveDependenciesEta
Building cereal-0.5.7.0 (lib)...
Building bsb-http-chunked-0.0.0.2 (lib)...
Building ansi-terminal-0.8.0.4 (lib)...
Building foundation-0.0.19 (lib)...
Building text-1.2.3.0 (lib)...
Building time-locale-compat-0.1.1.4 (lib)...
Building transformers-0.5.5.0 (all, legacy fallback)...
Building unix-2.7.2.2 (lib)...
Building word24-2.0.1 (lib)...
> Task :installDependenciesEta

etlas: Failed to build unix-2.7.2.2 (which is required by scotty-0.11.1 and
mysql-haskell-0.8.3.0). See the build log above for details.

> Task :installDependenciesEta FAILED

```

**Comment by Jyothsnasrinivas** [comment]
@politrons  Can you use `network:2.6.3.2` instead of `network:2.6.3.5` since Eta has a patch for `v2.6.3.2`? 

You can check which version of package to use from the [eta-hackage list](https://github.com/typelead/eta-hackage)

For any further questions can you please open a new issues? Thanks!
