### ISSUE TITLE
Eta cannot find GMP library

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta#850]
Under Ubuntu 16.04:

jamie@jamie-box:~/eta$ ./cleaninstall.sh 

'--local-bin-path' will be removed in a future release.
Please use '--local-bin' instead.

Warning: Cabal file warning in /home/jamie/eta/libraries/eta-repl/eta-repl.cabal@ 39:8: Unknown field: "java-sources"
Copying from /home/jamie/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta to /home/jamie/.local/bin/eta
Copying from /home/jamie/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta-build to /home/jamie/.local/bin/eta-build
Copying from /home/jamie/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/eta-pkg to /home/jamie/.local/bin/eta-pkg
Copying from /home/jamie/eta/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin/etlas to /home/jamie/.local/bin/etlas

Copied executables to /home/jamie/.local/bin:
- eta
- eta-build
- eta-pkg
- etlas
Cleaning files in rts/build, libraries/*/dist
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
# etlas (for clean)
cleaning...
Build completed in 0:01m
# eta (for uninstall)
Cleaning files in /home/jamie/.eta/0.8.0.2
Build completed in 0:01m
# eta (for install)
# git (for install)
# eta-pkg (for install)
# etlas (for install)
Downloading the latest package lists from:
- hackage.haskell.org
- git@github.com/typelead/etlas-index
Updating binary package index.
To revert to previous state run:
    etlas update --index-state='2018-08-17T05:24:56Z'
Updating the eta-hackage patch set.
# etlas (for install)
Will select the version of Eta available on the PATH.
# javac (for install)
# javac (for libraries/rts/build/rts.jar)
Note: eta/runtime/storage/ManagedHeap.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
# jar (for libraries/rts/build/rts.jar)
# etlas (for install)
Resolving dependencies...
Configuring rts-0.1.0.0...
Building rts-0.1.0.0...
Installed rts-0.1.0.0
# etlas (for install)
Resolving dependencies...
Configuring ghc-prim-0.4.0.0...
Building ghc-prim-0.4.0.0...
Installed ghc-prim-0.4.0.0
# etlas (for install)
Resolving dependencies...
Configuring integer-0.5.1.0...
Building integer-0.5.1.0...
Installed integer-0.5.1.0
# etlas (for install)
Resolving dependencies...
Configuring base-4.8.2.0...
Building base-4.8.2.0...
Failed to install base-4.8.2.0
Build log ( /home/jamie/.etlas/logs/eta-0.8.0.2/base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF.log ):
etlas: Entering directory '.'
Configuring base-4.8.2.0...
Preprocessing library for base-4.8.2.0..
Building library for base-4.8.2.0..
warning: [options] bootstrap class path not set in conjunction with -source 1.7
java-utils/Utils.java:164: error: package eta.ghc_prim does not exist
        return new String(eta.ghc_prim.Utils.byteBufferToBytes(address, len), "UTF-8");
                                      ^
1 error
1 warning

etlas: Leaving directory '.'
etlas: Error: some packages failed to install:
base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF failed during the building phase. The
exception was:
ExitFailure 1
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: etlas install --allow-boot-library-installs
Current directory: /home/jamie/eta/libraries/base
Exit code: 1
Stderr:
etlas: Error: some packages failed to install:
base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF failed during the building phase. The
exception was:
ExitFailure 1
)

jamie@jamie-box:~/eta$ etlas install --allow-boot-library-installs
Resolving dependencies...
etlas: Could not resolve dependencies:
trying: base-4.11.1.0:-integer-gmp
trying: base-4.11.1.0:-integer-simple
unknown package: invalid-cabal-flag-settings (dependency of
base-4.11.1.0:-integer-simple)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, eta, rts, base-4.10.0.0:flag,
base-4.10.1.0:flag, base-4.11.0.0:flag, base-4.11.1.0:flag,
invalid-cabal-flag-settings

**Comment by rahulmutt** [comment]
Which JVM version are you using?

```
java -version
```

**Comment by jstr045329** [comment]
$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by rahulmutt** [comment]
There have been known issues with using Java 9 and Eta. I suggest you use Java 8 or earlier using an environment managed like `jenv`.

**Comment by jstr045329** [comment]
This might be a dumb question but does it matter whether Java 8 is jdk or jre?

**Comment by rahulmutt** [comment]
You need JDK 8 if you want to build Eta from source

**Comment by jstr045329** [comment]
Now I have this:

$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Is that the proper version?

**Comment by rahulmutt** [comment]
Yes that should work!

**Comment by jstr045329** [comment]
Thanks! At this point I've 1) compiled eta from source, 2) removed etlas, 3) downloaded the latest etlas binary, 4) etlas repl works, 5) built scotty from source.

Now I'm trying to run eta-scotty-example, and I get this error:

~/eta-scotty-example$ etlas run
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - blaze-html-0.9.1.1 (lib) (requires build)
 - scotty-0.11.2 (lib) (requires build)
 - shakespeare-2.0.15 (lib) (requires build)
 - eta-scotty-0.1.0.0 (exe:eta-scotty) (first run)
Configuring scotty-0.11.2 (lib)...
Configuring blaze-html-0.9.1.1 (lib)...
Building blaze-html-0.9.1.1 (lib)...
Building scotty-0.11.2 (lib)...
Configuring shakespeare-2.0.15 (lib)...
Building shakespeare-2.0.15 (lib)...
Configuring executable 'eta-scotty' for eta-scotty-0.1.0.0..
Preprocessing executable 'eta-scotty' for eta-scotty-0.1.0.0..
Building executable 'eta-scotty' for eta-scotty-0.1.0.0..
<command line>: cannot satisfy -package-id file-embed-0.0.11-12c7a216d538925924fa61f79c7ac82955b0fa824803cf28c43757a3dc0efea3: 
    file-embed-0.0.11-12c7a216d538925924fa61f79c7ac82955b0fa824803cf28c43757a3dc0efea3 is unusable due to shadowed dependencies:
      base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF bytestring-0.10.8.2-BqFm4sXW1c7Fp5KyxfOs0Q directory-1.3.1.0-AeQsWT2nS0X49209NbRrSf template-haskell-2.11.1.0-KHMuAbu0DUK68xFSb1WRG5 filepath-1.4.1.2-Al6mhtc5hYQA8GQj9QvIKg
    (use -v for more information)

**Comment by rahulmutt** [comment]
@jstr045329 Why did you have to remove etlas in between?

**Comment by jstr045329** [comment]
When I typed etlas repl, I got an error that there is a version mismatch between etlas and eta.

**Comment by rahulmutt** [comment]
Ok run the following commands in your Eta clone and let me know if it works:

```
$ rm -rf ~/.etlas/store
$ git checkout master
$ git pull
$ git submodule update --init --recursive
$ ./install.sh 
```

**Comment by jstr045329** [comment]
git checkout master gives

error: pathspec 'master' did not match any file(s) known to git.

**Comment by jstr045329** [comment]
git branch shows:

* stable

**Comment by shirouto** [comment]
You may have cloned the stable branch. It should work too. Just continue with the rest
```
$ git pull
$ git submodule update --init --recursive
$ ./cleaninstall.sh
```
If however you wanna live on the edge, then you first need to switch to ```master```:
```
$ git fetch origin master
$ git remote update
$ git fetch --all
$ git checkout -b master origin/master
```
and then you can continue with the above.

Of course, you can always start from scratch and clone the master directly...

**Comment by jstr045329** [comment]
@shirouto it worked! Thank you! I had to git checkout origin/master somewhere in the above string of git commands, but I'm hacking again :)

**Comment by rahulmutt** [comment]
@jstr045329 As this issue looks resolved, I'm closing this. Feel free to file more issues as you encounter problems.
