### ISSUE TITLE
Provide a switch to skip writing of metrics/events.log

### ISSUE THREAD

**Issue by jin** [typelead/eta#853]
## Description

I'm writing a Bazel rule for Eta compilation, and due to the strict permissions in Bazel's interaction with external dependencies (`~/.eta` and `~/.etlas`), the Eta compiler is unable to create a new directory at `~/.eta/<version>/metrics` and write the `events.log` file.

## Expected Behavior

```
...
✓ Successfully built 1 module. Keep Hustling!
```

## Actual Behavior

```
...
✓ Successfully built 1 module. Keep Hustling!
eta: /Users/jingwen/.eta/0.8.0.2/metrics: createDirectory: permission denied (Operation not permitted)
Target //:main failed to build
```

## Steps to Reproduce

N/A, this feature request will involve not writing to an external directory after a compilation as a side effect.

Or, allow customizing the location of the `metrics` directory.

## Context

Writing Bazel rules for Eta.

## Your Environment

* Did you install an older version of Eta/Etlas before? No
* Current Eta & Etlas version: eta-0.8.0.2, etlas version 1.4.0.0, compiled using version 2.1.0.0 of the etlas-cabal library
* Operating System and version: macOS High Sierra
* Link to your project: N/A

**Comment by puffnfresh** [comment]
This would help with my Nix code too. I've got `send-metrics: False` in my config but I think directory is still created.

**Comment by jin** [comment]
Customising the locations of the two directories will be nice to have, but not a necessity.

The issue here is with performing writes to somewhere external to the build as a side effect during compilation time. Bazel keeps track of all outputs during an action, which is just `eta Main.hs` in this case.

**Comment by Jyothsnasrinivas** [comment]
So what we can do is add a flag `-metricsdir` to specify where metrics data should be written.

**Comment by jin** [comment]
Wow that was super quick, thank you @Jyothsnasrinivas!

**Comment by Jyothsnasrinivas** [comment]
@jin I've added the `-metricsDir` flag. If you run `eta -metricsDir somdir Main.hs`, it will dump the metrics in `somedir/event.log`, creating the specified directory if it doesn't already.
