### ISSUE TITLE
newest eta fails to build on OS X Sierra

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta#859]
$ git pull origin master
remote: Counting objects: 211, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 211 (delta 128), reused 211 (delta 128), pack-reused 0
Receiving objects: 100% (211/211), 24.74 KiB | 8.25 MiB/s, done.
Resolving deltas: 100% (128/128), completed with 66 local objects.
From https://github.com/typelead/eta
 * branch              master     -> FETCH_HEAD
   093de170..c90f1bbf  master     -> origin/master
Fetching submodule etlas
From https://github.com/typelead/etlas
   9a0399f..a97e19d  master     -> origin/master
 * [new branch]      use-internal-setup-method -> origin/use-internal-setup-method
 * [new tag]         1.4.0.0    -> 1.4.0.0
 * [new tag]         1.5.0.0    -> 1.5.0.0
Updating 093de170..c90f1bbf
Fast-forward
 README.md                                                                                 |   6 +--
 compiler/Eta/Main/DynFlags.hs                                                             |   8 +++-
 compiler/Eta/Main/GHC.hs                                                                  |  39 ++++++++++--------
 compiler/Eta/Main/HscTypes.hs                                                             |  19 +++++++--
 compiler/Eta/Main/Packages.hs                                                             |   6 +--
 compiler/Eta/Main/StaticFlags.hs                                                          |  16 +++++++-
 compiler/Eta/Main/SysTools.hs                                                             |   9 ++++-
 compiler/Eta/Prelude/PrelNames.hs                                                         |  15 ++++---
 compiler/Eta/TypeCheck/TcRnDriver.hs                                                      |  41 ++++++++++---------
 compiler/Eta/TypeCheck/TcRnMonad.hs                                                       |   7 ++++
 docs/0-user-guides/0-eta-user-guide/1-installation/2-etlas.md                             |   8 ++--
 docs/0-user-guides/0-eta-user-guide/1-installation/3-source.md                            |  13 +++++-
 docs/0-user-guides/0-eta-user-guide/2-basics/0-quick-start.md                             |   6 +--
 docs/0-user-guides/1-etlas-user-guide/1-installation/1-binary.md                          |   8 ++--
 docs/0-user-guides/1-etlas-user-guide/4-advanced-features/2-cabal-project-file.md         |   2 +-
 docs/0-user-guides/1-etlas-user-guide/5-command-reference/0-global-flags.md               |   2 +-
 docs/0-user-guides/2-gradle-user-guide/1-basic-configuration/2-plugin-basics.md           |   6 +--
 docs/0-user-guides/2-gradle-user-guide/2-advanced-configuration/1-global-configuration.md |  24 +++++------
 eta-serv/eta-serv.cabal                                                                   |   2 +-
 eta.cabal                                                                                 |   2 +-
 eta/Eta/REPL/UI.hs                                                                        |  18 ++++-----
 eta/Main.hs                                                                               |  32 ++++++---------
 etlas                                                                                     |   2 +-
 libraries/base/Eta/RTS.hs                                                                 |  16 +++++++-
 libraries/base/java-utils/Utils.java                                                      |  20 +++++++++
 libraries/eta-boot-meta/eta-boot-meta.cabal                                               |   2 +-
 libraries/eta-boot/eta-boot.cabal                                                         |   2 +-
 libraries/eta-meta/eta-meta.cabal                                                         |   2 +-
 libraries/eta-repl/eta-repl.cabal                                                         |   2 +-
 rts/src/main/java/eta/runtime/exception/RuntimeInternalError.java                         |   2 +-
 rts/src/main/java/eta/runtime/stg/Capability.java                                         |   6 ++-
 rts/src/main/java/eta/runtime/storage/ManagedHeap.java                                    |  27 +++++++------
 rts/src/main/java/eta/runtime/util/MPSCLongQueue.java                                     | 249 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------
 rts/src/test/java/eta/runtime/util/MPSCLongQueueTest.java                                 | 208 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------
 runtests.sh                                                                               |   7 ++++
 tests/suite/Driver.hs                                                                     |   3 +-
 tests/suite/templateHaskell/{run => compile}/TH_repGuard.hs                               |   3 +-
 tests/suite/templateHaskell/{run => compile}/TH_repGuard.stdout                           |   0
 tests/suite/templateHaskell/{run => compile}/TH_repPrim.hs                                |   2 +-
 tests/suite/templateHaskell/{run => compile}/TH_repPrim.stdout                            |   0
 tests/suite/templateHaskell/{run => compile}/TH_repPrim2.hs                               |   2 +-
 tests/suite/templateHaskell/{run => compile}/TH_repPrim2.stdout                           |   0
 tests/suite/typecheck/fail/tcfail133.stderr                                               |   2 +-
 utils/eta-pkg/eta-pkg.cabal                                                               |   2 +-
 44 files changed, 594 insertions(+), 254 deletions(-)
 create mode 100755 runtests.sh
 rename tests/suite/templateHaskell/{run => compile}/TH_repGuard.hs (96%)
 rename tests/suite/templateHaskell/{run => compile}/TH_repGuard.stdout (100%)
 rename tests/suite/templateHaskell/{run => compile}/TH_repPrim.hs (98%)
 rename tests/suite/templateHaskell/{run => compile}/TH_repPrim.stdout (100%)
 rename tests/suite/templateHaskell/{run => compile}/TH_repPrim2.hs (98%)
 rename tests/suite/templateHaskell/{run => compile}/TH_repPrim2.stdout (100%)

$ git branch
* master

$ etlas build
Resolving dependencies...
etlas: Could not resolve dependencies:
trying: eta-0.8.6.2 (user goal)
next goal: transformers-compat (dependency of optparse-applicative-0.14.0.0)
rejecting: transformers-compat-0.6.2/installed-6jA...,
transformers-compat-0.6.2, transformers-compat-0.6.1.6,
transformers-compat-0.6.1.5, transformers-compat-0.6.1.4,
transformers-compat-0.6.1.3, transformers-compat-0.6.1.2,
transformers-compat-0.6.0.6, transformers-compat-0.6.0.5,
transformers-compat-0.6.0.4, transformers-compat-0.6.0.3,
transformers-compat-0.6.0.2 (conflict: optparse-applicative =>
transformers-compat>=0.3 && <0.6)
trying: transformers-compat-0.5.1.4
trying: vector-0.12.0.1/installed-5ei... (dependency of ListLike-4.6)
next goal: semigroups (dependency of eta-0.8.6.2)
rejecting: semigroups-0.18.5/installed-1XY... (conflict:
transformers-compat==0.5.1.4, semigroups =>
transformers-compat==0.6.2/installed-6jA...)
rejecting: semigroups-0.18.5, semigroups-0.18.4, semigroups-0.18.3,
semigroups-0.18.2, semigroups-0.18.1, semigroups-0.18.0.1, semigroups-0.18,
semigroups-0.17.0.1, semigroups-0.17, semigroups-0.16.2.2,
semigroups-0.16.2.1, semigroups-0.16.2, semigroups-0.16.1,
semigroups-0.16.0.1, semigroups-0.16, semigroups-0.15.4, semigroups-0.15.3,
semigroups-0.15.2, semigroups-0.15.1, semigroups-0.15, semigroups-0.14,
semigroups-0.13.0.1, semigroups-0.13, semigroups-0.12.2, semigroups-0.12.1,
semigroups-0.12.0.1, semigroups-0.12, semigroups-0.11, semigroups-0.10,
semigroups-0.9.2, semigroups-0.9.1, semigroups-0.9, semigroups-0.8.5,
semigroups-0.8.4.1, semigroups-0.8.4, semigroups-0.8.3.2, semigroups-0.8.3.1,
semigroups-0.8.3, semigroups-0.8.2, semigroups-0.8.0.1, semigroups-0.8,
semigroups-0.7.1.2, semigroups-0.7.1.1, semigroups-0.7.1, semigroups-0.7.0,
semigroups-0.6.1, semigroups-0.6, semigroups-0.5.0.2, semigroups-0.5.0.1,
semigroups-0.5.0, semigroups-0.4.0, semigroups-0.3.4.2, semigroups-0.3.4.1,
semigroups-0.3.4, semigroups-0.3.3, semigroups-0.3.2, semigroups-0.3.1,
semigroups-0.3.0, semigroups-0.2.0, semigroups-0.1.0 (conflict: vector =>
semigroups==0.18.5/installed-1XY...)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: eta-build, etlas-cabal

**Comment by rahulmutt** [comment]
@jstr045329 Are you trying to build Eta with Eta? That is not supported yet, see #423.

**Comment by jneira** [comment]
Hi and thanks for try eta, it seems you are trying to build eta with etlas/eta itself and i am afraid that is not possible yet, see https://github.com/typelead/eta/issues/423). For now etlas/eta should be built using stack/ghc, you can check the steps (including the checkout, that involves use git submodule) here: https://eta-lang.org/docs/user-guides/eta-user-guide/installation/source.

**Comment by rahulmutt** [comment]
Closing as the issue as it appears to be resolved. Feel free to open a new issue if not.
