### ISSUE TITLE
:setupEnvironmentEta FAILED after ./gradlew run in docker 

### ISSUE THREAD

**Issue by mruzekw** [typelead/eta#860]
## Description

I ran `./gradlew run` in the provided docker container, and it kept failing to install.

**Run 1**

```
> Task :setupEnvironmentEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupEnvironmentEta'.
> No value has been specified for this provider.
```

**Run 2**

```
> Task :setupEnvironmentEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupEnvironmentEta'.
> Nonzero (1) exit code for command [/root/.gradle/caches/etlas/1.5.0.0/etlas, --select-eta=0.8.6b1, update] with workingDir null
```

**Run 3 after `etlas update`**

```
etlas: Unable to find eta-0.8.6.1 in any of your configured binary indices.
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupEnvironmentEta'.
> Nonzero (1) exit code for command [/root/.gradle/caches/etlas/1.5.0.0/etlas, --select-eta=0.8.6b1, update] with workingDir null
```

## Expected Behavior

A running app/script.

## Actual Behavior

"Execution failed for task ':setupEnvironmentEta'."

## Possible Fix

Not sure.

## Steps to Reproduce

```
$ docker run -it typelead/eta
# git clone https://github.com/typelead/eta-init
# cd eta-init
# ./gradlew run
# ./gradlew run
# etlas update
# ./gradlew run
```

## Context

I wanted to try out Eta. I'm not a JVM expert, so I'm not sure where to go from here.

## Your Environment
* Did you install an older version of Eta/Etlas before?

  - No. Fresh docker container.

* Current Eta & Etlas version:
  - etlas version 1.5.0.0 (compiled using version 2.1.0.0 of the etlas-cabal library)
  - The Eta Programming Language Compiler, Version 0.8.6b2

* Operating System and version:

  - Mac OS X 10.13 + Docker 18.03.1-ce-mac65 (24312)

* Link to your project: N/A

**Comment by rahulmutt** [comment]
Since you're in the Docker container, you already have `eta` and `etlas` provided, so in `eta-init/build.gradle` you can do the following:

```
eta {
  useSystemEta = true
  useSystemEtlas = true
}
```

If you don't put those settings above, it will try to install the binary version of Eta *again*. When installing binaries, it checks the platform to make sure you get the right binaries. I think it's failing because a Docker container is not a recognized platform for a binary (yet).

**Comment by mruzekw** [comment]
Thanks! That makes sense, and it works.
