### ISSUE TITLE
Improve the test driver for fail

### ISSUE THREAD

**Issue by shirouto** [typelead/eta#865]
The present test driver ```tests/suite/Driver.hs``` will simply concatenate the ```stdout``` and ```stderr``` on runtime error, so one will have to include the entire stacktrace into the ```.stdout``` file for the ```run``` target. This makes for cumbersome and brittle test cases having to update the test checks on tests updates and runtime updates.

Truncating the stderr stacktrace  could help. Also, having a separate runtime error target can also further help.

**Comment by Jyothsnasrinivas** [comment]
@shirouto Thanks for the suggestion. This is something we wanted ourselves but we haven't had the time to implement it.
