### ISSUE TITLE
Request: Documentation on using Eta compiled code from Java

### ISSUE THREAD

**Issue by adamschoenemann** [typelead/eta#873]
You have some good documentation on using Java code from Eta, but I cannot find any documentation on using Eta code from Java (or Kotlin in my case). I can include the compiled jar on the classpath, but I cannot figure out how to call this code properly, since the methods I get seem to require a lot of plumbing from the runtime. I'm sure there's a simple way to do it, but I can't find anything in the docs. Could you help me out? 

Thanks!

**Comment by jneira** [comment]
Hi, i am afraid that use directly automatic generated classes by eta in java is cumbersome. There is a way to export classes/methods documented [here](https://eta-lang.org/docs/user-guides/eta-user-guide/java-interop/java-interop-basics#exporting-eta-methods) (including java examples!).
Besides that, there is plans to export eta types automatically to java, tracked in [this issue](https://github.com/typelead/eta/issues/690#issuecomment-370685918).
Hope it helps!

**Comment by adamschoenemann** [comment]
Thanks for the answer and the link! I don't know how I missed it.

**Comment by jneira** [comment]
Well, maybe the docs for exporting eta methods should be in its own section (like imports) to make it more relevant
