### ISSUE TITLE
Win7+JDK10; etlas.exe: Unable to find any Eta binaries for your platform.

### ISSUE THREAD

**Issue by g-pechorin** [typelead/eta#880]
## Description

I'm trying to setup/use eta through Gradle.
I've followed the online instructions, but, get errors rather than a running program.
The errors seem to indicate that Windows7 or JDK10 aren't recognized.

## Expected Behavior

I would expect [the quickstart example](https://eta-lang.org/docs/user-guides/eta-user-guide/installation/gradle) to print a message about the 101st prime.

## Actual Behavior

```

    > Task :setupEnvironmentEta
    Installing Eta v0.8.6b2

    To revert to previous state run:
        etlas update --index-state='2018-09-12T18:10:41Z'
    Updating the eta-hackage patch set.
    etlas.exe: Unable to find eta-0.8.6.2 in any of your configured binary
    indices.

    Run `etlas update` and try again.
    If that doesn't work, please report this as a bug at

    https://github.com/typelead/eta/issues/new

    specifying your Etlas version.

    > Task :setupEnvironmentEta FAILED

    FAILURE: Build failed with an exception.
```

## Possible Fix

Unsure.

### `git clone git@github.com:typelead/eta-init.git && cd eta-init && gradlew run -PetaSendMetrics=false`

    Cloning into 'eta-init'...
    remote: Counting objects: 87, done.
    remote: Compressing objects: 100% (6/6), done.
    emote: Total 87 (delta 2), reused 5 (delta 2), pack-reused 78Receiving objects:  42% (37/87)
    Receiving objects: 100% (87/87), 73.56 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (37/37), done.
    Checking connectivity... done.
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/C:/Users/Peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradl
    e-4.9/lib/gradle-base-services-4.9.jar) to method java.lang.ClassLoader.getPackages()
    WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    Downloading the latest package lists from:
    - hackage.haskell.org
    - git@github.com/typelead/etlas-index
    Updating binary package index.

    > Task :setupEnvironmentEta
    Installing Eta v0.8.6b2

    To revert to previous state run:
        etlas update --index-state='2018-09-12T18:10:41Z'
    Updating the eta-hackage patch set.
    etlas.exe: Unable to find eta-0.8.6.2 in any of your configured binary
    indices.

    Run `etlas update` and try again.
    If that doesn't work, please report this as a bug at

    https://github.com/typelead/eta/issues/new

    specifying your Etlas version.

    > Task :setupEnvironmentEta FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':setupEnvironmentEta'.
    > Nonzero (1) exit code for command [C:\Users\Peter\.gradle\caches\etlas\1.5.0.0\etlas.exe, --disable-send-metrics, --select-eta=0.8.6b2, update] with workingDir null

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 20s
    1 actionable task: 1 executed

### `C:\Users\Peter\.gradle\caches\etlas\1.5.0.0\etlas.exe --select-eta=0.8.6b2 update`

    Downloading the latest package lists from:
    - hackage.haskell.org
    - git@github.com/typelead/etlas-index
    Updating binary package index.
    To revert to previous state run:
        etlas update --index-state='2018-09-12T19:39:12Z'
    Updating the eta-hackage patch set.
    etlas.exe: Unable to find eta-0.8.6.2 in any of your configured binary
    indices.

    Run `etlas update` and try again.
    If that doesn't work, please report this as a bug at

    https://github.com/typelead/eta/issues/new

    specifying your Etlas version.

### `C:\Users\Peter\.gradle\caches\etlas\1.5.0.0\etlas.exe update`

    Downloading the latest package lists from:
    - hackage.haskell.org
    - git@github.com/typelead/etlas-index
    To revert to previous state run:
        etlas update --index-state='2018-09-12T19:39:12Z'
    Updating binary package index.
    Updating the eta-hackage patch set.
    Discovering the installation paths for your Eta executables...
    No existing installation found for 'eta'.
    Attempting to download binaries...
    etlas.exe: Unable to find any Eta binaries for your platform.
    Run `etlas update` and try again.
    If that doesn't work, please report this as a bug at

    https://github.com/typelead/eta/issues/new

    specifying your Etlas version.                                       

## Context

I was unable to use eta.

## Your Environment

* Did you install an older version of Eta/Etlas before?
  - No
* Current Eta & Etlas version:
  - I haven't installed eta/etlas
* Operating System and version:
  - Windows 7 amd64
* Link to your project:
  - https://github.com/typelead/eta-init

**Comment by jneira** [comment]
Hi and thanks for trying eta. 
Could you share the output of `C:\Users\Peter\.gradle\caches\etlas\1.5.0.0\etlas update -v3`? It should print info about the urls tried to download eta binaries

**Comment by rahulmutt** [comment]
@g-pechorin JDK 10 is most likely the issue. Try using a tool like [jenv](http://www.jenv.be/) and install with Java 8.

**Comment by g-pechorin** [comment]
Tried again at work (Ubuntu18.04  JDK10)

Looks like ... yeah; eta doesn't work with the current JDK


# `peter@workbuntu:~/Desktop$ git clone git@github.com:typelead/eta-init.git && cd eta-init && ./gradlew run -PetaSendMetrics=false`

    Cloning into 'eta-init'...
    remote: Counting objects: 87, done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 87 (delta 2), reused 5 (delta 2), pack-reused 78
    Receiving objects: 100% (87/87), 73.56 KiB | 846.00 KiB/s, done.
    Resolving deltas: 100% (37/37), done.
    Downloading https://services.gradle.org/distributions/gradle-4.9-bin.zip
    ........................................................................
    Unzipping /home/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip to /home/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t
    Set executable permissions for: /home/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9/bin/gradle

    Welcome to Gradle 4.9!

    Here are the highlights of this release:
     - Experimental APIs for creating and configuring tasks lazily
     - Pass arguments to JavaExec via CLI
     - Auxiliary publication dependency support for multi-project builds
     - Improved dependency insight report

    For more details see https://docs.gradle.org/4.9/release-notes.html

    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/home/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9/lib/gradle-base-services-4.9.jar) to method java.lang.ClassLoader.getPackages()
    WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    Download https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.9/com.typelead.eta.gradle.plugin-0.7.9.pom
    Download https://plugins.gradle.org/m2/gradle/plugin/com/typelead/gradle-eta/0.7.9/gradle-eta-0.7.9.pom
    Download https://plugins.gradle.org/m2/gradle/plugin/com/typelead/gradle-eta/0.7.9/gradle-eta-0.7.9.jar

    > Task :setupEnvironmentEta
    Downloading etlas from: http://cdnverify.eta-lang.org/eta-binaries/etlas-1.5.0.0/binaries/x86_64-linux/etlas ; caching to /home/peter/.gradle/caches/etlas/1.5.0.0/etlas

    > Task :setupEnvironmentEta FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':setupEnvironmentEta'.
    > No value has been specified for this provider.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 19s
    1 actionable task: 1 executed

**Comment by g-pechorin** [comment]
... or a Mac with JDK9 ...

    $ java -version
        java version "9.0.4"
        Java(TM) SE Runtime Environment (build 9.0.4+11)
        Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
    $ git clone git@github.com:typelead/eta-init.git && cd eta-init && ./gradlew run -PetaSendMetrics=false
        Cloning into 'eta-init'...
        remote: Counting objects: 87, done.
        remote: Compressing objects: 100% (6/6), done.
        remote: Total 87 (delta 2), reused 5 (delta 2), pack-reused 78
        Receiving objects: 100% (87/87), 73.56 KiB | 627.00 KiB/s, done.
        Resolving deltas: 100% (37/37), done.
        Downloading https://services.gradle.org/distributions/gradle-4.9-bin.zip
        ........................................................................
        Unzipping /Users/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip to /Users/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t
        Set executable permissions for: /Users/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9/bin/gradle

        Welcome to Gradle 4.9!

        Here are the highlights of this release:
         - Experimental APIs for creating and configuring tasks lazily
         - Pass arguments to JavaExec via CLI
         - Auxiliary publication dependency support for multi-project builds
         - Improved dependency insight report

        For more details see https://docs.gradle.org/4.9/release-notes.html

        WARNING: An illegal reflective access operation has occurred
        WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/Users/peter/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9/lib/gradle-base-services-4.9.jar) to method java.lang.ClassLoader.getPackages()
        WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
        WARNING: All illegal access operations will be denied in a future release
        Download https://plugins.gradle.org/m2/com/typelead/eta/com.typelead.eta.gradle.plugin/0.7.9/com.typelead.eta.gradle.plugin-0.7.9.pom
        Download https://plugins.gradle.org/m2/gradle/plugin/com/typelead/gradle-eta/0.7.9/gradle-eta-0.7.9.pom
        Download https://plugins.gradle.org/m2/gradle/plugin/com/typelead/gradle-eta/0.7.9/gradle-eta-0.7.9.jar

        > Task :setupEnvironmentEta
        Downloading etlas from: http://cdnverify.eta-lang.org/eta-binaries/etlas-1.5.0.0/binaries/x86_64-osx/etlas ; caching to /Users/peter/.gradle/caches/etlas/1.5.0.0/etlas

        > Task :setupEnvironmentEta FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':setupEnvironmentEta'.
        > No value has been specified for this provider.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 1m 27s
        1 actionable task: 1 executed
