### ISSUE TITLE
[eta-tour]: Bug - The current version of Eta is v0.7.0b2.

### ISSUE THREAD

**Issue by rolandtritsch** [typelead/eta#882]
https://tour.eta-lang.org/start#3

Link the version to a/the github/doc page to make sure the version is always current.

**Comment by Jyothsnasrinivas** [comment]
@rolandtritsch Thanks for reporting. We could fix this in the coming version of Eta.

**Comment by rolandtritsch** [comment]
Outdated. Closing.
