### ISSUE TITLE
[eta-tour]: Bug - [description-here]

### ISSUE THREAD

**Issue by arhont375** [typelead/eta#884]
Source Code:
```haskell
main :: IO ()
main = do
  print $ [1, 2, 3, 4, 5]    [6, 7, 8, 9, 0]
  print $ "hello"    " "    "world"
  print $ ['w', 'h']    ['a', 't']
  print $ null []
  print $ null ""
  print $ length [32,43,120]
  print $ take 5 [1,5..100]
  print $ drop 5 [2,2..10]   -- This line I changed, originally was drop 5 [1, 2..10]
  print $ replicate 5 "AB"
  print $ head [1..10]
  print $ tail [1..10]
  print $ init [1..10]
  print $ last [1..10]
```

Output:
```shell
```

[write-further-description-here]
Seems like this program creating some exceptions or something, after that I can't get result of any program in tour (always request timeout).

**Comment by Jyothsnasrinivas** [comment]
@arhont375 Thanks for reporting. The problem with the list `[2,2..10]` is that it's an infinite list of 2's. So what happened was it printed indefinitely and eventually timed out. 

The one thing we could do is to improve the error message, but we probably won't have time to get around it anytime soon. So closing this issue.
