### ISSUE TITLE
[eta-tour]: Bug - execution of Sequenceable part 9/12 failed

### ISSUE THREAD

**Issue by stefanscheidt** [typelead/eta#887]
Source Code:
```haskell
import Text.Read

readInt :: String -> Maybe Int
readInt = readMaybe

addNonNegative :: Int -> Maybe Int
addNonNegative n
  | n >= 0    = Just $ n   100
  | otherwise = Nothing

addStringInt :: String -> Maybe Int
addStringInt str =
  case readMaybe str of
    Nothing  -> Nothing
    Just int -> addNonNegative int

main :: IO ()
main = print $ addStringInt "123"
```

Output:
```shell
```

SImply executing the sample failed after some time waiting for compiling and executing.

**Comment by shirouto** [comment]
Well, I cannot reproduce the issue. Two points though:

1. The code above does not compile as you have it here. Inside ``addNonNegative`` you should have ``n + 100`` (I guess). Probably some character encoding got scrambled while you copied and pasted. Once you make that change though, the code should compile and run as it is.

2. Your ``readInt`` is redundant, as you never use it. This should not affect successful compilation and execution though.

If you still run into this, might want to add some details on your ``eta`` and ``etlas`` versions, as well as specifics on how you build/run this code.

**Comment by stefanscheidt** [comment]
The code is the code from the Tour of Eta, executed in "the browser".
Now it works fine, probably just a hickup of the backend of the Tour of Eta.
