### ISSUE TITLE
Nix build: 'eta-build-shell' not found

### ISSUE THREAD

**Issue by guillaumecherel** [typelead/eta#895]
Following the [installation instructions](https://eta-lang.org/docs/user-guides/eta-user-guide/installation/nix) for installing eta with Nix fails.

## Description

I tried running 

```
$ git clone --recursive --depth 1 https://github.com/typelead/eta
$ cd eta
$ nix-shell -A eta-build-shell
```

## Expected Behavior

It should start the interactive nix shell.

## Actual Behavior

The command fails with the message:

> error: attribute 'eta-build-shell' in selection path 'eta-build-shell' not found

## Steps to Reproduce

Follow the eta installation instructions with Nix.

## Context

I was trying to install eta.

## Your Environment

* Did you install an older version of Eta/Etlas before?
No

* Current Eta & Etlas version:
* Operating System and version:
Debian 4.9.110-3+deb9u6 (2018-10-08)
* Link to your project:

**Comment by rahulmutt** [comment]
@puffnfresh Do the instructions need to be updated?

**Comment by puffnfresh** [comment]
Yes, the updated instructions are here:

https://github.com/typelead/eta/blob/master/docs/0-user-guides/0-eta-user-guide/1-installation/5-nix.md

I think the website needs to be regenerated.

**Comment by rahulmutt** [comment]
Should be updated now, closing.
