### ISSUE TITLE
Read instance does not work with records

### ISSUE THREAD

**Issue by tittoassini** [typelead/eta#897]
## Steps to Reproduce

data REC = REC {l::Int,r::Int} deriving (Read,Show)

main = print (read "REC {l=3,r=4}" :: REC)

Exception in thread "main" eta.runtime.exception.EtaException: Prelude.read: no parse

## Your Environment
Did you install an older version of Eta/Etlas before?
Yes, but I removed before installing the latest version.

Current Eta & Etlas version:
eta-0.8.6b2.

etlas version 1.5.0.0
compiled using version 2.1.0.0 of the etlas-cabal library

Operating System and version:
macOS Sierra

**Comment by rahulmutt** [comment]
It turns out that fixing #891 fixed this as well since it was the root cause.
