### ISSUE TITLE
Endianess reported incorrectly

### ISSUE THREAD

**Issue by tittoassini** [typelead/eta#899]
## Description
Some packages determine endianess on the base of WORDS_BIGENDIAN from "MachDeps.h".

eta should define this (as java is big endian) but doesn't.

## Steps to Reproduce
{-# LANGUAGE CPP #-}
module Main where
    
#include "MachDeps.h"

isBigEndian :: Bool
isBigEndian =
#if defined(WORDS_BIGENDIAN)
    True
#else
    False
#endif

main = print isBigEndian

Prints out "False" but should be "True"

## Your Environment
Current Eta & Etlas version:
eta-0.8.6b2.

etlas version 1.5.0.0
compiled using version 2.1.0.0 of the etlas-cabal library

Operating System and version:
macOS Sierra

**Comment by rahulmutt** [comment]
Eta has a `MachDeps.h` - https://github.com/typelead/eta/blob/master/libraries/rts/MachDeps.h

Happy to accept a PR for this change.

**Comment by tittoassini** [comment]
does eta set up any CPP constant so that it can be identified at compile time?

**Comment by rahulmutt** [comment]
@tittoassini Yes it does, `ETA_VERSION`. But why would you need that fix this particular problem? Adding `WORDS_BIGENDIAN` definition into `MachDeps.h` should be sufficient right?

**Comment by tittoassini** [comment]
guess so, but in the meantime...
