### ISSUE TITLE
Setup Nightly Builds

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#90]
It's rather cumbersome rebuilding from source every time GHCVM updates (and it updates frequently). We should setup a nightly build system across different platforms - it should build from source at a fixed time everyday and allow you to download the binaries for that day. If anyone knows of any tools/platforms that make this process smoother, please let me know.

In the worst case, if we're not able to find anything, we'll need people to volunteer to setup cron jobs on their systems that run once a day and produce binary builds and uploads the resulting binaries to a server.

**Comment by MrDWilson** [comment]
I don't know of any tools that do that, but I'd be more than willing to set up a Cron if you take that route.

**Comment by rahulmutt** [comment]
We need to resolve #53 before we can work on this for binary builds. The dependence on those files makes installation platform-dependent. Travis allows you to do GitHub releases and Appveyor has a similar feature as well. Travis also allows you to do nightly builds (I've set it up only for `eta-hackage` right now). If you could look into those that would be great.

**Comment by cema-sp** [comment]
@rahulmutt The first step towards binary builds and releases may be **git tags** (they also allow to switch source versions).

**Comment by rahulmutt** [comment]
@cema-sp Thanks for the tip! Hopefully we can get this out soon.

**Comment by rahulmutt** [comment]
While we don't have nightly binaries, we do build Docker images for the latest version of eta which allows people to give a test drive. Nightly binaries is not practical for us right now, and the Docker image is sufficient for a preview.
