### ISSUE TITLE
aeson and http2

### ISSUE THREAD

**Issue by politrons** [typelead/eta#900]
I´m having issues trying to use spock or scotty http server because this two libraries
Any idea if its possible make it works this two F

I’ve read in the issues related of Aeson than there is some patch fot eta but don’t understand how to use that patch.

I’m using gradle.

And this is the error that I receive when I build 
Building library for aeson-1.4.0.0..
Building library for http2-1.6.4..
etlas: Failed to build aeson-1.4.0.0 (which is required by Spock-0.13.0.0).
See the build log above for details.
Failed to build http2-1.6.4 (which is required by Spock-0.13.0.0). See the
build log above for details.

**Comment by jneira** [comment]
Hi! Thanks for trying eta. I am afraid that some haskell packages must be patched to work with eta. The patch is automatically applied by `etlas` using [this repository](https://github.com/typelead/eta-hackage)
There you can check what packages/versions are supported by eta. For `https2` the last supported version is `1.6.2` so we should patch the new version. In the meanwhile, if it fits your requierements, you could use a spock/scotty version that uses `http2-1.6.2`

Aeson is a different case, that version should be supported by `eta` so maybe you could share the full log  of `etlas build -v3` (as a attached file if it is too big) to analyze the possible cause of the error. To know the version of eta/etlas/java/so would be useful too.

**Comment by jneira** [comment]
What versions have you tried so far? Could you share the `cabal` file of your project (or point to the repo)?

**Comment by politrons** [comment]
I'm not using any cabal file, I´m using gradle 

you can take a look here https://github.com/politrons/Eta-Haskell-server/blob/master/build.gradle

And about the version of scotty, well basically I try all versions and nothing

**Comment by jneira** [comment]
Hi @politrons , finally i 've got a working version that, pinning the conflictive dependecies (warp and http2) to the versions supported by eta (you can check the versions [here](https://github.com/typelead/eta-hackage/tree/master/patches))

```
plugins {
    id 'com.typelead.eta' version '0.7.7'
    id 'application'
}

eta {
    version = '0.8.6b2'
    etlasVersion = '1.5.0.0'
}

repositories {
    mavenCentral()
    maven {
        url "http://repo.akka.io/snapshots/"
    }
}


dependencies {
    compile eta('base')
    compile eta('scotty')
    compile eta('warp:3.2.22')
    compile eta('http2:1.6.3')
    compile eta('file-embed')
    compile eta('bytestring')
    compile eta('aeson')
    compile eta('shakespeare')
    compile eta('blaze-html')
    compile eta('text')
    compile eta('template-haskell')
}
```

**Comment by politrons** [comment]
Wow @jneira  amazing job man, you manage to make it work, even with the latest version of Scotty 0.11.2. Thanks a lot!

**Comment by politrons** [comment]
@jneira 
This is adifferent question, but now having all dependencies when I run the server I receive this exception


> Task :run FAILED
"Starting Server at port 3000"
Setting phasers to stun... (port 3000) (ctrl-c to quit)
Exception in thread "main" java.lang.NoClassDefFoundError: eta/network/Utils

I try also to add the network library but seems is already included and is still failing, you can check the simple scotty implementation here  https://github.com/politrons/Eta-Haskell-server/blob/master/src/main/eta/ScottyHttpServer.hs

In have this implementation working in my cabal haskell project so I guess is something related with eta and network library

**Comment by jneira** [comment]
Mmm, `gradle run` in the command line works for me, including http requests like `http://localhost:3000/author`. Are you using IntelliJ? Maybe a cleaning could help.

**Comment by politrons** [comment]
Mmmmm still failing, after clean with gradle. The only thing that I can think about is the Gradle version.

Actually now trying with the local version

I have Gradle 4.
 I cannot clean and run anymore

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.typelead.eta', version: '0.7.7']
> Failed to apply plugin [class 'com.typelead.gradle.eta.plugins.EtaBasePlugin']
   > Could not create an instance of type com.typelead.gradle.eta.internal.DefaultEtaConfiguration_Decorated.
      > org.gradle.api.internal.DefaultDomainObjectCollection.<init>(Ljava/lang/Class;Ljava/util/Collection;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Unable to find method 'org.gradle.api.internal.DefaultDomainObjectCollection.<init>(Ljava/lang/Class;Ljava/util/Collection;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
00:27:05: Task execution finished 'run -PetaSendMetrics=false'.


```

Can you tell me which version are you using to try to use that one.

Also Java 8 "1.8.0_161"

Thanks a lot for all the help man

**Comment by politrons** [comment]
This issue looks related with my gradle version.

https://github.com/typelead/eta/issues/836

I'll update it thanks again!

**Comment by politrons** [comment]
I update to Gradle 4.10.2 and eta from 0.7.7 to  id 'com.typelead.eta' version '0.7.8' since otherwise was not working, but same issue. I can build but the run is failing

**Comment by jneira** [comment]
I think we can close this one, feel free to reopen
