### ISSUE TITLE
dieVerbatim: user error (etlas: '/anaconda3/bin/curl' exited with an error

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta#925]
Trying to do a fresh install of etlas and eta. 

$ java -version returns 

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

## Description
I get an error that image is not found. Not sure what that means.

## Expected Behavior
I'm expecting $etlas update to just work 

## Actual Behavior
$ etlas update
Welcome to Etlas, the awesome build tool for the Eta programming language!

We are working hard to make the best platform for pure functional programming
on the Java Virtual Machine.

Etlas will periodically send usage statistics to help us:

* Make decisions on how to evolve the language

* Build a community portal that displays the data we collect in visual form

* Build an Etlas package repository that will accurately display package popularity

* And more!

For more details, please consult our privacy policy:

        http://eta-lang.org/docs/html/privacy-policy.html

Would you like to help us make Eta the fastest growing programming language,
and help pure functional programming become mainstream? (y/n)

y
Thank you for trying out Eta.

If you face any issues, you can:

* File an issue at:
      https://github.com/typelead/eta/issues/new

* Post your question on Eta-Discuss:
      https://groups.google.com/forum/#!newtopic/eta-discuss

* Ask on the Gitter channel:
      https://gitter.im/typelead/eta

Config file path source is default config file.
Config file /Users/jamesstrieter/.etlas/config not found.
Writing default configuration to /Users/jamesstrieter/.etlas/config
dieVerbatim: user error (etlas: '/anaconda3/bin/curl' exited with an error:
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
Referenced from: /anaconda3/lib/libssh2.1.dylib
**Reason: image not found**

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Did you install an older version of Eta/Etlas before?
* Current Eta & Etlas version:
* Operating System and version:
* Link to your project:

**Comment by rahulmutt** [comment]
It looks like the `curl` from your anaconda is being picked up from your Anaconda installation and it appears it's broken. Can you try to fix that installation?

**Comment by jstr045329** [comment]
What fixed the problem was:

$ conda install libssh2

and then 

$ etlas update
$ etlas select latest
$ etlas repl

worked. Thanks for your help!

**Comment by rahulmutt** [comment]
Great to hear! No problem.
