### ISSUE TITLE
Documentation function compostition typo

### ISSUE THREAD

**Issue by theGhostJW** [typelead/eta#950]
https://eta-lang.org/docs/user-guides/eta-user-guide/functions/composition

**Note that you should read composition pipelines from left-to-right.**

should this not be right-to-left ?

**Comment by rahulmutt** [comment]
@theGhostJW Yes, thanks for the catch. Would you like to submit a PR?

The source file is here:
https://github.com/typelead/eta/blob/master/docs/0-user-guides/0-eta-user-guide/4-functions/2-composition.md

**Comment by theGhostJW** [comment]
done
