### ISSUE TITLE
eta-lang.org certificate expired

### ISSUE THREAD

**Issue by alunduil** [typelead/eta#987]
#  Description

I'm not sure this is the best place to report this so please move if appropriate, but I was visiting eta-lang.org and the presented certificate had expired several days ago (23 when I created this report).

## Expected Behavior

Site should load without any certificate issues.

## Actual Behavior

Chrome presented a dialogue saying the certificate was questionable due to being expired.

## Possible Fix

Update the certificate preferably with ACME so this never occurs again.

## Steps to Reproduce

1. Open web browser
1. Browse to eta-lang.org
1. If your browser doesn't show an error look into the certificate details

Alternatively and perhaps more straightforward:

1. `curl https://eta-lang.org`

Has the following ouptut:

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Context

I was trying to view the eta-lang.org website for information on the project but considered bouncing because I didn't know if it was authoritative.

## Your Environment

/etc/os-release:

```
NAME=NixOS
ID=nixos
VERSION="20.03.2957.c291195eedf (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03.2957.c291195eedf"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Comment by rahulmutt** [comment]
Thanks for reporting this. I'll take a look at renewing the certificate.

**Comment by masflam** [comment]
I also get told by my browser that eta-lang.org doesn't have an active SSL cert, but another thing is that the home page responds with a 404
Also, browsing this repo makes me wonder: is the development of Eta dead? It's been a year since the last commit

**Comment by rahulmutt** [comment]
The website should now be up & SSL cert fixed.. Feel free to file a new issue if there are still issues.
